### ISSUE TITLE
Suggestion: Add ActiveEffects to imported items.

### ISSUE THREAD

**Issue by adriangaro** [MrPrimate/ddb-importer#10]
When importing items it would be possible to add some of the items features to the item as active effects which transfer to the actor on equip.

For example, if a magic item provides you with a new language, an ActiveEffect with the attribute key `data.traits.languages.value` be added and add that specific language.

The same mechanism could be applied to spell bonuses and DC and any such feature which could easily be translated from DDB to FVTT.

**Comment by MrPrimate** [comment]
This is definitely a goal once I have monster importing out the way, an interim step will be #8 to allow copying of active effects from the DAE compendium to matching items.
