### ISSUE TITLE
Option to not overwrite biography information on character import

### ISSUE THREAD

**Issue by TheTural** [MrPrimate/ddb-importer#100]
I'd love to see an option alongside the other import options to exclude the character's biography info from re-imports. Sometimes my players will tweak their backstories, appearance, flaws/bonds/etc in Foundry since we don't utilize DDB except for doing level-ups, and then when re-importing the characters after such it wipes out any formatting or additional info they've added to their bio pages.

It would be ideal if they didn't have to leave Foundry to update DDB in the middle of the game to make such changes and have them stick, since we don't use DDB for anything during gameplay.

I know this is probably an edge case because most people don't ever change those things, but I have some players who are big on their backstories and they like to update it/format it nicely, and all that stuff gets erased when I do a re-import. I do re-imports like this because it's easier to have the players level up themselves on DDB where they can see all the class features, feats, etc they are selecting from, rather than me having to do all their level up stuff manually in Foundry. 

I know there is a solution of "tell them not to do that" or "stop doing imports after every level," but having options to more granularly control the import process is always good imo. It also adds consistency, because right now the Description/Notes tabs from DDB are the only things that can't be included or excluded, while you can do so for essentially the entire rest of the character sheet.

**Comment by MrPrimate** [comment]
I can get this into the 0.5.* release which should be out soon.
