### ISSUE TITLE
Itemmacros not imported from DAE SRD

### ISSUE THREAD

**Issue by adriangaro** [MrPrimate/ddb-importer#102]
It seems some spells(maybe even items) in DAE have itemmacros that are used in the active effects, but they aren't copied(or at least not updated) on the spells in question when munching the spells. Need to check using a clean compendium to munch them in to see if it reproduces there too.

**Comment by MrPrimate** [comment]
The Macros are supplied in a DAE compendium - you will have to import these manually (right click on the compendium and import all content). The macros are not embedded in the spell (as I understand it).

**Comment by adriangaro** [comment]
An example of this would be spiritual weapon, and it had the itemmacro embedded into the spell.

**Comment by MrPrimate** [comment]
@adriangaro  which of the options are you using copy effects or replace item?
