### ISSUE TITLE
Barbarian Rage Active Effect settings do not work properly

### ISSUE THREAD

**Issue by C-S-McFarland** [MrPrimate/ddb-importer#105]
After a fresh import with the 0.6.1 DDB Importer, Rage does not apply the right effect when used by a Barbarian.

I am using the three Experimental Active Effects settings when importing.

1. Once I set a duration of 1 minute and set a target of self, Rage works.
2. The default imported Rage seems to use two resources, a limit in the feature itself and the primary resource of the actor. It's not a problem, really, but it's redundant.

**Comment by MrPrimate** [comment]
Should be fixed in 0.6.2

**Comment by C-S-McFarland** [comment]
I did a fresh import of https://www.dndbeyond.com/profile/Mortizh/characters/43411020 to a new actor and I see that the target is now set. This does enable the rage effect and it is working.

Is it possible to also set a duration so there is a visible icon applied to the tokens and to make sure Raging stops after it's allocated time?

I'll also note that Rage, like some other features (such as Wild Shape) appear to use two resource pools right now. Both a primary attribute slot and a consumption pool on the feature itself. Perhaps there should only be one pool?

I'll try to play with my local edits on the module to see if I can apply some special exceptions like a duration.value and duration.units if that would help.

**Comment by C-S-McFarland** [comment]
I looked into this duration issue more and I can see how that might be too variable to hard-code as a single value. Need to think about this more.

**Comment by C-S-McFarland** [comment]
I think this is fixed based on my testing.
