### ISSUE TITLE
Sneak Attack and Favored Foe get imported as attacks and not as features, and they aren't imported from the conpendiums.

### ISSUE THREAD

**Issue by adriangaro** [MrPrimate/ddb-importer#106]
As the title says sneak attack and favored foe are imported as attacks which aren't imported from conpediums.

I guess in the case of sneak attack, it gets duplicated as the sneak attack feature gets added and can be swapped from compendium, but the attack is still there. For favored foe there is no feature added so no swap from conpendium.

**Comment by MrPrimate** [comment]
I'll add an option to do this in the next release, but it may, potentially, result in some weird behaviour, especially if using Active Effect generation.

**Comment by MrPrimate** [comment]
This is in 0.6.4
