### ISSUE TITLE
TypeError: Cannot read property 'proficient' of undefined

### ISSUE THREAD

**Issue by miromonti** [MrPrimate/ddb-importer#110]
I received this error: 
![image](https://user-images.githubusercontent.com/38819125/111765279-6bfed480-8861-11eb-81c2-ba6721f9d68b.png)

I looked through the DDB sheet's Proficiencies & Languages but don't believe the issue is there: 
![image](https://user-images.githubusercontent.com/38819125/111766028-4920f000-8862-11eb-993c-3e6b398f7c69.png)

Any clue on where to focus my search? Or what exactly to fix?

**Comment by MrPrimate** [comment]
Could you provide a character link?

**Comment by miromonti** [comment]
https://www.dndbeyond.com/profile/Breezy9395/characters/21870270

**Comment by MrPrimate** [comment]
Thanks, I've tracked down the issue and will release a fix later today

**Comment by miromonti** [comment]
Thank you for your prompt attention. Is the fix in 0.6.9? I updated and the error persists. I went so far as to have only ddb-importer running and import into a new character sheet. What now?

**Comment by MrPrimate** [comment]
This will be in 0.6.10 and should be available in the next few minutes.

**Comment by miromonti** [comment]
Import via 0.6.10 worked as expected. I removed the character link, for safety's sake.

Thanks again for your time and effort.
