### ISSUE TITLE
Bug - Switching Compendiums

### ISSUE THREAD

**Issue by Jonwh25** [MrPrimate/ddb-importer#111]
Found a new bug.

Settings:  Compendiums
If you change the Monster Compendium

Then go to the Monster Muncher and change Source to a different source.

Now import monsters. It will default to the previous compendium.  

The only reason I found this is because I'm insane and I'm trying to create different monster compendiums for each sourcebook. (I want monster manual, mordenkainens, etc in their own compendium)

Work around is to set the compendium in settings, then set the source in monster muncher, refresh the screen then import. repeat when making the next change.

**Comment by MrPrimate** [comment]
Fixed.
