### ISSUE TITLE
Weapons not syncing back to DDB

### ISSUE THREAD

**Issue by Pwhitcomb** [MrPrimate/ddb-importer#112]
I was trying to sync back my character after I killed a goblin just for a test. The equipment syncs but the weapons do not. Is there a way to force update just a few select items or am I missing a setting?

**Comment by MrPrimate** [comment]
This _should_ sync - was the weapon imported into the ddb items compendium? If possible can you right click and export the character and direct message it to me on Discord.

**Comment by Pwhitcomb** [comment]
Messaged. I was using Mr. Weaver's Triggler video on auto converting dead NPCs into Loot Sheet and got it from that.

**Comment by MrPrimate** [comment]
Required enhancement: lookup items without id's to sync in compendium.

**Comment by MrPrimate** [comment]
This should now work with the latest version
