### ISSUE TITLE
Optional class features showing up at lower levels

### ISSUE THREAD

**Issue by kaelad02** [MrPrimate/ddb-importer#113]
One of my players has a Ranger with some of the optional class features from Tasha's enabled. One of those is the 10th-level ability Nature's Veil that replaces Hide in Plain Sight. The character is only 3rd level but the feature is showing up on the imported version of the character even though they're not high-enough level to have it.

It doesn't show up on the D&D Beyond version of the character sheet in the Features & Traits section. ~~I don't know how generic this is, whether it happens for other optional class features gained at higher levels.~~ I just checked another character, a Druid, who has Cantrip Versatility. That doesn't kick in until 4th level but they're only 3rd and it's already on their character sheet.

**Comment by MrPrimate** [comment]
Will be fixed v0.6.16
