### ISSUE TITLE
Wrong formula when applying Great Weapon Fighting

### ISSUE THREAD

**Issue by whiteIZE** [MrPrimate/ddb-importer#114]
Great Weapon Fighting allows the PC to reroll a 1 or 2 damage dice roll upon attacking. The roll formula generated for 2h weapons (let's take the great sword[2d6] for example) while having this feature has the damage type in the wrong place:

What's generated: 2d6[slashing]r<=2 + @mod
Result: 2d6 + ability modifier

What is should be: 2d6r<=2[slashing] + @mod
Result: 2d6r<=2 + ability modifier

**Comment by MrPrimate** [comment]
Resolved in 0.6.19
