### ISSUE TITLE
Allow automated sync back to DDB

### ISSUE THREAD

**Issue by twiztedterry** [MrPrimate/ddb-importer#115]
This is not a bug, this is most definitely an Enhancement (I couldn't figure out how to make ENH Reqs through Git).

**User Story:** As a DM, it would be helpful to setup an automatic sync back to DDB to automatically update PC experience points/equipment at the end of a session. This way I do not have to manually track when xp has been applied, and do not run into issues when I forget to apply XP.

Ideally this would be entirely automated, and would run at X time every day (as long as the server is up, of course).

However, having a one-button option to sync all PC's to DDB based on specific presets would be acceptable in this workflow.

**Comment by MrPrimate** [comment]
This is now in Alpha and will be coming to Undying patreons later this month.
