### ISSUE TITLE
Issue with Dueling Fighting Style (and maybe other features)

### ISSUE THREAD

**Issue by nulmas** [MrPrimate/ddb-importer#116]
I think this only happened after the last update, but I'm not sure (I'm a newcomer to Foundry and I've been lost in a sea of modules ;) )

One of my players has the dueling fighting style. After the last import, his damage rolls didn't work because they resulted in a non-numeric value. I checked his character sheet and the problem was that the damage formula was written as "1d8 + 2[slashing] + @mod + 1" instead of "1d8[slashing] + 2 + @mod + 1"

I can't remember any off the top of my head, but I'm pretty sure there are other features that might lead to the same issue.

**Comment by MrPrimate** [comment]
Fixed in 0.6.20
