### ISSUE TITLE
error in spell cost calculation

### ISSUE THREAD

**Issue by kakaroto** [MrPrimate/ddb-importer#117]
Hi, just started looking through your code and I saw this : 
https://github.com/MrPrimate/ddb-importer/blob/11234444239fb4c9485b27cfb170d3b76b1c7f71/src/parser/spells/components.js#L16

The regexp seems wrong to me : `/([\d.]+)\s*gp/`
The `.` would make it match anything, so it should be escaped. 
Also, I noticed that ddb actually uses `,` not `.` (at least in the data that I see : Resurrection spell for example : "a diamond worth at least 1,000 gp, which the spell consumes") so the regexp should use `,` instead of `.`
I'll file issues for anything else I notice. I hope this helps. 👍

**Comment by MrPrimate** [comment]
Thanks!

**Comment by MrPrimate** [comment]
Fixed in the next release.
