### ISSUE TITLE
Reach property should check reach instead of range

### ISSUE THREAD

**Issue by kakaroto** [MrPrimate/ddb-importer#118]
This seems to set the reach property when range is > 5
It should check the reach value, not range, since reach > 5 (or == 10) means the weapon has the reach property, otherwise, it would set it on all ranged weapons.

https://github.com/MrPrimate/ddb-importer/blob/11234444239fb4c9485b27cfb170d3b76b1c7f71/src/muncher/monster/utils.js#L499

**Comment by MrPrimate** [comment]
Fixed in the next release.
