### ISSUE TITLE
sphere target is unhandled + regexp improvement

### ISSUE THREAD

**Issue by kakaroto** [MrPrimate/ddb-importer#119]
I see you handle "x-foot cone" and "x-foot line", but I also noticed "x-foot-radius sphere" as appearing in some places, so I'd recommend also adding support for the sphere target.

https://github.com/MrPrimate/ddb-importer/blob/11234444239fb4c9485b27cfb170d3b76b1c7f71/src/muncher/monster/utils.js#L393

Note also that I found some that use "--" or even "---" instead of "-" (like lightning breath from https://www.dndbeyond.com/monsters/ancient-blue-dragon)
So changing the regexp to use `(\d+)-+foot`  should make it work better.

**Comment by kakaroto** [comment]
Actually, noticing that the "--" is actually 3 characters, there's some unicode invisible char between the two dashes (can't see it but can copy/paste it) : `­-­-`

**Comment by MrPrimate** [comment]
Fixed in the next release.
