### ISSUE TITLE
possibly incorrect regexp for recharges

### ISSUE THREAD

**Issue by kakaroto** [MrPrimate/ddb-importer#120]
https://github.com/MrPrimate/ddb-importer/blob/11234444239fb4c9485b27cfb170d3b76b1c7f71/src/muncher/monster/utils.js#L145

I *think* the regexp here uses the dash in the middle of that list of characters which would make the regexp consider it as "all characters between `–` and `–`). For it not to consider the '-' (dash) as a character to match, it needs to be at the beginning or the end of the `[]` so I would recommend changing this : `[0-9–-–−]` into this : `[0-9––−-]`

**Comment by MrPrimate** [comment]
Fixed in the next release think, would be good to know if you found any monsters where this was an issue.

**Comment by kakaroto** [comment]
Nope, just noticed from "static analysis" of the code. I guess it could still work, since the characters are included, but also includes all the characters in between. I don't know if the dash itself `-` would be inside that unicode range 🤷
