### ISSUE TITLE
Damage could be parsed wrongly due to minus sign

### ISSUE THREAD

**Issue by kakaroto** [MrPrimate/ddb-importer#121]
I haven't looked at the damage parsing code, so not sure where you do that, but I was comparing a couple of imports with my own imports and noticed that the Baboon was not getting any damage to its attack. 

If you look at the baboon : https://www.dndbeyond.com/monsters/baboon
You'll notice the damage is : `1d4 − 1` it's using a "Minus sign" unicode character, rather than the dash character "-". Damage parsing should take the minus sign into account.

We had that same issue in Beyond20 by the way. We just did a mass replace of that character with "-" before doing any parsing.

**Comment by MrPrimate** [comment]
Fixed in next release. Classic regex typo.
