### ISSUE TITLE
Incorrect target configuration for touch spells

### ISSUE THREAD

**Issue by DesktopMan** [MrPrimate/ddb-importer#123]
Rolling imported touch spells results in the following description in chat: "Target: Creature (null Touch)", compared to the SRD version: "Target: Creature".

The only relevant difference between these two seems to be the _target_ configuration:

- Imported: [blank] touch creature
- SRD: 1 [blank] creature

Seen with _Cure Wounds_, _Shocking Grasp_ and _Inflict Wounds_. There are probably more.

**Comment by MrPrimate** [comment]
Are you using something like Better Rolls to modify the chat card description as I can't replicate

**Comment by DesktopMan** [comment]
> 
> 
> Are you using something like Better Rolls to modify the chat card description as I can't replicate

Ah yes, I am using Better Rolls. If you can't replicate it I guess it uses more of the configuration than the standard roll output?

**Comment by MrPrimate** [comment]
Okay I've been doing some testing - I don't really want to stop using the Touch field in Target, as I think the config it parses is a valid combo (i.e. Touch Creature). I'd like to suggest this is a bug with Better Rolls - and it should replace a null value in that field with an empty string.
