### ISSUE TITLE
Error importing character

### ISSUE THREAD

**Issue by dmcrune** [MrPrimate/ddb-importer#125]
Up to now had no issues, however i tried to import a character today, and all give the same error:

Error parsing Character: TypeError: Cannot read property 'getIndex' of null

**Comment by kavukavu** [comment]
Also having the issue: Here is the console output

```
DDB Importer | ERR > TypeError: Cannot read property 'getIndex' of null
    at getCompendiumItems (http://MYIP:30000/modules/ddb-importer/dist/main.js:6986:34)
    at async getCompendiumItemSpells (http://MYIP/modules/ddb-importer/dist/main.js:7241:28)
    at async addMagicItemSpells (http://MYIP:30000/modules/ddb-importer/dist/main.js:7271:52)
    at async CharacterImport.processCharacterItems (http://MYIP:30000/modules/ddb-importer/dist/main.js:25894:7)
    at async CharacterImport.parseCharacterData (http://MYIP:30000/modules/ddb-importer/dist/main.js:26125:5)
    at async HTMLButtonElement.<anonymous> (http://MYIP:30000/modules/ddb-importer/dist/main.js:25583:13)
```

**Comment by MrPrimate** [comment]
Could one of you provide a URL of a problematic character.

**Comment by SeigneurPaladin** [comment]
Same thing.  I have also thie issue since at least wednesday.
I can't paste json neither. (https://character-service.dndbeyond.com/character/v4/character/40193614)

```
POST https://ddb-character.vttassets.com/alwaysPreparedSpells net::ERR_CONNECTION_TIMED_OUT
(anonymous) @ import.js:588
getAlwaysPreparedSpellsOnly @ import.js:585
(anonymous) @ import.js:705
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
import.js:576 GET https://ddb-character.vttassets.com/40193614 net::ERR_CONNECTION_TIMED_OUT
```

Character URL exemple : 
https://www.dndbeyond.com/profile/KhamenTutis/characters/40193614

**Comment by MrPrimate** [comment]
@SeigneurPaladin this error looks like it's coming from the VTTA module, (on account of it talking to the VTTA website) - please log a bug there.  (They do import correctly with DDB-Importer).

**Comment by dmcrune** [comment]
I do not have the vtta module. Error still persists. Here is a character URL that is nmot importing:
https://www.dndbeyond.com/profile/DmcRune/characters/48490472

**Comment by MrPrimate** [comment]
@dmcrune yes, the previous message was for the message that SeigneurPaladin  posted.

**Comment by MrPrimate** [comment]
@dmcrune I've just walked through the same issue with someone else on Discord - can you try resetting your cobalt cookie - I can't replicate the issue locally but it did work for the other user.

**Comment by SeigneurPaladin** [comment]
Oops. Indeed. Wrong module. I uninstalled VTTA and try ddb-importer. It did work well for me.

**Comment by dmcrune** [comment]
@MrPrimate I reset the cobalt cookie, but it is still giving the same error.

**Comment by MrPrimate** [comment]
@dmcrune what version of the following do you have:
- the ddb-importer module your using
- Foundry version
- Foundry D&D 5e system

Can you also let me know which browser you are using.

**Comment by dmcrune** [comment]
@MrPrimate 
ddb-importer: 0.6.32
Foundry: 0.7.9
dnd5e: 1.2.4

Running Foundry from the app itself, but use chrome for players

**Comment by MrPrimate** [comment]
@dmcrune does this error appear only when importing characters in the Foundy app, or if you import them with Chrome as well?

**Comment by MrPrimate** [comment]
Other thoughts - can you check that the compendium defined in the ddb-importer settings for Spells exists? This error is happening when it's trying to look up spells in the compendium to attach to magic items. It should fall back to SRD if it can't find any spells, but this looks like it has failed to resolve the compendium.

**Comment by dmcrune** [comment]
@MrPrimate YES! That seemed to be it! Thank you so much!
