### ISSUE TITLE
Character not importing?

### ISSUE THREAD

**Issue by Mahayana1** [MrPrimate/ddb-importer#126]
Im unable to import Clerics or Paladins into my game (Druids are fine), I have the cookie-thing enabled and other stuff and the error reads out like this
![Screenshot_2](https://user-images.githubusercontent.com/83150804/115979800-df6cc380-a53c-11eb-92fa-b34b119b1800.png)

**Comment by Mahayana1** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/83150804/115979909-881b2300-a53d-11eb-81e1-044d21632d8b.png)

**Comment by MrPrimate** [comment]
Please provide a character link and:
* What browser are you using?
* What version of ddb-importer are you using?

**Comment by Mahayana1** [comment]
I've forwarded these to the discord server but I'll provide them here as
well
https://www.dndbeyond.com/profile/Maliki_lagiban/characters/49128422
(Cleric)
https://www.dndbeyond.com/profile/Theloserlord2365/characters/49053647
(Paladin)
Google Chrome (Molten Hosting)
Foundry 0.79
DDB Importer 0.6.31

**Comment by Mahayana1** [comment]
Resolved by MrPrimate
