### ISSUE TITLE
Imported items have price set as 0

### ISSUE THREAD

**Issue by jfgen** [MrPrimate/ddb-importer#127]
Items imported from DDB have the price set as 0. 

Looking around I haven't found anything about this being intended so I'm assuming its a bug or a feature request.

**Comment by MrPrimate** [comment]
This is fixed in the next release 1.0.3.

**Comment by MrPrimate** [comment]
Ah, actually, this isn't really a bug - most items don't have price associated with them and so the field gets left blank, which Foundry then defaults to zero.
