### ISSUE TITLE
Paladin's Divine Sense imports wrong value

### ISSUE THREAD

**Issue by noodohs** [MrPrimate/ddb-importer#13]
When importing a paladin character, the number of uses of Divine Sense should be 1+CHA modifier. In the case of my specific character, this should be a total of 4 uses, but it imports as 3 total. I believe it is only factoring in the CHA modifier, which is +3, and not the additional +1. VTTAssets also has this issue if that means anything.

**Comment by MrPrimate** [comment]
This is fixed in the next version 0.0.15, thanks for your report!
