### ISSUE TITLE
Feature request: Allow disabling of default import compendiums

### ISSUE THREAD

**Issue by RogueEntityX** [MrPrimate/ddb-importer#130]
Is it possible to allow the disabling of the default compendiums included with the module?

I prefer to have all my imports go into custom shared compendiums, rather than the default world compendiums, so that I can do my import/updates in a single world, and have that propagate to all worlds where I have the import module active. Then I do not need to import/update in EVERY world. Unfortunately, that leaves me with all the empty default compendiums taking up space in my already crowded compendiums tab.

I realize I could edit the module for this, but since you update fairly regularly, they would keep appearing each time.

**Comment by MrPrimate** [comment]
Hi, this setting already exists in the compendium setup page of the config. Set the compendiums to your shared compendiums, uncheck the box on the setting called "Create default compendiums if missing?". then delete the default ones.

**Comment by RogueEntityX** [comment]
Ah, I see now. I guess I misunderstood how that functioned. Thanks for your response.On May 14, 2021 4:48 p.m., Jack Holloway ***@***.***> wrote:
Hi, this setting already exists in the compendium setup page of the config. Set the compendiums to your shared compendiums, uncheck the box on the setting called "Create default compendiums if missing?". then delete the default ones.
