### ISSUE TITLE
Spell Muncher TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Bcpoole** [MrPrimate/ddb-importer#135]
FoundryVTT: 0.8.6
Importer: 2.1.3, 2.1.4

Receiving the following error when running Spell Muncher. Item muncher works fine.
```
main.js:5947 DDB Importer | ERR > TypeError: Cannot read property 'name' of undefined
    at http://localhost:30000/modules/ddb-importer/dist/main.js:26588:24
    at Array.map (<anonymous>)
    at parseSpells (http://localhost:30000/modules/ddb-importer/dist/main.js:26587:4)
    at async Function.parseSpells (http://localhost:30000/modules/ddb-importer/dist/main.js:29392:7)
```

**Comment by MrPrimate** [comment]
Hi, if you're on Discord can you reach out so I can get some debug info you don't want to post on github :) 
If not, do you have any homebrew spells in your collection? (And I'm going to assume you're using D&D 1.3.3?)

Thanks

**Comment by Bcpoole** [comment]
Ok weird, it's working now and I didn't change anything other than update some modules today, including this to 2.1.5. Maybe your most recent change fixed it our DDB had a bug on their end?
