### ISSUE TITLE
Bundled manifest does not allow updates

### ISSUE THREAD

**Issue by akrigline** [MrPrimate/ddb-importer#14]
The `module.zip` release artifact which is downloaded on installation includes a `module.json` where the `manifest` url is locked with that version instead of being a url pointed at the latest manifest. 

The `manifest` should instead point to `https://github.com/mrprimate/ddb-importer/releases/download/latest/module.json`.

You have the correct url in your "module.json" release artifact, but it is not correct in the module.zip artifacts.

Here's a rather robust [article on the wiki](https://foundryvtt.wiki/en/development/guides/releases-and-history) with some more details if you're curious.

**Comment by MrPrimate** [comment]
Yep, this is corrected in recent versions, but I have not updated some historic artifacts

**Comment by akrigline** [comment]
Magnificent, thanks!
