### ISSUE TITLE
Adventure importer issue 

### ISSUE THREAD

**Issue by Luckypiee** [MrPrimate/ddb-importer#143]
There was no problems, with it in the beginning 2 days ago, but now there's no light on the maps. 
We're talking about Rime of the frost maiden, and now the journals don't appear on the map either. 

I tryed importing it on both the forged, and my local machine more then 6 times with out luck to get it to work. 
I'll deleted everything multiple times and monched alle items, spells and monsters the same mount of times after i deleted it ofc. just to make sure I didn't get anything wrong. 

I don't know what the issue is, but I thought I would let you know. 
Maybe you know a solution?

**Comment by MrPrimate** [comment]
What versions are you using for:

* Foundry?
* DDB Importer?
* Adventure Muncher?

It might be easier to hop on Discord to have a chat with people about this issue as well.
