### ISSUE TITLE
Error when importing character with homebrew item.

### ISSUE THREAD

**Issue by sandercuppen** [MrPrimate/ddb-importer#144]
The character has a magic staff, the error suggests it cannot match an icon from the srd.
[foundry.tojnk.nl-1625336233842.log](https://github.com/MrPrimate/ddb-importer/files/6758861/foundry.tojnk.nl-1625336233842.log)

**Comment by MrPrimate** [comment]
Darker Dungeons disables the SRD compendiums, so you can't use the options which load from the SRD either items or icons.

**Comment by sandercuppen** [comment]
Thanks for spotting that! Didn't realize it was incompatibility with another module.
