### ISSUE TITLE
Monster Import not importing Armor

### ISSUE THREAD

**Issue by Allmight** [MrPrimate/ddb-importer#146]
The monster importer does not import the armor worn by monsters. Gobling for example should have Leather Armor and a Shield. But after import those are missing but AC is right. But when i add the shield and armor to the goblin (note, i use DAE), the AC bugs out unless i change the AC to it's "naked" AC before adding the shield and armor.

**Comment by MrPrimate** [comment]
For monsters it does not attempt to parse out armor items at the moment. This is a requested enhancement.

**Comment by MrPrimate** [comment]
Now available.
