### ISSUE TITLE
Imported Adventures Scenes Missing

### ISSUE THREAD

**Issue by Vhostymr** [MrPrimate/ddb-importer#148]
I am on Foundry v. 0.8.8 and trying to run the adventure importer. I have been able to successfully generate the fvttadv files from the importer with the generated config. I opened these files with 7zip and was able to confirm it grabbed all the assets correctly from D&D Beyond. However, when using the import muncher, it would create the folders correctly, but the scenes would be black. I could view the tokens and doors (if present), but it looks like the map itself did not correctly associate with the scene. I am on the newest version of the importer as well.

If you need any logs or additional info, let me know.

Thanks!

**Comment by MrPrimate** [comment]
This sounds weird.... Any chance you could pop along to the Discord to troubleshoot this as it might be a number of things.

**Comment by Vhostymr** [comment]
Absolutely. Heading over there now.

**Comment by Vhostymr** [comment]
Seems to be a conflict with Scene Defaults. I added a new issue on their repo since it appears to be on their end.

https://github.com/BradfordC/FoundryVTT-Scene-Defaults/issues/6
