### ISSUE TITLE
Convert imported images to WebM 

### ISSUE THREAD

**Issue by Varriount** [MrPrimate/ddb-importer#149]
Currently, any avatar & token images are imported in the format they originally were on DDB. Many of these are PNGs, and while PNG isn't bad, it's not the best format when it comes to minimizing storage space. It would be very convenient if the importer allowed automatically converting these images into WebP, as it would allow reducing the amount of space taken up by images.

Some initial research suggests that the amount of space saved would be ~60% for PNG files, with less for JPEG files. An [Emscripten/Webassembly-compiled version of FFmpeg](https://github.com/Kagami/ffmpeg.js/) could be used to carry out the conversion.

**Comment by MrPrimate** [comment]
New setting in core settings to enable webp mode. This will convert all images when loaded through muncher or characters into webp files. What is webp? It's a image storage format that makes images very small. Note if you turn this on and update monsters/spells/items/etc it won't remove the old images - you'll have to do that manually. Consider changing the upload directories for images both for characters and adventures if you wish to migrate stuff to save space.
