### ISSUE TITLE
Tidy5e Sheet compatibility

### ISSUE THREAD

**Issue by ravingdragoon** [MrPrimate/ddb-importer#155]
Currently, importing a character with D&D Beyond Importer while using Tidy5e Sheet seems to work, however upon reloading the page all active effects are missing.

**Comment by MrPrimate** [comment]
I suspect this is not a Tidy5e problem but the following bug: https://gitlab.com/foundrynet/foundryvtt/-/issues/5309

I use Tidy myself, so pretty sure it's not an incompatibility.

**Comment by ravingdragoon** [comment]
I am not sure what the difference is then, I use the import with only the necessary modules installed and it works fine, then I add back in only Tidy5e Sheet and it bugs out again.

**Comment by MrPrimate** [comment]
What version of Foundy, DDB and DAE are you using?

**Comment by ravingdragoon** [comment]
I was using Foundry 0.8.8 (now on 0.8.9 with the same problem), the most recent version of DAE, and Chrome Version 92.0.4515.159. The problem still doesn't occur when I only have the required modules installed, but the starts to happen again as soon as I turn on Tidy5e Sheet. I am now also getting an error at or near the end of import. I will submit a different bug report for that, because I am not sure if it is related.

**Comment by adriangaro** [comment]
I can second this behaviour, when I deactivated tidy5e sheet, every import works without an issue, however when I have it activated it breaks almost everytime with `The key xxxx does not exist in the EmbeddedCollection Collection` like in the ticket mentioned above.

**Comment by MrPrimate** [comment]
@adriangaro this is a core Foundry bug based on race conditions - the more modules you have that do _stuff_ the more likely it is to occur - due to how much stuff the tidy sheet does the race condition occurs. I'm going to close this issue as it's not a problem with DDB Importer, but how Foundry works in v8. It may be fixed in v9 if the bug gets prioritised.
