### ISSUE TITLE
Thumbnails not accessable during Monster Munch

### ISSUE THREAD

**Issue by ravingdragoon** [MrPrimate/ddb-importer#160]
I received the following errors when doing a Monster Munch. It seems that some of the files are not available for some reason.

revivi.fi/avernum/icons/death-juice.png?cors-retry=1629119000593:1 Failed to load resource: net::ERR_FAILED
06:13:24.932 london.drop.mrprimate.co.uk/https://media-waterdeep.cursecdn.com/avatars/thumbnails/6566/330/400/680/636988831933632399.jpeg:1 Failed to load resource: the server responded with a status of 403 ()  
06:18:30.550 london.drop.mrprimate.co.uk/https://media-waterdeep.cursecdn.com/avatars/thumbnails/6221/837/400/1036/636953243281185872.jpeg:1 Failed to load resource: the server responded with a status of 403 ()  
06:19:11.273 london.drop.mrprimate.co.uk/https://media-waterdeep.cursecdn.com/avatars/thumbnails/13603/411/400/207/637397531920717188.jpeg:1 Failed to load resource: the server responded with a status of 403 ()  
06:20:29.685 london.drop.mrprimate.co.uk/https://media-waterdeep.cursecdn.com/avatars/thumbnails/11697/791/400/406/637308566330293443.jpeg:1 Failed to load resource: the server responded with a status of 403 ()  
06:32:21.762 london.drop.mrprimate.co.uk/https://media-waterdeep.cursecdn.com/avatars/thumbnails/7095/924/400/1204/637036062004184885.jpeg:1 Failed to load resource: the server responded with a status of 403 ()  
06:40:59.410 london.drop.mrprimate.co.uk/https://media-waterdeep.cursecdn.com/avatars/thumbnails/19703/436/400/400/637645525180364067.png:1 Failed to load resource: the server responded with a status of 403 ()  
06:41:07.941 london.drop.mrprimate.co.uk/https://media-waterdeep.cursecdn.com/avatars/thumbnails/11701/993/400/747/637308732929032749.jpeg:1 Failed to load resource: the server responded with a status of 403 ()  
06:42:49.713 main.js:10053 GET https://london.drop.mrprimate.co.uk/https://media-waterdeep.cursecdn.com/avatars/thumbnails/7095/917/400/1066/637036061664737937.jpeg 403  
(anonymous) @ main.js:10053  
downloadImage @ main.js:10052  
process @ main.js:10093  
uploadImage @ main.js:10114  
getImagePath @ main.js:2438  
async function (async)  
getImagePath @ main.js:2430  
getNPCImage @ main.js:3334  
async function (async)  
getNPCImage @ main.js:3321  
buildNPC @ main.js:3545  
parseNPC @ main.js:3590  
(anonymous) @ main.js:3598  
addNPC @ main.js:3597  
parseCritters @ main.js:16802  
async function (async)  
parseCritters @ main.js:16802  
06:42:49.713 main.js:1526 DDB Importer | ERR > Image upload error Could not retrieve image
log @ main.js:1526  
error @ main.js:1548  
uploadImage @ main.js:10117  
async function (async)  
uploadImage @ main.js:10114  
getImagePath @ main.js:2438  
async function (async)  
getImagePath @ main.js:2430  
getNPCImage @ main.js:3334  
async function (async)  
getNPCImage @ main.js:3321  
buildNPC @ main.js:3545  
parseNPC @ main.js:3590  
(anonymous) @ main.js:3598  
addNPC @ main.js:3597  
parseCritters @ main.js:16802  
async function (async)  
parseCritters @ main.js:16802

**Comment by MrPrimate** [comment]
This should be resolved now
