### ISSUE TITLE
Imported Ring of Protection not applying bonus AC

### ISSUE THREAD

**Issue by rossmcnulty** [MrPrimate/ddb-importer#161]
Seems to have happened after the AC changes to the 5e system in Foundry.

Character:
https://www.dndbeyond.com/profile/Blue_Heron/characters/50710374

I made sure to re-import items using the muncher, and even with the ring of protection equipped, his AC is 20, not 21.
![image](https://user-images.githubusercontent.com/2968279/129599146-b23e34e8-6864-411d-bb92-c301f40ff358.png)

**Comment by MrPrimate** [comment]
Ah! I'll try and get a fix in for this, but with the new AC stuff, you almost certainly want to install Dynamic Active Effects to get AC bonuses from things like Rings of protection -  you don't need to use any of the other features, just have DAE installed and active.

**Comment by MrPrimate** [comment]
There is a temporary work around in v 2.3.9 that will create an effect that works without DAE, but not sure if I will keep that or move back to setting a flat AC if DAE is not installed.

**Comment by MrPrimate** [comment]
Have enhanced this in the latest version, closing this issue.
