### ISSUE TITLE
Item Muncher is not Importing Rarity

### ISSUE THREAD

**Issue by lizShack** [MrPrimate/ddb-importer#162]
With the update to DnD 5e, Rarity is a dropdown, not a string value. Now, importing items has a blank value for rarity. Updating the items doesn't seem to update it, and neither does fully reimporting the compendium

![image](https://user-images.githubusercontent.com/7528068/129815423-c0847276-a865-40b2-8265-c64bd8e005e9.png)

**Comment by MrPrimate** [comment]
This will be in v2.3.11
