### ISSUE TITLE
Spell Muncher not munching in new world

### ISSUE THREAD

**Issue by 95Gman** [MrPrimate/ddb-importer#164]
![image](https://user-images.githubusercontent.com/74572009/130344405-112b7ac7-e02d-453f-bcdb-bf991d4e5770.png)
Not sure what this means. Maybe you'll make sense of it. Item Muncher worked fine.

**Comment by MrPrimate** [comment]
Which version of Foundry, 5e and DDB Importer are you using?

**Comment by 95Gman** [comment]
Foundry 0.8.9, DnD5e 1.4.2, Importer 2.3.12.
btw the name is bugged:
![image](https://user-images.githubusercontent.com/74572009/130376963-f4e5efe2-93ec-4729-9baa-d5938459a064.png)
