### ISSUE TITLE
Updated to 2.4.8, module disappeared from server.

### ISSUE THREAD

**Issue by SavageNH** [MrPrimate/ddb-importer#167]
Updated to the latest version (2.4.8 running on Foundry 0.8.9), and the module completely disappeared from the server. 

It does not appear in the list of installed (or uninstalled) modules, and the import icons do not appear on the character sheets.

I've tried uninstalling and reinstalling the module via Forge to no effect.

**Comment by MrPrimate** [comment]
Please reach out to the forge - the package is installing fine here and on test machines. Does it happen if you install this in a local version?
