### ISSUE TITLE
DDB Importer titled "Dam;pD Beyond" (Up to date)

### ISSUE THREAD

**Issue by Blueimmunity** [MrPrimate/ddb-importer#168]
Whenever I insert the character sheet URL into the URL search bar, the window freezes. It's stuck on getting character data. I have triple-checked the module to make sure it is up to date. Also, my module is called D&am;pD Beyond importer. I asked another DM and his read correctly.

**Comment by MrPrimate** [comment]
This is a Foundry bug https://gitlab.com/foundrynet/foundryvtt/-/issues/5738
