### ISSUE TITLE
Module Name (Character Glitch?) 

### ISSUE THREAD

**Issue by adrianpinnock** [MrPrimate/ddb-importer#169]
Not certain how to explain this. Instead of the module being displayed as D&D Beyond Importer, it displayed as D&"amp;"D Beyond Importer. Doesn't seem to affect how the module functions but drives me crazy. (see screenshot below)

![image](https://user-images.githubusercontent.com/1498139/132074049-f04ffe31-5988-45cb-a792-dc53e8b85c88.png)

**Comment by MrPrimate** [comment]
Duplicate of #168
