### ISSUE TITLE
Token Vision 0

### ISSUE THREAD

**Issue by ravingdragoon** [MrPrimate/ddb-importer#173]
Every time I import from dndbeyond, all of my players' prototype tokens have their vision changed to 0 in the Dim Vision and Bright Vision fields, no matter how I have defaults set up, or what the prototypes were set to before import. I do not receive any errors when performing the import, so I am not sure what is causing the issue. Below are my settings and systems. Also, as a side note, your Changelog link on The Forge points to your Readme file instead of your Changelog.

```Versions:
  Foundry: 0.8.9
  System: dnd5e version 1.4.3
User:
  Role: GAMEMASTER
Settings:
  Disable_Canvas: Disabled
  Max_FPS: 60
  Token_Drag_Vision: Disabled
  Soft_Shadows: Enabled
  Token_Vision_Animation: Enabled
  Light_Source_Animation: Enabled
  Zoomed_Texture_Antialiasing: Enabled
  Animate_Roll_Tables: Disabled
Scene:
  Walls: 204
  Lights: 1
  Tokens: 14
  Tiles: 0
  Sounds: 0
  Drawings: 1
  Notes: 10
  Dimensions: 4800 x 6600
  Background: 4800 x 6976
  Foreground: 0 x 0
WebGL:
  Context: WebGL2RenderingContext
  GL_Vendor: WebKit
  Renderer: WebKit WebGL
  Unmasked_Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7141)
  WebGL_Version: WebGL 2.0 (OpenGL ES 3.0 Chromium)
  MAX_TEXTURE_SIZE: 16384
  MAX_RENDERBUFFER: 16384
Database:
  Actors: 265
  Items: 309
  Scenes: 75
  Journals: 941
  Tables: 86
  Chat: 255
  Macros: 415
Data_Sizes:
  Actors: 15.31 MB
  Items: 1.41 MB
  Scenes: 6.37 MB
  Journals: 6.93 MB
  Tables: 1.34 MB
  Chat: 255.94 KB
  Macros: 753.9 KB
Browser:
  Platform: Win32
  Vendor: Google Inc.
  Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
Memory:
  Heap_Limit: 4 GB
  Heap_Total: 263.34 MB
  Heap_Used: 214.43 MB
Modules:
  Total: 373
  Enabled: 29
Active_Modules:
  Dynamic-Effects-SRD: Dynamic Active Effects SRD v6.0.01
  about-time: About Time v1.0.4
  advanced-macros: Advanced Macros v1.11
  api: HTTP API v0.3
  condition-automation: Condition Automation v3.0.2
  conditional-visibility: Conditional Visibility v2.0.11
  dae: Dynamic effects using Active Effects v0.8.55
  ddb-importer: D&D Beyond Importer v2.5.8
  debug-report: Debug Report Generator v0.0.2
  dnd5e-helpers: DnD5e Helpers v3.0.2
  foundryvtt-simple-calendar: Simple Calendar vv1.3.44
  grape_juice-isometrics: Grape Juice Isometrics v0.0.23
  lib-wrapper: libWrapper v1.10.6.0
  magicitems: Magic Items v2.1.2
  midi-qol: Midi QOL v0.8.61
  midi-srd: Midi SRD v0.1.02
  module-sets: Module Sets - Dual Track GMing, baby v1.0.1
  perfect-vision: Perfect Vision v2.10.1
  rounded-distance-for-measured-templates: Rounded Distance for Measured Templates v0.5.1
  scaleGrid: Grid Scale Menu v0.0.14
  smalltime: SmallTime v1.13.0
  socketlib: socketlib v1.0.9
  t-is-for-target: T is for Target v0.4
  template-wall-collision: Template Wall Collision v1.0.3
  tidy-ui_game-settings: Tidy UI - Game Settings v0.1.25
  times-up: times-up v0.8.13
  token-hud-wildcard: Token HUD Wildcard v1.4.0
  tokenmagic: Token Magic FX v0.5.2.1
  forge-vtt: The Forge v1.10
```

**Comment by MrPrimate** [comment]
Do the characters have dark vision? If not the default Foundry vision settings would be to set these to 0.

**Comment by ravingdragoon** [comment]
They all have darkvision. The only one that is parsing correctly is the Twilight Cleric with 300 ft of Darkvision.

**Comment by MrPrimate** [comment]
Can you provide some character links please

**Comment by ravingdragoon** [comment]
Sure.

https://www.dndbeyond.com/characters/34780336  
https://www.dndbeyond.com/characters/34801181 (This is the one that parses correctly)
https://www.dndbeyond.com/characters/29957367
https://www.dndbeyond.com/characters/29927542
https://www.dndbeyond.com/characters/25053393
https://www.dndbeyond.com/characters/25044812

**Comment by ravingdragoon** [comment]
My settings, in case they are a problem.

![image](https://user-images.githubusercontent.com/72875320/134776660-8baab40b-8cb0-4b56-9c23-cfb62fc06a2b.png)
![image](https://user-images.githubusercontent.com/72875320/134776686-a3466a21-0949-47b6-8e7f-05db2d5b179d.png)
![image](https://user-images.githubusercontent.com/72875320/134776703-dc886ada-053a-4a12-882b-89a54d5c8db6.png)

**Comment by MrPrimate** [comment]
Ah! So the problem is probably the Senses ticked for racial traits in the active effects for characters - tokens don't pick up on active effect change so you would need to use something like https://github.com/kandashi/Active-Token-Lighting to get active effects to change a tokens senses, as racial darkvision is now granted via an active effect rather than hardcoded - I would normally recommend not using Senses or Movement as an active effect for racial and class features, especially if its unlikely you would ever need to turn them off.

**Comment by ravingdragoon** [comment]
Ah. That did solve the problem. Thank you so much!
