### ISSUE TITLE
Rogue Sneak Attack ability not being transferred.

### ISSUE THREAD

**Issue by flynnkd** [MrPrimate/ddb-importer#178]
I have a tabaxi, 8th rogue (Soulknife) 4 sorcerer (Clockwork) where the Sneak Attack feature does not get transferred across.

**Comment by MrPrimate** [comment]
Can you provide a character link, and screen shots of the settings you're using on the Import Character, Advanced Settings and Active Effect tabs?

**Comment by flynnkd** [comment]
https://ddb.ac/characters/44390846/WOn3GN

[image: Roger screen.png]


Kevin Flynn
Mob: 0412380188
www.flynnkd.com
Facebook: https://www.facebook.com/mappingcards
Discord: flynnkd#7958

**Comment by flynnkd** [comment]
[image: ddbeyond screen.png]


Kevin Flynn
Mob: 0412380188
www.flynnkd.com
Facebook: https://www.facebook.com/mappingcards
Discord: flynnkd#7958

**Comment by MrPrimate** [comment]
As discussed on Slack, fix in latest release.
