### ISSUE TITLE
Cannot load unpacked folder

### ISSUE THREAD

**Issue by Rumfitt89** [MrPrimate/ddb-importer#179]
Every time I try to upload the unpacked folder to chrome extension I get the following message:

Failed to load extension
File
~\Downloads\ddb-importer unzipped
Error
Manifest file is missing or unreadable
Could not load manifest.

Any advice?

**Comment by MrPrimate** [comment]
For the chrome extension you want https://github.com/MrPrimate/ddb-importer-chrome

**Comment by Rumfitt89** [comment]
Excellent this has worked. Do you have a patreon as I would like to give you some money as a thanks for your excellent work?

**Comment by MrPrimate** [comment]
Good to hear, if you wish to support me you can do so at https://patreon.com/mrprimate 

Thanks!
