### ISSUE TITLE
Error parsing Character: Error: Required field BrightSight not present in PrototypeToken

### ISSUE THREAD

**Issue by SirTman** [MrPrimate/ddb-importer#18]
Trying to add one of my players D&D Beyond characters to Foundry with the importer and I got this error.

![image](https://user-images.githubusercontent.com/15119804/99748378-589a6180-2b2c-11eb-9a53-b5a3c3d9f914.png)

Character: https://ddb.ac/characters/23966661/dSq2g0
I thought it might have had to do with the Players Truesight however I removed the truesight waited about 20 min and still got the same error, so I added it back.
I can add all the other characters in the campaign with no issue but it's just this one player character I am unable to add. I've tried going through the token to find any brightSight setting but I can't find one.

**Comment by MrPrimate** [comment]
This is weird - are you adding the Truesight via a custom sense? (It currently shows up on the character sheet, but in the JSON is a null value). I have pushed a fix in 0.0.18 which will allow the import to continue, but the value may be set to null on the character sheet.

**Comment by SirTman** [comment]
That's alright. As long as it works I am happy to fill in the blanks.
