### ISSUE TITLE
Monster Muncher getting stuck.

### ISSUE THREAD

**Issue by KJTailor** [MrPrimate/ddb-importer#180]
Hi,

I tried importing the 88 monster stat blocks from the new Fizban's book. The spells and items imported immediately without an issue, but the monsters are getting stuck.

In detail: When I start the import (exclusive only Fizban's) it will tell me it found 88 monsters to import and then start the import. However, it will never progress past a monster. No I am not impatient, I left it like that for about 1 h, with not progress whatsoever.
What does work though, is closing the monster muncher and re-opening it. The previously imported monster is integrated into the compendium and it goes on to the next... just to get stuck again. Close monster muncher, re-open, restart import, import monster #2, and it gets stuck on #3. Rinse and repeat.

It clearly does import things, but for some reason it has issues importing the monsters properly?
Relevant mods that I am using could be one that allows folders in compendiums?

Any idea, what's wrong here?

Cheers

**Comment by MrPrimate** [comment]
Can you try with other mods disabled to rule that out as a possibility?

**Comment by KJTailor** [comment]
yeah, sadly [Compendium Folders](https://github.com/earlSt1/vtt-compendium-folders) was interfering with it. guess I have to disable it, import everything I want and re-enable it.|
Mind be worthwhile putting something up in "Known Issues" or something?

Thanks though

**Comment by MrPrimate** [comment]
Okay, Compendium FOlders should be compatible - might be worth cleaning that compendium using the cleaning tool in Compendium Folders and trying again.

**Comment by ravingdragoon** [comment]
I am having the same issue. I tried fixing the compendium, then I tried cleaning them, same result. I get the following errors, the first almost immediately when I start the Monster Munch, the second and third after it is done parsing and is actually trying to import the monsters into the folders.

```
20:34:62.318 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
[Detected 1 package: ddb-importer]
    at compendiumFolders (main.js:2933)
    at main.js:2960
    at Array.forEach (<anonymous>)
    at updateCompendium (main.js:2959)
    at async Function.parseItems (main.js:22088)
compendiumFolders @ main.js:2933
(anonymous) @ main.js:2960
updateCompendium @ main.js:2959
await in updateCompendium (async)
updateCompendium @ main.js:2959

20:40:08.098 main.js:1626 DDB Importer | ERR > error parsing NPC: TypeError: Cannot read properties of undefined (reading 'name') Adult Emerald Dragon
log @ main.js:1626
error @ main.js:1646
(anonymous) @ main.js:4159

20:40:08.098 main.js:1626 DDB Importer | ERR > TypeError: Cannot read properties of undefined (reading 'name')
    at compendiumFolders (https://assets.forge-vtt.com/bazaar/modules/ddb-importer/2.6.19/dist/main.js:2933:87)
    at addNPCToCompendium (https://assets.forge-vtt.com/bazaar/modules/ddb-importer/2.6.19/dist/main.js:3828:82)
    at async parseNPC (https://assets.forge-vtt.com/bazaar/modules/ddb-importer/2.6.19/dist/main.js:4148:3)
log @ main.js:1626
error @ main.js:1646
(anonymous) @ main.js:4160
```

**Comment by dpschreiner** [comment]
for me on forge-vtt, the importer always freezes while importing "Alhoon" from Volo's Guide.

I tested another monster from Volo's: Archdruid using the search filter, and it worked fine.

as a workaround, is there a way to specify a boolean NOT in the monster search filter?  i looked through the code and couldn't find where body.searchTerm is actually used.

**Comment by dpschreiner** [comment]
sorry, i did also test this with only the ddb-importer module enabled.

**Comment by dpschreiner** [comment]
some monsters other than Alhoon that seem to hang, in case there is a common cause (perhaps to do with spells?):

Nezznar the Black Spider
Mind Flayer Arcanist
Githzerai Monk
Arcanaloth (summoner variant)
Drow Mage

**Comment by MrPrimate** [comment]
@dpschreiner All the monsters work for me on the forge

What version of DDB Importer, Foundry and 5e are you using?

(And you imported the spells first right?)

**Comment by dpschreiner** [comment]
DDB importer: 2.6.22
Foundry: 0.8.9
5e: 1.5.5

i did import spells first, but it's possible i failed to do so once...  should i just delete various compendia and try again?

**Comment by MrPrimate** [comment]
@dpschreiner what error message do you get in the console?

**Comment by dpschreiner** [comment]
not sure if relevant but i am using DAE SRD Items for imported spells..  (and almost everything else).  do you recommend a separate compendium?

**Comment by MrPrimate** [comment]
@dpschreiner you should use a separate compendium.

You're also going to want to not use the DAE or a compendium supplied by a module as when they update they replace the entire content.

**Comment by dpschreiner** [comment]
thank you very much.  it is proceeding now!
