### ISSUE TITLE
Problem with DND Beyond Importer

### ISSUE THREAD

**Issue by Maustaler** [MrPrimate/ddb-importer#181]
Since 5 days we have been getting a lot of error messages when we log into a campaign in the FoundryVTT.

I have now tested the following in several campaigns:
All modules deactivated and module by module activated until the error messages reappear.

With the module "DND Beyond Importer" the error messages go off.

As of yesterday we can no longer import any characters.

Error see screenshot, if you need more logs, please write to me.

Briefly about my surroundings:
Foundry VTT runs on a Windows Server 2019 with IIS.
Foundry Version: 0.8.9
DND Beyond Importer Version: 2.5.33
GameSystem: DND5e - Version 1.5.3

greeting
Martin

![image](https://user-images.githubusercontent.com/93937790/140786753-5b44792b-163a-4a27-ae7a-7b2b69e8c3ac.png)

**Comment by MrPrimate** [comment]
The compendium messages indicate that the DDB Compendiums are not set correctly - can you make sure that the Settings -> Modules -> DDB Importer -> Compendiums are set correctly.

Regarding character imports, what errors are you getting?

**Comment by MrPrimate** [comment]
Closed via Discord - compendium settings had become borked.
