### ISSUE TITLE
Issue with Linked Items and auto update to DnD Beyond

### ISSUE THREAD

**Issue by ctbritt** [MrPrimate/ddb-importer#182]
Having what I think is a ddb-importer + Link Item & Resource DnD5e. I've set up an item called Javelin (Thrown), which uses the new Link Item functionality to link ammo to a resource slot. I also have the auto-update to DDB turned on. When I set the number of Javelin (Thrown) to some number, say, 5, and use it, the quantity drops to 1 and multiple versions of the Javelin (Thrown) are created on the char sheet. This ONLY happens when DDB-importer auto update to DDB is on. Works fine when it's off. So I think it's an issue here. 

Definitely seems related to the auto update of DDB-import, because I just looked at the char sheet on dndbeyond.com, and the char had several dozen javelins... 

Hope this helps.

**Comment by MrPrimate** [comment]
Thanks for the issue - this will be fixed in v 2.6.17 released in the next few hours. You'll want to re-import your characters from DDB to get it to work correctly, and probably remunch your items to the items compendium you're using.
