### ISSUE TITLE
Import Character - TypeError: effects.push is not a function

### ISSUE THREAD

**Issue by ochiwan** [MrPrimate/ddb-importer#188]
If I try to import this character, https://www.dndbeyond.com/profile/BennyLiquid/characters/57031786, I get an error. The error is:

Error parsing Character: TypeError: effects.push is not a function

D&D beyond importer is version 2.6.25 in my installation. Also, the character importer seems to work fine for any other character in my campaign.

![image](https://user-images.githubusercontent.com/24800423/145328517-219dfb36-1e00-470e-9e92-32954a1f8653.png)

**Comment by MrPrimate** [comment]
There is a bug here (which I will push a fix for), but I believe the equipped generic "Adamantine Armor" item is causing an issue as it's AC is set to 0/null.

**Comment by MrPrimate** [comment]
Fixed in v2.6.26

**Comment by ochiwan** [comment]
Thanks!
