### ISSUE TITLE
Monster Muncher Import Fails When Creating Compendium Folders

### ISSUE THREAD

**Issue by Varriount** [MrPrimate/ddb-importer#190]
During the monster import process, when:
  - Usage of compendium folders is enabled.
  - Not all compendium folders of the selected kind (A-Z, Monster Type, etc.) exist.
  - A monster is processed that would required creation of a compendium folder.

The entire import process will fail with a "document is undefined" error in the browser console.

Inspection reveals that the missing compendium folder is created, and retrying the import will process the monster successfully (unless, of course, the import process encounters the above conditions again).

This occurred with approx. version 2.6.26, with other modules enabled, however I will be re-testing later will all other modules disabled and on the latest version (2.71).

**Comment by MrPrimate** [comment]
99% sure this is fixed now.
