### ISSUE TITLE
Error updating spell slots

### ISSUE THREAD

**Issue by crimsonknave** [MrPrimate/ddb-importer#191]
When I try to `Update D&DBeyond` on a character that has cast spells I get an error. In the console I see a CORS error and a 404 for the , which I think is actually the 404 being the issue and the proxy doesn't have the CORS headers on a 404. I'm running my own proxy if that matters.

Specifically, `https://[my-proxy-url]/proxy/update/spells/slots` gives the 404. I don't see that url anywhere in the the ddb-proxy code, it looks like there is a `/proxy/class/spells` endpoint though.

![image](https://user-images.githubusercontent.com/352979/146105622-533b97c8-d753-4b14-87e7-56155a5a1307.png)

**Comment by MrPrimate** [comment]
The ddb-proxy does not have the update to DDB feature implemented right now

**Comment by crimsonknave** [comment]
Just noticed I see the same thing when I add an item to a character's inventory and try to update.

**Comment by crimsonknave** [comment]
Ah, ok. So, it only works with your proxy right now? Do you plan on making that available via `ddb-proxy`?

**Comment by MrPrimate** [comment]
At some point
