### ISSUE TITLE
Bardic Inspiration

### ISSUE THREAD

**Issue by pwim** [MrPrimate/ddb-importer#192]
When importing Bardic Inspiration, the damage formula is set to `1d6`. This means when my bard targets another player they want to give Bardic Inspiration to, it damages them (due to my automation through Midi QOL). Regardless, as the inspiration dice is rolled by the player when they use the inspiration, I think the damage should be removed.

**Comment by MrPrimate** [comment]
I'm not going to change this as it seems dependant on your modules and how you play in Foundry. However, as a workaround, I suggest you change the bardic inspiration feature to your desired config and then click the D&D Beyond logo in the title bar and "Ignore this item when importing character" which will keep it the same going forward.

**Comment by pwim** [comment]
Understood. Thanks for the *inspiration* for a workaround!

**Comment by MrPrimate** [comment]
I revisited this and if you're using midi-qol bardic inspiration should now get set up properly for you

**Comment by pwim** [comment]
That's awesome! I tried it out and it's so much nicer than what I was proposing. My players are going to love it! 😎
