### ISSUE TITLE
Spirit Bard's Tales gets imported incorrectly

### ISSUE THREAD

**Issue by AquaZera** [MrPrimate/ddb-importer#194]
For the College of Spirits Bard their Tales from Beyond table is always imported incorrectly with the eighth tale, Tale of the Phantom, being shortened massively.

**Comment by MrPrimate** [comment]
Is this via a character or class munch, and is this the table in the description or the Foundry RollTable?

**Comment by AquaZera** [comment]
A character Munch. The Table in the Description. Instead of it saying **"Tale of the Phantom. The target becomes invisible until the end of its next turn or until it hits a creature with an attack. If the target hits a creature with an attack during this invisibility, the creature it hits takes necrotic damage equal to a roll of your Bardic Inspiration die and is frightened of the target until the end of the frightened creature’s next turn."** It says **"Tale of the Phantom. The target becomes frightened creature’s next turn."**

**Comment by MrPrimate** [comment]
@AquaZera perfect, thanks - this is a great bug that only pops up when the condition is mentioned twice in the same text paragraph - very unusual but surprised it's not come up before - I'll get a fix out this evening UK time.

**Comment by MrPrimate** [comment]
Fixed in latest release
