### ISSUE TITLE
Reaction spells don't list what you are reacting to when you cast the spell

### ISSUE THREAD

**Issue by crimsonknave** [MrPrimate/ddb-importer#195]
Soul Cage (https://www.dndbeyond.com/spells/soul-cage) when imported does not have the note about when it's used as a reaction. In dndbeyond there is an asterisk after the reaction, in the printed book it's just `Casting Time: 1 Reaction which you take...`. However, the imported spell has no asterisk (which makes sense it would probably break the filtering of reaction group), but the spell body says nothing about what you are reacting to. https://www.dndbeyond.com/spells/hellish-rebuke has the same issue, but less so as the text at least talks about `the creature that damage you`.

It would be great to prepend something like `1 Reaction which you take [insert asterisk text here]` as the first line of the spell description.

**Comment by MrPrimate** [comment]
I will add this to the activation condition field, which is where I think it should go, and it should then show up in spell cards in chat etc.

**Comment by MrPrimate** [comment]
Added
