### ISSUE TITLE
Skill Expert causes import error.

### ISSUE THREAD

**Issue by AquaZera** [MrPrimate/ddb-importer#196]
One of my players has the Skill Expert feat and chose Sleight of hand for proficiency and then chose it again for expertise. This causes them to get the error, Error: The _id[qJeYdcrZttx1BqZS] already exists within Actor [ddmRTgKRQRWiXbyf] items. I isolated it to the fact that because there is two Skill Expert: Sleight of Hand features being imported it breaks.

**Comment by MrPrimate** [comment]
Can I get a character URL?

**Comment by AquaZera** [comment]
https://ddb.ac/characters/58540710/YUNg49

**Comment by MrPrimate** [comment]
Sorry it took a few days to fix this one, was a knotty problem. Fixed in v0.8.2.
