### ISSUE TITLE
Monster Muncher randomly failing

### ISSUE THREAD

**Issue by ravingdragoon** [MrPrimate/ddb-importer#197]
I have tried a few times, and I keep getting the following errors somewhere between 100 and 300 imports.

```
logger.js:62 
DDB Importer | ERR > TypeError: Cannot read properties of undefined (reading 'createEmbeddedDocuments')
log @ logger.js:62
```
```
logger.js:62 
DDB Importer | ERR > TypeError: Cannot read properties of undefined (reading 'createEmbeddedDocuments')
    at addNPCToCompendium (https://assets.forge-vtt.com/bazaar/modules/ddb-importer/2.8.1/dist/main.js:8354:27)
    at async parseNPC (https://assets.forge-vtt.com/bazaar/modules/ddb-importer/2.8.1/dist/main.js:8678:3)
log @ logger.js:62
```

**Comment by MrPrimate** [comment]
Try disabling Monk's Enhanced journal if you have it installed. There is a bug with the current release that over rides the Compendium import method and breaks the importer. You can re-enable it after import

**Comment by MrPrimate** [comment]
https://github.com/ironmonk88/monks-enhanced-journal/issues/168 is upstream issue
