### ISSUE TITLE
Error parsing Character: You do not have permission to browse the host file system!

### ISSUE THREAD

**Issue by giantryansaul** [MrPrimate/ddb-importer#198]
Getting an error when importing sheets as a player user. The error on the import matches that in the Console. Player stats get set to level 0.

![2022-01-11 17_58_32-Worldbuilders • Foundry Virtual Tabletop and 14 more pages - Personal - Microsof](https://user-images.githubusercontent.com/353566/149050668-28ffc875-c04e-4d9d-b626-864326cb4813.png)

This error only began after I updated both Foundry and the ddb-importer.

foundry: 9.24
ddb-importer: 2.7.7

If I run the same import as a DM user however, it succeeds, and the character's level is restored.

I double-checked that all needed folders exist on my server and are owned by the running process, so I don't think this is a file system error.

**Comment by MrPrimate** [comment]
This is a permissions error for the users - check that the role permissions the user has - are they able to browse/upload data?

**Comment by giantryansaul** [comment]
That fixed it, thank you! 

For whatever reason when I updated foundry it dropped our saved settings in a lot of places, including modules. I forgot that I had set that setting awhile back when we set the server up.
