### ISSUE TITLE
Importer overwrites local modifications

### ISSUE THREAD

**Issue by odcinek** [MrPrimate/ddb-importer#2]
Even with "Import new items only" option enabled, modifications made in Foundry get overwritten. Tested with both spells and weapons, Foundry 0.7.5 and ddb-importer 0.0.6

Thanks,

**Comment by MrPrimate** [comment]
Thanks for the report @odcinek 
- is this via the character import option?
- what is the extension setting "Compendium import policy)" set to?

**Comment by odcinek** [comment]
All extension settings are on defaults, "Compendium import policy" is set to "Save new entities only, do not overwrite existing ones".

![image](https://user-images.githubusercontent.com/217108/98220337-feca5280-1f02-11eb-8528-446a40c6cc74.png)

First item marked in red (which got modified in foundry) gets it's name updated to ddb original. The second one, which does not exist in ddb, gets deleted.

**Comment by odcinek** [comment]
fwiw I do have vtta-dndbeyond installed too, if that makes any difference.

**Comment by MrPrimate** [comment]
Fixed!
