### ISSUE TITLE
Error Cannot Read Property 'name' of undefined

### ISSUE THREAD

**Issue by WomenlyProducts** [MrPrimate/ddb-importer#20]
![image](https://user-images.githubusercontent.com/74851932/99897610-07869b00-2cef-11eb-9182-95d7b4c22b7b.png)

I get this error when trying to import this Character. No idea why. I was able to import a level 5 paladin just fine
https://www.dndbeyond.com/profile/WomenlyProducts/characters/39674592

**Comment by MrPrimate** [comment]
What version of the importer are you using?

**Comment by WomenlyProducts** [comment]
Omg I was a version behind. Sorry I updated and its all working now. Sorry
