### ISSUE TITLE
Suggestion: Possibility to draw from a custom set source compendium for spells, items and features etc on import.

### ISSUE THREAD

**Issue by SirAron111** [MrPrimate/ddb-importer#200]
Suggestion: Possibility to draw from a custom set source compendium for spells, items and features etc on import.
I know it would add to the time it takes to  import a char, but i think it would be great if there was an option to set additional compendiums other than the SRD ones that the importer looks through when adding features. For example, i have Homebrew spells that the importer doesn't properly set when importing them and not even gives them a picture other than the standard spell school picture. If I was able to say, "hey look into this compendium where I have all these things set up and named appropriately, just use this before attempting to create a new one"
something like this
Set additional Spell directory for spell imports: (Custom Spells)
Set Additional Item directory for item imports (Custom Items)
Set additional race directory ....
And so on, I don't know if it's possible, but for example i made a custom class that contains the full blood hunter and artificer stuff as well as some custom races etc and i was thinking wouldn't it be easier for the importer to just add them from a compendium that already exists instead of attempting to convert them from scratch...I don't know the technicalities that would involve, so if it's impossible, I will stick to fixing everything that needs fixing manually.

**Comment by MrPrimate** [comment]
You can already do this - the importer creates an "Override" compendium that you can add item/spells/features to. You can change this to a new compendium in the settings if you need to. When you import a character, on the Advanced tab, tick the "Use Override compendium" option. it will replace any items that match the name and type from the override.
