### ISSUE TITLE
D&D Beyond Importer Issue: Error parsing character: cannot read properties of undefined (reading 'conditions')

### ISSUE THREAD

**Issue by Squidrobe** [MrPrimate/ddb-importer#204]
I get this error when I try to import a character, not sure what I'm doing wrong...

Error parsing character: cannot read properties of undefined (reading 'conditions')

**Comment by gtg922r** [comment]
Same error on a fresh install. Cobolt cookie added fwiw

**Comment by MrPrimate** [comment]
Working on a fix, but a work around is to connect via the browser for now

**Comment by MrPrimate** [comment]
Fixed in v2.8.12
