### ISSUE TITLE
Issue with Healing Word's Healing Formula

### ISSUE THREAD

**Issue by pwim** [MrPrimate/ddb-importer#205]
This isn't necessarily a bug on your end, but I noticed that Healing Word now has a Healing Formula of `1d4[healing - Unaffected: constructs, undead] + @mod` whereas Cure Wounds has a Healing Formula of `1d8[healing] + @mod`. The difference between these two seem to be coming from D&D Beyond, as they have the restriction only indicated on Healing Word.

This breaks my automation with midi-qol. Perhaps this is where it should be fixed, though I'm not aware of if there's any "protocol" around tagging healing rolls like this.

**Comment by MrPrimate** [comment]
You can turn off this feature in the core settings -> Module Settings -> DDB Importer -> Add restrictions to damage hints?
