### ISSUE TITLE
Number of preparable Spells not imported correctly for Artificer

### ISSUE THREAD

**Issue by eccobold** [MrPrimate/ddb-importer#206]
Hi, whenever I import an Artificer, his preparable spells are set to 0. The number of prepared spells is correct. It will be overridden although Spells, Classes and Features are disabled in the Import.

![image](https://user-images.githubusercontent.com/71939920/151535609-ecfa4cb2-95b1-48a2-9d15-66d5c74cfef9.png)

**Comment by eccobold** [comment]
maybe this helps: for Artificers dndbeyond gives "spellPrepareType === 2" which will be skipped in your maxPreparedSpells method.

**Comment by MrPrimate** [comment]
This is fixed in the next (2.8.16) version, thanks for the report and useful info.
