### ISSUE TITLE
BUG: Monster abilities with recharge have incorrect setting--can cause issues

### ISSUE THREAD

**Issue by SwordofSpirit** [MrPrimate/ddb-importer#209]
Some monsters with abilities that recharge (might be all of them, but I know it's on dragon breath attacks) have the Resource Consumption set to "Item Usage" as well as having the recharge set.

Normally this doesn't cause a problem, but with the Better Rolls module it does. When you use the feature it gives the message: "The designated Item Use source that [Element] Breath (Recharge 5-6) consumes no longer exists!" and fails to function.

Since the SRD versions of the dragons don't have Item Usage set (and don't cause errors), and since I tried it on a fresh world without modules, I can only assume the muncher somehow introduces this bug.

Thanks for your time.

**Comment by MrPrimate** [comment]
This will be fixed in the next release.
