### ISSUE TITLE
Non-magical items are listed as "Common" in the magic item categories

### ISSUE THREAD

**Issue by SwordofSpirit** [MrPrimate/ddb-importer#211]
I know the SRD (for some unfathomable reason) does that with their listings, but just thought I'd put in vote to take it out on import, since it's not true to the game's conventions. Non-magical items don't have a magic item rarity.

To clarify, I'm speaking about the listing on the item sheet itself. You can manually select an item and set that field to blank, but I'd rather it already be blank than have to go through so many items one by one.

**Comment by MrPrimate** [comment]
This will be in 2.8.27
