### ISSUE TITLE
I can't download spells

### ISSUE THREAD

**Issue by jofrepouplana** [MrPrimate/ddb-importer#212]
I have teh cobalt Cookie ok, but I can't import spells. I've buy it in d&d beyond and I want to import it in Foundry but once I click Spell Munch it begins but never ends. I tryed several times. It only says:
Downloading Spells...
Parsing Spell Data..

And I can wait for an hour but nothing, the new spells doesn´t appear.

What it can be? Maybe that I'm using the babel spanish traduction module?

I'm doing all well acording to the tutorial videos...

Thanks

**Comment by MrPrimate** [comment]
This maybe easier to fix over on the discord. I need some more information:

* Version of Foundry
* Version of D&D5e
* Version of DDB Importer
* Have you tried with all other modules disabled? (If not, please do this)
* Open the browser dev console (F!") and see if any errors appear during import.
