### ISSUE TITLE
Importer fails to correctly import the racial ability score increase of Homebrew races in certain cases.

### ISSUE THREAD

**Issue by SirAron111** [MrPrimate/ddb-importer#213]
I have noticed that even if they are correctly phrased, the importer doesn't import the racial ability score increase from some Homebrew races. It consistently happens with races that have it stated like this.
"Four different ability scores of your choice increase by 1."
or "Two different ability scores of your choice increase by 2."
which is used in 3 different Homebrew races my players frequently use, which don't gain many racial abilities but have the 1 more ability score point increase like stated above instead of the standard 2/1 score most other races get. They are more like the standard human, which gets +1 to all but doesn't have many features to its base race.

Is it possible to fix this, or is this too much of a niche case to bother?

**Comment by MrPrimate** [comment]
Can you provide a link to a character with an example homebrew race that is failing - it should be parsing this based on the config of the feature, not the text that is written.

**Comment by MrPrimate** [comment]
Thanks, I'll have a fix in v2.8.28, out sometime in the next 24 hours.
