### ISSUE TITLE
Feature Request: Disable "Update" Toast

### ISSUE THREAD

**Issue by rcebulko** [MrPrimate/ddb-importer#214]
Love this extension, but hate that I get this every single time I open Foundry:
![screenshot 55](https://user-images.githubusercontent.com/6694512/154573109-a04e9416-febe-411c-937a-b62f27715792.jpg)

I actually did update yesterday, entirely because this was bothering me, only to find that an even newer release dropped a few hours later. Looking at your commit log, it seems like updates are fairly frequent (which is great!).

Feature request would be either
1. Add a setting to disable the update toast entirely
2. Provide a "Don't show this again" or "Don't show this for 30 days" option
3. Display the toast as part of existing module flows; ex. if I start to Monster Munch, it would make sense to nudge me to update the module, however 95% of the times I log into Foundry, I'm not importing anything directly as I've already imported all spells/monsters etc. (Yes, I could just disable/enable the entire module, but that's more heavyweight than ideal)
4. At most show the toast once per release, but remember that the toast has been seen and dismissed.

**Comment by MrPrimate** [comment]
1. There is a "secret" setting that I can let you know, if you promise to always update before logging bugs. Open the console (F12) and run: `game.settings.set("ddb-importer", "update-check", false)`;

**Comment by rcebulko** [comment]
Much obliged good sir! Thanks for all you do and keep up the great work

**Comment by jbhaywood** [comment]
I was just going to add this same request. No other module that I use tells me to update inside my game, and I could imagine how annoying it would be if more of them did. It wouldn't even be so bad if the module wasn't updated so often (which is fine, I'm glad it's actively maintained), but there's a reason I don't always update and I don't want to have to add an extra mouse click every time I run a game.

**Comment by MrPrimate** [comment]
I'll work on improving the options for this in the near future!

**Comment by MrPrimate** [comment]
Setting wil be in module settings in v2.9.52
