### ISSUE TITLE
Monster Features/Attacks: `The ${monsterName} uses ${featureName}!`

### ISSUE THREAD

**Issue by rcebulko** [MrPrimate/ddb-importer#215]
I assume this is the result of some permutation of settings on my part, but here's what I'm getting in a monster's sheet:
![image](https://user-images.githubusercontent.com/6694512/154761205-4cb099e7-786b-48b2-ba9d-34f9ea881c03.png)

The **Description** tab of the item always says roughly that, ex. "The Specter uses Incorporeal Movement!" rather than the description text present in the DDB stat block.

## Muncher settings:
![image](https://user-images.githubusercontent.com/6694512/154761718-6cf098f3-25bb-46b2-bf9a-4572e4ce94b9.png)

![image](https://user-images.githubusercontent.com/6694512/154761770-a8f6c24e-7526-4377-8b84-197e5cec3898.png)

Note that I imported this batch a couple weeks ago, so my apologies if this is already resolved, but I didn't want to run a whole re-munch without knowing what was wrong.

**Comment by MrPrimate** [comment]
This is what the "Hide monster action description from players" option does, it hides the action description in chat, but still shows it on the sheet.

**Comment by rcebulko** [comment]
> This is what the "Hide monster action description from players" option does, it hides the action description in chat, but still shows it on the sheet.

Unless I'm missing something major, it doesn't still show it on the sheet at all. As shown in the screenshot above, the sheet (including the **Description** tab if I _Right Click > Edit Item_) only includes that as a description and never any of the actual descriptive text.

**Comment by MrPrimate** [comment]
Looks like something went wrong during the import, it should look like this:
![gobo](https://user-images.githubusercontent.com/3985378/155192412-6dbf2388-f8ff-43ce-a648-bf3628c225e7.png)
And if you edit the source like so:
![gobo-source](https://user-images.githubusercontent.com/3985378/155192409-b4b13b52-55a5-4373-9302-7f9491c73dd7.png)

**Comment by rcebulko** [comment]
I will re-run the import I guess. Is it possible that "Copy effects from DAE" or "Use Dynamic Active Effects Compendium" settings could be causing this somehow?

**Comment by MrPrimate** [comment]
They shouldn't be - might also be another module interfering.
