### ISSUE TITLE
Messed up links

### ISSUE THREAD

**Issue by SwordofSpirit** [MrPrimate/ddb-importer#218]
I just did a new import (fresh world) version 2.9.6, and I'm getting some weird links inside some of the items.

As an example, the editable text in Ring of Invisibility is:

"While wearing this ring, you can turn @Compendium[dnd5e.rules.@Compendium[dnd5e.rules.Invisible]{Invisible}]{@Compendium[dnd5e.rules.Invisible]{invisible}} as an action. Anything you are wearing or carrying is @Compendium[dnd5e.rules.@Compendium[dnd5e.rules.Invisible]{Invisible}]{@Compendium[dnd5e.rules.Invisible]{invisible}} with you. You remain @Compendium[dnd5e.rules.@Compendium[dnd5e.rules.Invisible]{Invisible}]{@Compendium[dnd5e.rules.Invisible]{invisible}} until the ring is removed, until you attack or cast a spell, or until you use a bonus action to become visible again."

As you can imagine, the duplicated "@Compendium" portions make it look like a complete mess. There are many of these in various elements of content. I wasn't experiencing this on an import a few versions ago, so I'm assuming it's a new issue.

**Comment by MrPrimate** [comment]
Ah! I'll have this fixed in the next release tomorrow
