### ISSUE TITLE
DAE: Unarmored defence monk/barbarian

### ISSUE THREAD

**Issue by DeadlyArtist** [MrPrimate/ddb-importer#22]
1. Import custom proficiencies
2. Map unarmored defense to "Unarmored Defense (Monk)" and "Unarmored Defense (Barbarian)" respectively. (Cuz theyre called that in dae srd and i assume you add them by name)

**Comment by MrPrimate** [comment]
1. Custom proficiency should be imported already - it could be that the json or foundry has changed the way these are handled. I will investigate.

2. This might be a better issue for DAE - I call the provided DAE function, maybe it could check to see what classes a character has?
I also may end up doing this as part of the feature import, but I'm not sure if people will want the features with class names appended. It might be possible to do this just for the DAE  mapping based imports.

**Comment by phildias** [comment]
I came here to post about the issue regarding the monk's "Unarmored Defense" feature too. The importer does not automatically map the imported feature from DnD Beyond to the DAE feature.

**Comment by MrPrimate** [comment]
v 4.0.0 of the DAE SRD compendium should resolve this.
