### ISSUE TITLE
Error when importing character: TypeError: Cannot read property of undefined (reading '0')

### ISSUE THREAD

**Issue by aceradryd** [MrPrimate/ddb-importer#222]
Hello,

thank you for your tool!
I was able to import all characters except the following. With this one I get the error "TypeError: Cannot read property of undefined (reading '0')".

As far as I understand the error message in the console, this has to do with the fact that the character is a druid (Circle of Stars).

Charaktersheet: https://www.dndbeyond.com/characters/44035154

**Comment by MrPrimate** [comment]
Whoops! This is fixed in v2.9.20, releasing now!
