### ISSUE TITLE
Sleep is currently a damage spell

### ISSUE THREAD

**Issue by dhorkin** [MrPrimate/ddb-importer#223]
I noticed in the patch notes that Precision Attack was recently changed to No Damage, so I thought I would call out that the Sleep spell is currently generated in such a way that it does damage if you're using Midi-QOL/automation modules.

I was able to fix this by opening up the spell and changing the damage type to No Damage. It still rolls the dice like it's supposed to and everything is working now, but it would be nice for other people for this to be the default behavior

**Comment by MrPrimate** [comment]
Thanks for the report. This is on my list to add an active effect to soon, so I will make the change at that point, sometime before the weekend hopefully!

**Comment by MrPrimate** [comment]
This + sleep macro effect will be in v 2.9.21
