### ISSUE TITLE
Error parsing Character: TypeError: Cannot read properties of undefined (reading 'proficiencyGroups')

### ISSUE THREAD

**Issue by JIVIV** [MrPrimate/ddb-importer#225]
![image](https://user-images.githubusercontent.com/47309633/160691243-8c9bff9a-b06a-4f7e-afe3-4c217272dd2d.png)

I have been using the tool as I always do and this issue arose today. I'm not sure what changes may have caused it. I checked for an update to the module and i updated my game system.

**Comment by MrPrimate** [comment]
Changes at DDB have caused this - it seems to only fail in Foundry Client, so you can try connecting with a browser instead. The version 2.9.22 should tru and fix this.

**Comment by SirAron111** [comment]
Got the same error today when attempting to update my players chars. With version 2.9.22

**Comment by MrPrimate** [comment]
This should now be fixed.
