### ISSUE TITLE
Error parsing Character: TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by sunyatacyte** [MrPrimate/ddb-importer#23]
Hi,

Thanks heaps for your importer, it works for all of the characters I'm importing at the moment except for one, which gives me this error: Cannot read property 'name' of undefined. Do you know what this might be referring to? I tried adding the cobalt cookie but that didn't help.

This is the character: https://www.dndbeyond.com/characters/38255200

**Comment by MrPrimate** [comment]
Hi, can you make sure your using the latest version of the importer 0.0.22 - there was a bug in the earlier versions which meant the upgrade button didn't work correctly so you may need to uninstall and reinstall it.

**Comment by sunyatacyte** [comment]
Thank you, sir! That was indeed the exact nature of the problem. My gratitude 😄
