### ISSUE TITLE
Error importing characters with customized spell names

### ISSUE THREAD

**Issue by jaronkk** [MrPrimate/ddb-importer#231]
This was tested with an Artificer and Cleric, and I assume it affects any character that has a list of prepared and unprepared spells (e.g. druid, paladin, wizard).

Simple reproduction steps: 
1) Create a 1st level cleric in dndbeyond
2) Prepare the `Bless` spell.
3) Customize the `Bless` spell's name e.g. `I can't believe it's not bless` (specific name doesn't matter) 
![image](https://user-images.githubusercontent.com/127832/165990032-d0a80dc7-880b-4e88-957c-402ac5acc464.png)

4) Import the character into Foundry.
5) Check the character's spell list. There will be two versions of the customized spell. One of the spells will be prepared, the other will not.  
![image](https://user-images.githubusercontent.com/127832/165989953-ddc8189b-e08b-4faf-9503-376e9de0a9c2.png)
6) Import the character one more time and you will receive an error: `Error parsing Character: Error: The _id [SOMEID] already exists within Actor [ACTORID] items`  
![image](https://user-images.githubusercontent.com/127832/165990236-7e663999-3fe5-4d4d-b30d-ee2b1acbcd1b.png)

We have a workaround for right now where the player with the issue just doesn't keep any spells prepared in dndbeyond so the customized spells aren't added twice. My assumption is that it's adding the spell to the list once from the prepared spell list and again from the full spell list.

**Comment by MrPrimate** [comment]
Hmm, very odd - this doesn't happen with Casters like Wizards, so I suspect it is something to do with the way duplicate spells are added to the meta data for classes like Cleric. I have added a fix for release v 2.9.34
