### ISSUE TITLE
Import Character feature imports all known spells

### ISSUE THREAD

**Issue by bailboy101** [MrPrimate/ddb-importer#236]
Recently when I update character sheets their spell list has all known spells instead of all prepared spells. I tried deleting the non known ones and uploading the foundry sheet to d&d beyond and then reupdating on foundry but the same thing happens

**Comment by MrPrimate** [comment]
This is the desired/expected behaviour - if the cobalt cookie is not set it will only import prepared spells.

Is this causing an issue? WOuld you like an option to not import known spells?

**Comment by bailboy101** [comment]
I see what the intent was now. I missed the icon on the right that marks them as prepared or not. Thank you
