### ISSUE TITLE
Issue with importing 

### ISSUE THREAD

**Issue by DarkPhonix5097** [MrPrimate/ddb-importer#238]
When I try to import a char this massage appears
![image](https://user-images.githubusercontent.com/48560216/170339495-4dd6a941-8685-499a-8412-d0ae7681cad0.png)

**Comment by MrPrimate** [comment]
What version of:
- Foundry
- 5e
- DDB Importer

are you using, and please provide a character url

**Comment by DarkPhonix5097** [comment]
![image](https://user-images.githubusercontent.com/48560216/170555663-35f8550d-f987-46ba-96ba-b4ce793af87d.png)

https://www.dndbeyond.com/characters/74619425

thanks

**Comment by DarkPhonix5097** [comment]
yes it works now (-: Thanks
