### ISSUE TITLE
Feature Request : Allow filter "Legacy" content on Races too

### ISSUE THREAD

**Issue by MiahNelah** [MrPrimate/ddb-importer#241]
I noticed ddb-importer do import Legacy content witch Race Muncher :
![image](https://user-images.githubusercontent.com/1334405/172171455-aeb79910-c94c-4cdc-b624-eb6352bd7ef8.png)

Is it possible to get a filter on race import too ?
Even better, I would love to filter on non-Legacy content in all importers.

**Comment by MrPrimate** [comment]
Implemented
