### ISSUE TITLE
Suggestion: Add an option to leave the 'Chat Message Flavor' field empty during weapon item imports.

### ISSUE THREAD

**Issue by Ben-ODea** [MrPrimate/ddb-importer#249]
Hi, love the module and appreciate the work you do on it.

When items are imported, they're imported with flavour text. The content seems to default to 'other damage:' for most weapons. See below.

![flavour-1](https://user-images.githubusercontent.com/89972605/179384928-406565d6-54a6-4dbc-bf40-6aea8e2dcf75.png)

This flavour text shows up in the chat card when the item is used. This is obviously compounded when monster muncher is set to equip items from the DDB compendium rather than parsing attacks where possible. See below.

![flavour-2](https://user-images.githubusercontent.com/89972605/179385019-a54feee8-a242-4895-ac93-54bfe4a40f6b.png)

Note that my chat cards in the screenshot are impacted by a couple modules including DF Chat Enhancements and MidiQoL, however the flavour text also displays on vanilla Foundry. There are no options in any modules I could find to prevent it from displaying. Obviously, this flavour text does not make a great deal of sense or add anything to the chat card.

I was wondering if it would be possible to stop this field from populating during item import in cases where there's nothing significant to write (i.e. weapons). An alternate option might be to insert flavour text like '\<Actor\> uses \<weapon\>', similar to how the feature imports are managed. 

Thanks!

**Comment by MrPrimate** [comment]
Ah, this shouldn't be happening - I tweaked some stuff here recently - I'll take a look and see what's going on.

**Comment by MrPrimate** [comment]
This will be fixed in v2.9.58
