### ISSUE TITLE
Shared Content Not Importing Properly

### ISSUE THREAD

**Issue by insquared** [MrPrimate/ddb-importer#25]
I included the shared content ID from the campaign link in the settings, does not seem to be importing some spells from xgte, tcoe, phb and etc.

**Comment by MrPrimate** [comment]
It will cache your requests for a bit, so please try again and let me know. If your still having problems please reach out to me on discord for some troubleshooting

**Comment by insquared** [comment]
> It will cache your requests for a bit, so please try again and let me know. If your still having problems please reach out to me on discord for some troubleshooting

It seems that was the issue, I will keep that in mind in the future, to wait for the cache to clear for a bit. :)
