### ISSUE TITLE
Manifest File is missing or unreadable

### ISSUE THREAD

**Issue by RufousBartleby** [MrPrimate/ddb-importer#255]
Hi I have tried loading the extension into chrome, but it states th manifest file is missing or unreadable?!

[image](https://user-images.githubusercontent.com/110336702/182025840-c8648ebe-5026-430e-a31f-6967d7f11674.png)

**Comment by MrPrimate** [comment]
It looks like you're trying to use the ddb-importer module for Foundry, rather than the chrome extension, here: https://github.com/MrPrimate/ddb-importer-chrome

**Comment by MrPrimate** [comment]
No response, closing.
