### ISSUE TITLE
unable to import character

### ISSUE THREAD

**Issue by MrSquiggz** [MrPrimate/ddb-importer#256]
I have been able to import 5 of the 6 characters, now that I am trying to re-import them in only one is giving me a problem no matter the world I use (foundryserver.com)
I have had no issues with this character in the past- every other parses over easily and I am unsure what the undefined element would be

I continue to get the error:
Error Processing character: typeError: Cannot read properties of undefined (reading '0')

**Comment by MrPrimate** [comment]
* Foundry Version?
* D&D 5e module version?
* DDB Importer version?
* Have you tried with other modules disabled? (If not, please try disabling them - the "Find the culprit" module can help turn these on and off for you)
* A character URL please!

**Comment by sjc625** [comment]
Foundry 9.269
5e 1.6.1
DDB Importer2.9.4.6
Not yet - not my server, but a list of other active modules:
- DDB Gamelog
- libWrapper
- PnP - Pointer and Pings!
- Polyglot
- Simple Dice Roller
- Universal Battlemap Importer
- Zoom/Pan Options

https://www.dndbeyond.com/characters/77718611

**Comment by MrPrimate** [comment]
@sjc625 Please try updating DDB Importer and the 5e system version.

**Comment by MrPrimate** [comment]
No response, closing.
