### ISSUE TITLE
Unable to import "Unarmed Strikes"

### ISSUE THREAD

**Issue by eBAHN** [MrPrimate/ddb-importer#257]
On importing characters from DDB, the "Unarmed Strike" action would not import into new Foundry player character sheets. The "Unarmed Strike" *bonus action* would, however. In addition, I have previously existing character sheets with Unarmed Strike, which would then disappear if I re-imported these PCs from DDB.

This change appears to be relatively recent. Everything else (weapons, equipment, other inventory items) appear to import as normal. I disabled all modules except for DDB-importer but the issue persists.

Foundry Version: v9 Build 269
D&D 5e module version: 1.5.7
DDB Importer version: 2.9.62

**Comment by MrPrimate** [comment]
Do you have a character link? I did recently add a feature that respected the DDB option to not show/generate unarmed strike action.

**Comment by eBAHN** [comment]
Here is one example:

https://www.dndbeyond.com/characters/77818675

This one is a monk and would have unarmed strike as an action and bonus action. Foundry imports the bonus action but not the action.

**Comment by MrPrimate** [comment]
Ah it looks like DDB have removed the option to hide Unarmed Strike from the sheet, and this option is now always `true`. I'll push an update.

**Comment by MrPrimate** [comment]
Fixed in 2.9.63
