### ISSUE TITLE
Migrate Item Compendium, Compendium Folders, Vehicles/Mounts cause exceptions and are not put into folders

### ISSUE THREAD

**Issue by watermelonwolverine** [MrPrimate/ddb-importer#259]
Steps to reproduce:
- Munch items without compendium folders module enabled
- Enable compendium folders module
- Open Muncher > Tools > Migrate Item Compendium with `Item Type` selected

Result:
- Mounts/Vehicles like Camel or Carriage aren't categorized
- 19 exceptions in console:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
[Detected 1 package: ddb-importer]
    at getItemCompendiumFolderNameForType (compendiumFolders.js:421:1)
    at getItemCompendiumFolderName (compendiumFolders.js:455:1)
    at getCompendiumFolderName (compendiumFolders.js:519:1)
    at addToCompendiumFolder (compendiumFolders.js:543:1)
    at async compendiumFolders.js:623:1
```

Expected result:
- No Exceptions in console
- All items in folder

**Comment by watermelonwolverine** [comment]
Debug Report:
[debug-report.txt](https://github.com/MrPrimate/ddb-importer/files/9382622/debug-report.txt)

**Comment by MrPrimate** [comment]
THis should be resolved in the latest versions.
