### ISSUE TITLE
@Compendium[dnd5e.rules<ability>] now missing after fresh import

### ISSUE THREAD

**Issue by bobby-driggs** [MrPrimate/ddb-importer#261]
Hey, not sure if this is a bug with the importer or just a DnD Beyond or Foundry v10 changes.

After upgrading to Foundry VTT v10 last night, I decided to do a fresh pull of all the content on DndBeyond I have, as I assumed there would probably be some formatting changes, etc, and my Campaign isnt starting for a few weeks yet.

One thing I noticed after successfully importing everything, is that the DDB * Compendium packs that were generated, are now missing Compendium references to the baked in `dnd5e` rule compendium.

Here is a diff of the two packs, left is new, right is a backup a took. I sorted lines alphabetically in Notepad++ to attempt a decent diff.

This is just comparing the two "Feat" packs, but I did a search in VS Code, and `@Compendium[dnd5e` is not found at all in the new packs.

Is this desired behavior? Its not a big deal, but figured if it was a regression issue, may be nice to fix.

<img width="1547" alt="image" src="https://user-images.githubusercontent.com/9810149/187977635-4105c6de-1c1d-484a-9c94-21ff288ce683.png">

Let me know if you need any details. This was on a fresh v3.0.0 of the importer, and V10 of Foundry, and a reinstall of the dnd5e system

**Comment by MrPrimate** [comment]
There is a small issue in the v10 version of DDB Importer where links to the SRD items are not working. This is due to a change in how the SRD content is structured (it's much better) but has broken the auto link detection. The downside is it's going to require a bit or work and thought to get working again.

**Comment by MrPrimate** [comment]
A partial fix is in v3.0.3. Adventure Muncher still needs some work.

**Comment by bobby-driggs** [comment]
Updated to 3.0.4 this morning, and confirmed @Compendium[dnd5e.rules*] is back! I dont use the Adventure Muncher, so didnt test that! 

Thanks!
