### ISSUE TITLE
Foundry VTT v10 importer issues

### ISSUE THREAD

**Issue by edyragon** [MrPrimate/ddb-importer#263]
Having some issues importing with Foundry's new v10 stable. Spells and Items Compendiums are munching as normal, but Monsters Compendiums are getting held up and never completing. I've tried to run it a few times, but it keeps getting stuck without making any progress. I left my server running all night with the Monster Munch going, but it appears still stuck without completing. 

Also, I can't import new characters or re-import older characters as actors. I'll get the prompt to accept the import, but it stays stuck on "uploading avatar" and never actually pulls features, inventory, etc. 

I've been using ddb-importer as a patreon supporter for over half a year, so I know I have the set-up correct. I checked cobalt cookie and my patreon key, but they are both good. 

Is this just a bug with v10?

**Comment by MrPrimate** [comment]
Do you have webp conversion enabled in the settings? If so can you try disabling it.

**Comment by edyragon** [comment]
Not sure where that setting is located. Is that in the module configuration or muncher dialogue? 

Also, I updated the module this afternoon with the latest release, and the Monster Muncher is now working. The character importer seems to still be getting stuck.

**Comment by MrPrimate** [comment]
Hoping this is resolved with latest v10 and DDB Importer?

**Comment by MrPrimate** [comment]
Closing this as I believe it is fixed, please reopen if its not.
