### ISSUE TITLE
Character import fails when there's an avatar set on DnDBeyond.

### ISSUE THREAD

**Issue by FanaticPythoner** [MrPrimate/ddb-importer#265]
The import fails when importing a character if an avatar is set on DnDBeyond. Tried a bunch of different combination of options, still the same result. See before / after pictures. 2nd last image represents where the error occurs. Last image is the list of modules. Console log text: "DDB Importer | ERR > TypeError: Cannot read properties of undefined (reading 'src')". Foundry VTT version 10, build 284, DnD5e - Fifth Edition System version: 2.02.

![image](https://user-images.githubusercontent.com/45826736/188940904-d1f66591-81d6-419f-9d02-f902ce719e52.png)
![image](https://user-images.githubusercontent.com/45826736/188941053-36fe271d-f155-4eb2-b26e-359c52c87ede.png)
![image](https://user-images.githubusercontent.com/45826736/188941251-6e3aaf3a-656e-4bbd-a102-fc0c002c0d99.png)
![image](https://user-images.githubusercontent.com/45826736/188941833-94166551-61af-48fd-9a09-ab0b85cb9307.png)

**Comment by MrPrimate** [comment]
That actor imports fine here - I would suggest disabling other modules and trying again.

Also, did this actor get migrated from v9 or created a fresh in v10 (the code you like to by the way is core system stuff, not DDB Importer)

**Comment by FanaticPythoner** [comment]
The actor was freshly created in V10.

**Comment by FanaticPythoner** [comment]
I'll try disabling even more modules one by one and keep you up to date.

**Comment by FanaticPythoner** [comment]
No. I deactivated all modules except D&D Beyond importer and it has the same issue.

**Comment by FanaticPythoner** [comment]
Here's the character's link, if it helps: https://www.dndbeyond.com/characters/82677640

**Comment by FanaticPythoner** [comment]
And I know it's the avatar, because I just created a character without avatar and imported it without any issue. However, the moment I set the avatar, the import fails.

**Comment by MrPrimate** [comment]
It imports fine here. It looks like it must import correctly at least once, looking at the screen shot there. is this for an update, or on initial import?

And this definitely happens if:
- you disable other modules and create a new actor.
- import to that newly created actor

**Comment by edyragon** [comment]
I believe this user may be experiencing the same issue as I am. The import fails at the "downloading avatar" from DDB - https://github.com/MrPrimate/ddb-importer/issues/263#issue-1362203048.

**Comment by MrPrimate** [comment]
- Are you using Foundry Client/Chrome/Firefox etc?
- In Settings -> DDB Importer -> Directory Locations is "Convert images to webp?"  ticked?

Can you screen shot the settings on the Character Import screen for the "Import Character", "Active Effects" and "Advanced" please.

**Comment by MrPrimate** [comment]
I believe this maybe the same issue as #268

Please try:

Other users have reported success after running `game.dnd5e.migrations.migrateWorld()` in their world. It looks like this is the product of a bad migration after upgrading. 

Run this by opening the web console (F12) and entering the command.

**Comment by MrPrimate** [comment]
Please can you try updating to the latest version of Foundry v10, I believe this was a core bug that is now resolved.

**Comment by FanaticPythoner** [comment]
I will check it out later today and keep you in touch.
