### ISSUE TITLE
LMOP V10 import

### ISSUE THREAD

**Issue by llothos** [MrPrimate/ddb-importer#266]
Tried importing LMOP and it does import but there are quite a bit of links that are not working. For example, just in the table of contents, it doesn't show that you can click on it and it does show @journal..... links in the text but they aren't correct and don't go anywhere and even within the journal articles there will be some links that work and others that don't.

It seems to be links to other parts of the adventure that aren't working correctly. I downloaded the most recent version of the adventure muncher (as of yesterday) and updated foundry and modules to the latest as of today.

**Comment by MrPrimate** [comment]
What options did you have checked in Adventure Muncher when generating the adventure?

**Comment by MrPrimate** [comment]
Can you provide some screen shots too? Links to the rules Journals are currently broken, as per issue #261 But links in the adventure are working here for me when I use "Generate content for Foundry v10" and the two hand out options unchecked.

**Comment by llothos** [comment]
I look again and get some screenshots but I remember checking the box for V10 but I think the hand out options may have been checked. For me the issue was the links to other parts of the adventure wasn't working but a few of the rules ones were working that I had tried.

**Comment by llothos** [comment]
![LMOP TOC](https://user-images.githubusercontent.com/23327649/189269406-f7f127c7-cc63-446a-9e8a-4a935ac575ad.jpg)
![LMOP ex](https://user-images.githubusercontent.com/23327649/189269411-d543a591-639d-47eb-8dcc-3c915c3c6c7d.jpg)
Two screenshots of how it currently looks, I did generate a new file that doesn't have the player handouts checked but I haven't imported it yet as I wanted to get these screenshots. You can see the symbols look different and only say something about text page but I can't click that the other ones that reference back to SRD seem to take me there.
Here's what I had selected in the adventure muncher before but I will try it without the two handout options checked and report back once I've imported it.
![adventure munch](https://user-images.githubusercontent.com/23327649/189269758-e4182409-54e1-45de-8b4d-4d50ab418ae3.jpg)

**Comment by llothos** [comment]
ok even with those two options unchecked I get same result.

**Comment by llothos** [comment]
I created a new world, enabled the importer, generated a new config file and LMOP file and now the links work. 
The previous world I was trying on was one I was playing around with and was a V9 world that I migrated to V10 and that is the one that wasn't working. Weird...

**Comment by llothos** [comment]
did another test, disabled all modules on that other world except yours and the import worked fine. Links all working now but I went back in and re-enabled several modules and now links don't work. It appears the module "scene clicker" was the offending module and I have removed it and that module doesn't appear to be being updated at all.
