### ISSUE TITLE
No Homebrew Monsters accessible

### ISSUE THREAD

**Issue by ceriath** [MrPrimate/ddb-importer#267]
Hi,
i am trying to import some homebrew monsters. Those are shared with my via a campaign. Unfortunately this does not seem to work, since 0 Monsters are returned, i can also see that in the proxy logs:
```
https://monster-service.dndbeyond.com/v1/Monster?search=Corvum&skip=0&take=100&showHomebrew=t
Monster count: 0.
```
Might this be related to the campaign endpoint not working in the proxy? I opened an issue there earlier: https://github.com/MrPrimate/ddb-proxy/issues/23

I am trying to import: https://www.dndbeyond.com/homebrew/monsters?filter-type=0&filter-search=Corvum&filter-cr-min=&filter-cr-max=&filter-armor-class-min=&filter-armor-class-max=&filter-average-hp-min=&filter-average-hp-max=&filter-is-legendary=&filter-is-mythic=&filter-has-lair=&filter-author=&filter-author-previous=&filter-author-symbol=&filter-rating=-11

**Comment by MrPrimate** [comment]
This is not a bug in ddb-importer, but the proxy as you mentioned. Please follow the work around there, or set the campaign using my proxy.

**Comment by MrPrimate** [comment]
Related to/duplicate of #240
