### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'src')

### ISSUE THREAD

**Issue by skellitor301** [MrPrimate/ddb-importer#268]
I've gotten this error when trying to import a dndb character to foundryvtt.
ddb importer version: 3.1.2
Foundry version: 10 build 285
DND5E version: 2.0.2
f12 console:
![chrome_cMjFm1Sjka](https://user-images.githubusercontent.com/3630718/189741589-0d68acda-b426-4b32-89fc-8a8f85fd89db.png)
Btw the blanked areas are to block the dns address for my server. That's the only omitted data.

**Comment by skellitor301** [comment]
> Does this happen with other modules disabled? Can you provide a character URL? Was this character migrated from v9, or created a fresh in v10?

Yes, I've just tested disabling all other modules and I still get the error.
Character URL is: https://www.dndbeyond.com/characters/83352651
This was a freshly made character I put together about 2 days ago from this post.

**Comment by tsimnujhawj** [comment]
I was also experiencing this, but FWIW, creating a new actor solved it for me.

**Comment by skellitor301** [comment]
Oh, when you asked if the character was v9 did you mean the actor entry or no? Cause it is possible it might be a v9 actor, I'd have to double check.

**Comment by MrPrimate** [comment]
@skellitor301 yep, I think there is something weird going on with migrated characters

**Comment by skellitor301** [comment]
That is going to kinda suck considering both dndb and foundry have different inventory systems. We've been not syncing inventories cause of that >.<

**Comment by MrPrimate** [comment]
Could you try exporting you character (right click on them) and then import that into a new actor, and see if you can update that?

**Comment by skellitor301** [comment]
Just tried that, same result.
Here's the export json if you need it.
https://gist.github.com/skellitor301/0596a44a39aaad8b8f482564ef8cd1e0

**Comment by thefloppy1** [comment]
I too am getting this error, but only with the Magic type classes of 5e.  Wizard and Bard in my particular campaign.

**Comment by MrPrimate** [comment]
> Same resulting error. Here's the export json if you need it. https://gist.github.com/skellitor301/0596a44a39aaad8b8f482564ef8cd1e0

Okay this works for me - I created a fresh actor, imported the json into it, then ran the ddb importer, and it came in.

Can you try creating a new world, and try that process there?

**Comment by MrPrimate** [comment]
If that fails, can you generate a log file using the following: https://github.com/MrPrimate/ddb-importer/blob/main/FAQ.md#i-want-to-send-you-a-useful-log-info when you try and import

**Comment by skellitor301** [comment]
I was able to import the character with a fresh actor, that part works tine works fine, it's legacy version actors that have this issue. Which as mentioned would be an issue with desynced info like inventories and the like.

**Comment by MrPrimate** [comment]
Yes, but if you are recreating the actor from the json, then importing into that, it will have your data, surely?

You could also try opening the console and migrating your world again and watching for errors:
`game.dnd5e.migrations.migrateWorld()`

**Comment by MrPrimate** [comment]
Other users have reported success after running `game.dnd5e.migrations.migrateWorld()` in their world. It looks like this is the product of a bad migration after upgrading. Probably there was:
- a module that was not compatible that caused failures
- the browser restarted before migration was finished

**Comment by skellitor301** [comment]
> Yes, but if you are recreating the actor from the json, then importing into that, it will have your data, surely?

Unfortunately no, making a new actor and importing the json makes the actor ineligible to be updated with the module. That's the result of this test showed:

> Same resulting error. Here's the export json if you need it. https://gist.github.com/skellitor301/0596a44a39aaad8b8f482564ef8cd1e0

**Comment by MrXofar** [comment]
Getting this error myself. 
TypeError: Cannot read properties of undefined (reading 'src') Doppelganger

Tried several things, including what is on this page, plus I tried deleting all doppelgangers and munching monsters again, still no joy.

**Comment by Quidam2k** [comment]
Also cannot import due to this bug. 

![image](https://user-images.githubusercontent.com/32143050/194173276-ee3890ee-a4af-49f2-8bea-47ca5b21619b.png)
[ddbimporter-log-data.zip](https://github.com/MrPrimate/ddb-importer/files/9719302/ddbimporter-log-data.zip)

**Comment by MrPrimate** [comment]
@quidam2k this is a different bug to what you're seeing, your on v9 (or at least are using a v9 version of ddbimporter).
 I'm not actually sure what's causing it though, as I can't replicate with that character

**Comment by kcits** [comment]
I too am getting this error:

`logger.js:76 DDB Importer | ERR > error parsing NPC type monster: TypeError: Cannot read properties of undefined (reading 'src') Stirge`
`log	@	logger.js:76`
`error	@	logger.js:96`
`(anonymous) 	@	importMonster.js:372`
`Promise.catch (async)`
`(anonymous)	@	importMonster.js:371`
`addNPC	@	importMonster.js:366`
`parseCritters	@	monsters.js:147`
`logger.js:76 DDB Importer | ERR > TypeError: Cannot read properties of undefined (reading 'src')
    at Actor5e._preUpdate (https://[removedDomain]/scripts/commons.js:7267:59)
    at async Actor5e._preUpdate (https://[removedDomain]/systems/dnd5e/dnd5e.mjs:9151:5)`
`log	@	logger.js:76`
`error	@	logger.js:96`
`(anonymous)	@	importMonster.js:373`
`Promise.catch (async)	`	
`(anonymous)	@	importMonster.js:371`
`addNPC	@	importMonster.js:366`
`parseCritters	@	monsters.js:147`
`logger.js:76 DDB Importer | ERR > TypeError: Cannot read properties of undefined (reading 'src')`
`log	@	logger.js:76`
`error	@	logger.js:96`
`parseCritters	@	ddb.js:317`
`logger.js:76 DDB Importer | ERR > TypeError: Cannot read properties of undefined (reading 'src')
    at Actor5e._preUpdate (https://[removedDomain]/scripts/commons.js:7267:59)
    at async Actor5e._preUpdate (https://[removedDomain]/systems/dnd5e/dnd5e.mjs:9151:5)`
`log	@	logger.js:76`
`error	@	logger.js:96`
`parseCritters	@	ddb.js:318`

I have been getting it for the past 2 days when trying to much the Monsters.  I have turned modules off, and I also ran

`game.dnd5e.migrations.migrateWorld()`

those options did not fix the issue.

There is one thing that might not have to deal with ddb-importer, but D&DBeyond (see screenshots) as possible bad data or bad formatting on their website?  I can replicate the error quickly when using the Muncher and entering the term stirge.

![Screenshot 2022-10-06 092729](https://user-images.githubusercontent.com/1087569/194417188-483fa9e6-80db-45f6-9de3-ffd5a4e6191b.png)
![Screenshot 2022-10-05 at 19-09-38 stirge - Search - D D Beyond](https://user-images.githubusercontent.com/1087569/194417190-32c33fcf-9a7e-4ec7-bca9-5890d81de711.png)

**Comment by kcits** [comment]
Update: I updated to 10.287 and re-ran the Muncher and it worked.

**Comment by MrPrimate** [comment]
I believe it maybe related to https://github.com/foundryvtt/foundryvtt/issues/8241 which is fixed in the latest v10

**Comment by MrXofar** [comment]
10.287 update also seems to have corrected the issue for me. Thanks :)
