### ISSUE TITLE
Only pull from certain books

### ISSUE THREAD

**Issue by r04dw4rri0r** [MrPrimate/ddb-importer#269]
Would it be possible to only pull from certain sourcebooks that are on your Beyond account? If i am running a Sword Coast campaign it would be cool to only import that sourcebook, etc.

**Comment by MrPrimate** [comment]
Yes, you can already. On the muncher tab click "Restrict import to specific sources" and a button will appear allowing you to select. Please note that this is often just the "first" book a monster/spell appeared in, so it can not always work as expected.
