### ISSUE TITLE
Currency overwritten even when unchecked

### ISSUE THREAD

**Issue by frvwfr2** [MrPrimate/ddb-importer#27]
Import, uncheck the "Currency" button, but it still gets updated from DND Beyond, overwriting the information on the character sheet.

**Comment by MrPrimate** [comment]
Hi @frvwfr2 I can't replicate this can you upload a screen shot of the options selected, either here or on the discord. Thanks.

**Comment by frvwfr2** [comment]
Was doing further testing, and it seems I had a version (0.0.22) from a few days ago. Once I updated, the issue is gone. Thanks.
