### ISSUE TITLE
Error when resting on an imported character with spell gems

### ISSUE THREAD

**Issue by seanpg71** [MrPrimate/ddb-importer#271]
Foundry: 9.280
D&D Beyond Importer: 2.9.65
Magic Items: 2.2.1

If I import a character that has a Spell Gem in their inventory, I then get this error on a long rest and items fail to recharge for the character with Magic Items:

```
       Uncaught (in promise) TypeError: formula.replace is not a function
[Detected 1 package: magicitems]
    at Roll._extractFlavors (foundry.js:7314:23)
    at Roll._splitGroup (foundry.js:7204:35)
    at Roll._splitParentheses (foundry.js:7121:17)
    at Roll.parse (foundry.js:7041:22)
    at new Roll (foundry.js:6597:35)
    at OwnedMagicItem.doRecharge (magicitem.js:706:21)
    at OwnedMagicItem.onNewDay (magicitem.js:690:25)
    at magicitemactor.js:168:26
    at Array.forEach (<anonymous>)
    at MagicItemActor.onLongRest (magicitemactor.js:165:24)
    at Actor5e.longRest (magicitemactor.js:110:16)
```

The gems get created with this flag:

```
magicitems:
{
    "enabled": true,
    "charges": 1,
    "chargeType": "c1",
    "rechargeable": true,
    "recharge": 1,
    "rechargeType": "t2",
    "rechargeUnit": "r2",
    "destroy": false,
    "destroyCheck": "d1",
    "spells": {},
    "feats": {},
    "tables": {},
    "equipped": true,
    "attuned": false,
    "destroyFlavorText": "reaches 0 charges: it crumbles into ashes and is destroyed.",
    "sorting": "l"
}
```

Which more or less corresponds to the gem being set to recharge its one charge at dawn.  This isn't great - because it's not how spell gems recharge.  But even if it was, that "recharge" property seems to need to be a string in order to keep Magic Items from throwing that error.

Edit: Also note that just looking at the item is enough to convert it to a string and make the error go away - but you'd have to know to do that, and it breaks recharging for other items on the character - which may be more of a Magic Items problem.

**Comment by MrPrimate** [comment]
OKay, I see, I can't do much about the daily recharge on this - although I'd argue that's probably what's represented here, i.e. can you store/cast a spell in it.

I will force that field to be a string, which should avoid the error. This will be in the next release, which is v10 only.
