### ISSUE TITLE
createCompendiumFolder race condition prevents folders from creating during monster folder migration when Forge module active

### ISSUE THREAD

**Issue by rikmarais** [MrPrimate/ddb-importer#273]
Reported on Discord here https://discord.com/channels/759781688011522069/761196994898165781/1024950727614943282
There is a situation where Monsters do not import into Compendium Folders due to the folders being accessed before they become available, as shown here 
![image](https://user-images.githubusercontent.com/34374883/193944462-db7f8840-0d5b-468b-86f5-af3dce05bf48.png)

I thin that this is due to to a race condition, possibly due to a bug in `createCompendiumFolderStructure`'s case methods, the [`createChallengeRatingCompendiumFolders` method and others like it](https://github.com/MrPrimate/ddb-importer/blob/main/src/muncher/compendiumFolders.js#L123).

Because the `forEach` loop is not asynchronous, even if the function passed into it is, `resolve(promises)` could be hit before the `await createCompendiumFolder()` has a chance to complete.
For whatever reason, this race condition consistently happens when the Forge module is active, but has been reported to affect only monsters, not to affect spells and items.

Changing the code to push promises rather than folders, and then `await`ing the resolution of them all with `resolve(Promise.all(promises))` should be able to fix this. 

```js
// challenge rating
async function createChallengeRatingCompendiumFolders(packName) {
  return new Promise((resolve) => {
    let promises = [];
    CONFIG.DDB.challengeRatings.forEach(async (cr) => {
      const paddedCR = String(cr.value).padStart(2, "0");
      promises.push(createCompendiumFolder(packName, `CR ${paddedCR}`, "#6f0006"));
    });
    resolve(Promise.all(promises));
  });
}
```

**Comment by MrPrimate** [comment]
I have pushed this change in v3.1.12
