### ISSUE TITLE
In Foundry V10 the Core setup dialog won't open

### ISSUE THREAD

**Issue by AlbanT** [MrPrimate/ddb-importer#275]
I updated the D&D Beyond importer to v3.1.14 and am running Foundry V10.287

When I go to Configure settings and try to open the D&D Beyond Importer core setup dialog nothing happens.
The other buttons do show the respectively dialogs.

Is this reproducable? Or am I doing something wrong?

**Comment by MrPrimate** [comment]
It does sometimes happen, please try the following step to see if it resolves the issue: https://github.com/MrPrimate/ddb-importer/blob/main/FAQ.md#my-core-settings-screen-wont-open

**Comment by rouceto1** [comment]
Restart of the foundry server helped.
