### ISSUE TITLE
Rage broken

### ISSUE THREAD

**Issue by itteerde** [MrPrimate/ddb-importer#276]
seemingly only the number of rages, not the damage is filled into the Actor

**Comment by itteerde** [comment]
Actually pretty much all Barbarian Advancement is missed -- including this.

**Comment by itteerde** [comment]
Is there something like a mission statement for the module what quality of matching it tries to achieve? We are considering how central DnDB and your importer should be for our FVTT game and it is a bit unclear atm what way we should go, not least depending on how much breakage on import is to be expected. Your tool is great as is, but it still is a lot of breakage (as matching system is difficult to impossible).

**Comment by kaelad02** [comment]
When you compare the Barbarian class on an imported PC to the copy of the class in the SRD compendium you can see the differences. It has a scale value for the number of rages but its identifier is `rage` instead of `rages`. It's also missing the Rage Damage scale value.

**Comment by MrPrimate** [comment]
How are you importing/using rage here?

When I import a barbarian with Rage, and have midi-qol and dae installed I get full effects and advancements.

The importer is primarily designed to import working characters and monsters into Foundry to use.

If you are building characters using the feature imports from the "Characters" tab of the muncher, at the moment it will be missing most functionality, and will just be descriptions.

**Comment by kaelad02** [comment]
OP was originally asking for help with this on the main Foundry Discord server. They were having an issue with applying the Rage effect from Convenient Effects. That version of Rage references the melee damage bonus's scaling value based on how the scaling value is defined in the copy of Barbarian in the SRD compendium. If you try and use the CE version of Rage with an imported barbarian PC, it does not work since the identifier of the scale value is not the same.

**Comment by itteerde** [comment]
> The importer is primarily designed to import working characters and monsters into Foundry to use.
The character was imported with ddb-importer, neither created from scratch, nor using anything from compendia. After the simingly successful import of this Level 5 Bear Totem Barbarian using a newly created level 0 Actor the Actor has the values as stated by kaelad02
![Screenshot 2022-10-13 151949](https://user-images.githubusercontent.com/8367477/195607897-e34c611f-1fb0-40d3-910d-499a56d792aa.png)
where it should (well, I think it would be good to match what comes with dnd5e and DFred in this case agrees) be
![Screenshot 2022-10-13 152234](https://user-images.githubusercontent.com/8367477/195608349-7912bf51-d079-43f5-9878-4d5f60cb902c.png)

**Comment by MrPrimate** [comment]
These values are automatically generated by the data provided by DDB, thus you get slightly different class configurations.

If using MidiQoL, DAE and DFreds CE, make sure you set the MidiQOL Workflow setting "Apply Convenient Effects" to "Apply Item effects, if absent apply CE". This will then use the rage effect built into DDB importer, rather than DFreds.

**Comment by itteerde** [comment]
I see. Will try that and evaluate if that is an option for us. I think working with effects granting items instead of DFreds should be okay for our DM if there is some value like this. So trying to replace DFreds no as we are running MidiQOL already anyways just without automatically applying effects.
And again, great work (already for the state so far, if you are correct and we can fix it this way even more so). Hope you keep up working on it as matching systems (at one of them without open source or cooperation) is a nightmare, but DnDBeyond is just to convenient not to use -- therefore need you to keep working it!

**Comment by MrPrimate** [comment]
I do use DF Freds for condition effect and management, so is worth keeping around.

**Comment by MrPrimate** [comment]
I have "fixed" this in v3.1.16, it will now add the SRD advancements where there is no identifier clash.

**Comment by itteerde** [comment]
much appreciated, tested, works.
