### ISSUE TITLE
Item rarity ends up being non-blocking-space string

### ISSUE THREAD

**Issue by itteerde** [MrPrimate/ddb-importer#277]
cosmetic bug mainly: Item rarity ends up bing non-blocking-space string

![Screenshot 2022-10-18 153332](https://user-images.githubusercontent.com/8367477/196445005-3a81d4ed-a4d6-43f0-b1cc-c4bd159420bc.png)

**Comment by MrPrimate** [comment]
This is a core 5e bug, rather than something to do with DDB Importer - this field should be blank, but it seems that latest version of 5e sets it to  non-blocking-space string

**Comment by MrPrimate** [comment]
This is https://github.com/foundryvtt/dnd5e/issues/1850
