### ISSUE TITLE
Greek character names overwriting character art (probably most non-ASCII or non Latin-1?)

### ISSUE THREAD

**Issue by itteerde** [MrPrimate/ddb-importer#278]
Picking Greek character names, such as Δοκιμή and Ηλιακό φως, even differently names character end up overwriting each other's character art as it becomes ddb-images/characters/-.jpeg for both of them. While using character names instead of an unique ID here is already not that good, this bug will map a lot of names to the same bug-string filename overwriting each others.

**Comment by itteerde** [comment]
Seeing the result of the overwriting needs reloading, before doing so it seems as if it kept the first image for both.

**Comment by itteerde** [comment]
For repeated overwriting/ testing one also needs to check importing the image manually (guess it sees that nothing changed at the source and [of course] is unaware that it despite that is different from the destination).

**Comment by itteerde** [comment]
Drops German Umlaute as well.

**Comment by MrPrimate** [comment]
Wow, okay, that's awkward, as a temp workaround I'll ship a fix in the next few hours. It will add the unique ddb character id to the file name. Also, amazed it's taken this long for someone to have this problem!

**Comment by itteerde** [comment]
Great!

**Comment by MrPrimate** [comment]
Fixed in v3.1.19
