### ISSUE TITLE
DDB Importer boxes won't tick on

### ISSUE THREAD

**Issue by jerazost** [MrPrimate/ddb-importer#279]
![image](https://user-images.githubusercontent.com/13992684/197421434-527cd7ce-f20c-46bb-88bb-45f3fba592c3.png)

Attempting to tick any of the boxes above produces no change and logs nothing to the console. 

- Patreon Link is valid
- Cobalt cookie is valid
- Campaign ID is selected

Foundry Version 10 Build 286

**Comment by MrPrimate** [comment]
So this option is currently only available to Undying tier as it's a bit wobbly right now. You can sync characters back individually on the character import tabs without altering anything here.

**Comment by jerazost** [comment]
I see, that wasn't totally clear from what I saw. Thanks for the clarification!
