### ISSUE TITLE
DDB Magic Item Spell Save DC Bonus Not Applying on Import

### ISSUE THREAD

**Issue by eclay1819** [MrPrimate/ddb-importer#280]
First, thank you so much for all of your work on this module - absolutely integral to my Foundry setup.

My players have some items that add a bonus to spell save DC and spell attack (Ex. Moon Sickle). However, when importing into Foundry, the spell attack bonus is reflected, but not the spell save DC bonus. I was able to find a workaround by adding a dummy item that adds a bonus to the "Warlock Spell Save DC" instead (Rod of the Pact Keeper), and that bonus does apply properly when imported.

I'm running v10 288 and 3.1.20 of the module. Steps to reproduce below:

1. Create a druid in DDB and add/equip/attune the Moon Sickle +1
2. Note the spell save DC and spell attack bonuses in DDB
3. Import into Foundry VTT
4. Note the spell save DC and spell attack bonuses - in my tests, the spell attack matches, but the spell save DC does not reflect the magic item.
5. Replace the Moon Sickle with a Rod of the Pact Keeper +1 (equip/attune)
6. Note the spell save DC and spell attack bonuses in DDB - it will not reflect the item bonus since it is limited to Warlocks
7. Import into Foundry VTT
8. Note the spell save DC and spell attack bonuses - in my tests, the item bonuses are properly reflected in Foundry

So this ends up being 2 bugs that are probably related:

1. Bonus - Spell Save DC is not being reflected when imported into Foundry
2. Bonus - Warlock Spell Save DC is being reflected when imported into Foundry even if the player is not a Warlock.

**Comment by MrPrimate** [comment]
Ah! Thanks for this report. I've fixed this in the soon to be released v3.1.21

**Comment by eclay1819** [comment]
Dude....you rock. 👏
