### ISSUE TITLE
Monster Import | Feature icons are still using the old system paths

### ISSUE THREAD

**Issue by webmaster94** [MrPrimate/ddb-importer#281]
Many of the monster feature icons are still using the old dnd5e system path icons. These icons were removed in dnd5e 2.0.1. I did a full re-import when I updated everything from Foundry v9 to Foundry v10 to be sure everything was at the latest version. 

**Screenshots** (Some Examples)
![image](https://user-images.githubusercontent.com/85364225/199986612-728add76-77b7-4451-8ecd-159ef40df48c.png)
![image](https://user-images.githubusercontent.com/85364225/199986692-76fb9219-b487-4a18-a030-4d474be602e6.png)

**Environment:**
 - Browser chrome
 - Foundry Version 10.288
 - 5e System Version 2.0.3
 - Module Version 3.1.22
 - Does this behaviour occur with other modules disabled: Yes

**Comment by MrPrimate** [comment]
These have definitely been fixed, so I suggest something went wrong with your compendium migration, you didn't have update existing things checked, or you imported with a very early version of DDB Importer for V10.

**Comment by webmaster94** [comment]
This was me screwing up. I forgot that the compendium for imported monsters is world by world. You are correct, this is only an issue in one of the worlds that did have old stuff.
