### ISSUE TITLE
Getting an error on (every?) monster import.

### ISSUE THREAD

**Issue by AlanDNelson** [MrPrimate/ddb-importer#282]
**Describe the bug**
Getting errors importing monsters....

**To Reproduce**
Import any monster from D&D Beyond via Monster Munch.

**Expected behavior**
No error.

**Screenshots**
![image](https://user-images.githubusercontent.com/36895037/200148707-4985351b-ceb5-44d7-8a15-267c3ecd4c99.png)
![image](https://user-images.githubusercontent.com/36895037/200148716-f5e4b4ca-0e6e-4739-a828-89b26f507ec8.png)

**Environment:**
Foundry Virtual Tabletop: Version 10, 10.288
Game System: dnd5e, 2.0.3
Active Modules: 47
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
GPU: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 2000 x 1124 | Grid Size: 100 | Padding Percentage: 0
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 6

Actors: 46 | Items: 26 | Journal: 20 | Rollable Tables: 1 |
Playlists: 4 | Compendium Packs: 52 | Chat Messages: 56

**Comment by MrPrimate** [comment]
There are two key elements that you didn't answer in the bug report template. Please provide:

 - Module Version [e.g 3.1.21]
 - Does this behaviour occur with other modules disabled: Yes/No (Find The Culprit module can help with this)
 
 I ask because this does not occur here, and the most likely outcome is that one of the other modules is changing/adjusting the model data.
 
 The other option is that the default token settings in your world have "Sense All" added as a default detection mode.

**Comment by AlanDNelson** [comment]
Version was 3.1.23

I did not have all other modules enabled... but I only enabled the one's specifically mentioned as required in the Muncher screen... as follows:

![image](https://user-images.githubusercontent.com/36895037/200204095-50838801-4d19-438b-a4aa-f5526cd23563.png)

![image](https://user-images.githubusercontent.com/36895037/200204141-54af3f1f-02f1-45e1-afdd-6fc9f409fe98.png)

### Active Modules
Active-Auras
Active Token Effects
Advanced Macros
D&D Beyond Importer
DFreds Convenient Effects
Dynamic effects using Active Effects
Item Macro
libWrapper
socketlib
Midi QOL
Module Management+
Sequencer
Automated Animations
Times Up
Token Magic FX

Working on "Find the Culprit"...

**Comment by AlanDNelson** [comment]
I did have Sense All set up in my default token.  That's probably the cause of the problem.  I would think that setting up a "Sense All" ontop of another would just overwrite the setting...

**Comment by AlanDNelson** [comment]
I can confirm it was the default token settings....

**Comment by MrPrimate** [comment]
I have added a check for the next release so it won't add multiple senses

**Comment by MrPrimate** [comment]
Resolved in v3.1.24
