### ISSUE TITLE
Can't install module on Foundry v 10.290

### ISSUE THREAD

**Issue by joelmacd** [MrPrimate/ddb-importer#283]
**Describe the bug**
When trying to install DDB Importer v 3.1.25 get error message: "Errors were encountered while installing the package. Consult your console log (F12) for details."

**To Reproduce**
1. Go to 'Add-on Modules'
2. Click on 'Install Module'
3. Scroll down to 'D&D Beyond Importer'
4. Click on 'Install'
5. See error

**Expected behavior**
Module to download and install.

**Screenshots**
From console log:
'foundry.js:58907 Errors were encountered while installing the package. Consult your console log (F12) for details.
fetch @ foundry.js:58907
setup.js:141 [ddb-importer] Metadata validation failed for module "ddb-importer": The file "vendor/jszip/jszip.min.js" included by module ddb-importer does not exist
#logPackageWarnings @ setup.js:141'

**Environment:**
 - Foundry App
 - Foundry Version 10.290
 - 5e System Version 2.0.3
 - Module Version 3.1.25
 - Does this behaviour occur with other modules disabled: N/A

**Additional context**

**Comment by MrPrimate** [comment]
This definitely exists in the file, you can check here https://github.com/MrPrimate/ddb-importer/releases/tag/3.1.25

The most likely problem here is that the download of the zip failed or was disrupted. Foundry does some local caching for modules. Stop the foundry server and clear out any downloaded ddb-importer modules, or extract the zip manially.
