### ISSUE TITLE
Homebrew spells from Beyond not working (cantrips)

### ISSUE THREAD

**Issue by boozybeggarchi** [MrPrimate/ddb-importer#284]
Had an issue dealing with spells from Beyond that were homebrew/third party spells entered into beyond.
A level 1 spell seemed to work fine, but became denoted in Foundry as Always Prepared.
Two cantrips refused to be scraped from Beyond into Foundry.

**Comment by MrPrimate** [comment]
If the spells are not attached to a character, they will need to be part of a spell list for one of the core classes.

This will effect how they are imported/parsed.

If they are attached to a character, please provide a link so I can import and investigate.

**Comment by boozybeggarchi** [comment]
so the homebrewed spells are attached to a character.
I'm guessing you need the character link so here's the DDB link:
https://ddb.ac/characters/77916449/nq6olY

Both Phantom Light and Starburst are Kobold press spells the player entered
as homebrew (one of them they also tried using my own homebrew entry to see
if it mattered between DM vs player creation) that are on the Beyond sheet
but not the imported version on Foundry on the spell page.

Thanks for looking into this!

**Comment by MrPrimate** [comment]
Okay, this should now be fixed, if you're using your own proxy please update to v0.0.22, or, if using mine, just munch the character again.
