### ISSUE TITLE
Death Save Push to D&D Beyond Fails

### ISSUE THREAD

**Issue by brandon-hurler** [MrPrimate/ddb-importer#287]
**Describe the bug**
When syncing to D&D beyond from Foundry, the console logs errors indicating death saving throws have failed to upload.

**To Reproduce**
1. Go to an actor's character sheet.
2. Perform an 'empty' sync (same as freshly fetched) - this should work perfectly with no errors in the log.
3. Delete a death save value (instead of setting to 0).
4. Resync and see the error in the log.

**Expected behavior**
It looks like the death saves fail due to a missing null coalescing to 0 when a user deletes the value instead of setting it to 0. Absent values should default back to 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/112717624/210587033-d05c6953-9a3a-4544-8db7-851214861b86.png)
![image](https://user-images.githubusercontent.com/112717624/210587430-a2765bb2-86be-4d1d-8fac-a808f3a95613.png)

**Environment:**
 - Browsers Chrome, Brave
 - Foundry Version 10.291
 - 5e System Version 2.0.3
 - Module Version 3.2.12
 - Does this behavior occur with other modules disabled: Yes

**Comment by brandon-hurler** [comment]
One additional comment: the same issue may occur for other fields that sync that can be manually modified. May be worth checking those areas as well for the same check type.

**Comment by MrPrimate** [comment]
Thanks for this, it will be fixed in the next release.
