### ISSUE TITLE
Duplicate Companion Import

### ISSUE THREAD

**Issue by brandon-hurler** [MrPrimate/ddb-importer#288]
**Describe the bug**
When importing companions, the import does not check for an existing companion list and duplicates the entries. With the existing functionality, you have to delete the list before importing.

**To Reproduce**
1. Go to an actor's character sheet
2. Click on the D&D Beyond Import
3. Click on the Import Companions tab
4. Import Companions twice

**Expected behavior**
When importing companions, I would expect to only import the deltas if they have been imported once before. For example, we are using companion tracking for known druidic wildshapes. They can only wild shape into creatures they have seen before that are defined by the rules and their levels. When leveling up, they also gain access to swimming and flying. All of these will cause deltas.

**Screenshots**
![image](https://user-images.githubusercontent.com/112717624/210590489-ea7714d3-e95c-4cf3-83dd-e198aaf20c75.png)
![image](https://user-images.githubusercontent.com/112717624/210590984-ca2caeed-e81b-4c47-b87e-37109109077e.png)

**Environment:**
 - Browser Chrome, Brave
 - Foundry Version 10.291
 - 5e System Version 2.0.3
 - Module Version 3.2.12
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**
There are no errors in the logs.

**Comment by MrPrimate** [comment]
Thanks, this will be fixed in the next release
