### ISSUE TITLE
Update Failed when running "Update D&D Beyond"

### ISSUE THREAD

**Issue by mrte1122** [MrPrimate/ddb-importer#291]
**Describe the bug**
When attempting to push character changes back to dnd beyond character sheet after running a session in foundry, I receive the following error: "Update failed: (Man'dos) Unknown error during character update: (see console log (F12) for more details)"

This Update to DND beyond feature has worked without error before, but I am thinking caused the error is when trying to level up in a character sheet in foundry, then running the "update to dnd beyond" feature, the error started occurring. 

**To Reproduce**
1. Go to character sheet, features tab within foundry, then level up class
2. go through foundry prompts to roll hit die
3. once done, try to run "update to dnd beyond" 

**Expected behavior**
DND Beyond Update feature should push inventory updates, HP changes, inspiration, spell slots, etc back to the dnd beyond character sheet.

**Screenshots**
see attached

**Environment:**
 - Browser : Mozilla Firefox
 - Foundry Version: 10 build 291
 - 5e System Version: 2.1.1
 - Module Version: 3.3.0
 - Does this behavior occur with other modules disabled: Yes
 - 

 - A Character URL: https://www.dndbeyond.com/characters/90259764
 - Details of any errors in the browser console (press F12).
![Capture](https://user-images.githubusercontent.com/24609723/212098581-999b8b79-c9a6-4ced-bca7-b11a510be5bd.PNG)

**Comment by MrPrimate** [comment]
Oh, thanks for this, looks like I need to make some changes for the schema validation in D&D 1.2.x system.

**Comment by MrPrimate** [comment]
Hoping this is fixed in v3.3.1

**Comment by mrte1122** [comment]
Thanks for the response. I updated to v3.3.1, and just did a quick test to push back to DnD beyond with the character sheet i posted above, and I did not receive the error.
