### ISSUE TITLE
Arkhan the Cruel Import Failure

### ISSUE THREAD

**Issue by Vhostym-the-Sojourner** [MrPrimate/ddb-importer#293]
**Describe the bug**
When importing the monster list, Arkhan the Cruel fails.

**To Reproduce**
1. Run the DDB Muncher with the settings in the screenshots below.

**Screenshots**
![image](https://user-images.githubusercontent.com/122459669/212494579-46ba4460-b5e0-4707-8b3f-fa75052eda75.png)
![image](https://user-images.githubusercontent.com/122459669/212494586-93fe3d43-2e9f-41c3-9fc8-ecec7fb4c226.png)
![image](https://user-images.githubusercontent.com/122459669/212494608-e3536052-2c03-46a5-bf26-7ecac471eee9.png)
![image](https://user-images.githubusercontent.com/122459669/212494626-4baacbb2-fea8-430b-9cca-8335d1656162.png)

**Environment:**
 - Browser Chrome, Firefox
 - Foundry Version [e.g. 10.291]
 - 5e System Version [e.g 2.1.2]
 - Module Version [e.g 3.3.2]
 - Does this behaviour occur with other modules disabled: Unknown (need other modules for effects, see screenshot)

**Comment by Vhostym-the-Sojourner** [comment]
In looking over the error, I am unsure if this is a DAE bug or one with the importer. If you think it is a DAE bug, I can post there.

**Comment by MrPrimate** [comment]
I think this is likely a DAE bug - for what it's worth I can't replicate it here.

**Comment by Vhostym-the-Sojourner** [comment]
No worries, I can raise it there. Thanks!
