### ISSUE TITLE
Legacy Monsters Imported Twice

### ISSUE THREAD

**Issue by Vhostym-the-Sojourner** [MrPrimate/ddb-importer#294]
**Describe the bug**
When running the DDB Monster Muncher, the importer will import new instances of creatures appended with the (Legacy) trait when the muncher is run multiple times.

**To Reproduce**
1. Go to the DBB Muncher.
2. Apply the settings in the screenshots below.
3. Run the importer multiple times.

**Screenshots**
![image](https://user-images.githubusercontent.com/122459669/212495464-cdb94984-02f0-4b72-9aec-5b63fdc2c8e4.png)
![image](https://user-images.githubusercontent.com/122459669/212495466-6a528dcf-f10a-40a1-9c86-9c210b302b1f.png)
![image](https://user-images.githubusercontent.com/122459669/212495474-3f8b0601-ffcf-477c-943f-00ece16eb440.png)

**Environment:**
 - Browser Chrome, Firefox
 - Foundry Version [e.g. 10.291]
 - 5e System Version [e.g 2.1.2]
 - Module Version [e.g 3.3.2]
 - Does this behavior occur with other modules disabled: Yes

**Comment by MrPrimate** [comment]
Fixed in v3.3.3
