### ISSUE TITLE
Companion Import Fails

### ISSUE THREAD

**Issue by Vhostym-the-Sojourner** [MrPrimate/ddb-importer#295]
**Describe the bug**
When importing companions, the import fails entirely, not adding any entries.

**To Reproduce**
1. Go to a character sheet and click on the D&D Beyond import button
2. Click on Import Companions
3. Click on Import Extras

**Screenshots**
![image](https://user-images.githubusercontent.com/122459669/212501119-960d8f88-20ff-45f0-b7ac-11ed59f21c4b.png)

**Environment:**
 - Browser Chrome, Firefox
 - Foundry Version [e.g. 10.291]
 - 5e System Version [e.g 2.1.2]
 - Module Version [e.g 3.3.2]
 - Does this behavior occur with other modules disabled: Yes

Example character URLs:
[https://www.dndbeyond.com/characters/74349127](https://www.dndbeyond.com/characters/74349127)

**Comment by MrPrimate** [comment]
This is fixed in the upcoming v3.3.4 release.
