### ISSUE TITLE
Bugged interaction Between Aura of Protection and Cloak of Protection on import

### ISSUE THREAD

**Issue by GSBicalho** [MrPrimate/ddb-importer#296]
**Describe the bug**
When a paladin gets its Aura of Protection (+5 on all saves) and puts on a Cloak of Protection (+1) on all saves, they get a "+51" bonus to saves instead of a "+5+1". Which makes them _slightly_ overpowered. The player doesn't really mind, but I do.

Here is a character you can use to test the bug, instead of creating one: https://www.dndbeyond.com/characters/92118025

**To Reproduce**
1. Create a 17th level paladin in DnDBeyond and import it to foundry. 
2. Open its character sheet to see everything is normal.
3. Click on the "Configure Ability Checks and Saving Throws" cog by the saving throws, you will see it has a "+ 5" Global Saving Throw Bonus, as expected
4. Add a Cloak of Protection to your paladin in DnDBeyond. Attune to it. Under the saves in DndBeyond, you will see it gets "+5 on saves" and "+1 on saves". 
5. Reimport the character to foundry
6. Open its character sheet and check the saving throw bonus on all stats is +Fifty-something
7.  Click on the "Configure Ability Checks and Saving Throws" cog by the saving throws, you will see it has a "+ 51" Global Saving Throw Bonus

**Expected behavior**
The imported character should only have a +6 to saving throws

**Screenshots**
![image](https://user-images.githubusercontent.com/5908933/212795367-b43338b7-c4a0-4fcb-bde0-9a122e831729.png)

**Environment:**
 - Browser: Any
 - Foundry Version: 10.291
 - 5e System Version: 2.1.2
 - Module Version: 3.3.4
 - Does this behavior occur with other modules disabled: Yes

**Comment by MrPrimate** [comment]
This will be fixed in v3.3.4
