### ISSUE TITLE
Characters are deleted after I sync them

### ISSUE THREAD

**Issue by mattimeo84** [MrPrimate/ddb-importer#298]
**Describe the bug**
Every time I sync a character, I have issues being able to place a token. When I refresh my browser (both Chrome and Firefox), the characters are deleted from my actors tab. This works on both new imports and syncing established characters. 

**Environment:**
 - Browser: Chrome [Version 109.0.5414.76 (Official Build) (64-bit)]
 - Browser: Firefox [109.0 (64-bit)]
 - Foundry [v10 Stable - Patch 5 (Build 288)]
 - Forge [Story Teller]
 - 5e System Version [v2.1.2]
 - Module Version [v3.3.6]
 - Does this behaviour occur with other modules disabled: Yes, Find the Culprit found an issue with DNDBeyond Character Sheet for 5E. Disabled DNDBeyond Character Sheet for 5E and the problem resolved itself. 

**Additional context**
I can live without the Character Sheet Module if needed, but the players really liked it.

**Comment by MrPrimate** [comment]
This is a problem with the character sheet module, not the importer. It has not been updated to work with the D&D 5e system 2.1.x changes
