### ISSUE TITLE
Battle Master Commander's Strike applying to melee damage only

### ISSUE THREAD

**Issue by modzy2** [MrPrimate/ddb-importer#300]
**Describe the bug**
The Battle Master Commander's Strike is adding the effect as melee damage only (system.bonuses.mwak.damage) but it should apply to ranged damage also

**Expected behavior**
"That creature can immediately use its reaction to make one weapon attack, adding the superiority die to the attack’s damage roll."

**Environment:**
 - Browser chrome
 - Foundry Version  10.292
 - 5e System Version  2.1.4
 - Module Version 3.3.6
 - Does this behaviour occur with other modules disabled: Yes, except still having midi qol, midi srd, dae srd

**Comment by MrPrimate** [comment]
Will be fixed in the next release, thanks for the report.
