### ISSUE TITLE
Items actiosn and features appearing twice on chracter sheet

### ISSUE THREAD

**Issue by SilverwolfNL** [MrPrimate/ddb-importer#304]
**Describe the bug**
Not sure what is happenign seeign attacks features and actions appearigt wice on soe monsters after importing them, however not on all of them.  

**To Reproduce**
Unsure .. tried importin twice. evend eleted compendium after first try

**Expected behavior**
would exect them to only appear once

**Screenshots**
see screenshot atached of 1 monster as example

**Environment:**
 - Edge
 - Foundry Version 10.291
 - 5e System Version [e.g 2.1.4]
 - Module Version [e.g 3.3.10
 - Does this behaviour occur with other modules disabled: Yes/No (Find The Culprit module can help with this)
unsure did not try yet

**Additional context**

 - A Character URL, if the problem is a character import.
 - Details of any errors in the browser console (press F12).
![double](https://user-images.githubusercontent.com/26388997/219882400-5936e0d6-6ab5-45f0-b363-ad3a60edb34f.jpg)

**Comment by MrPrimate** [comment]
If you had tried disabling other modules, as asked, you would have discovered this is The Tagger module. You can track this issue here https://github.com/fantasycalendar/FoundryVTT-Tagger/issues/26

**Comment by SilverwolfNL** [comment]
thnx for the speedy reply.. saved me tiem diabling all other modules tommorrow
