### ISSUE TITLE
Hideous laughter ondamage hook doesn't work

### ISSUE THREAD

**Issue by xenoguy** [MrPrimate/ddb-importer#308]
**Describe the bug**
a condition in the item macro never evaluates to true, so the ondamage hook doesn't work.

**To Reproduce**
cast tashas hideous laughter, fail the save.  then change the targets hp, or damage it.

**Expected behavior**
the ondamage hook should automatically roll a saving throw with advantage if damage is taken

**Environment:**
 - Browser chrome 110
 - Foundry Version 10 build 291
 - 5e System Version 2.1.5
 - Module Version 3.3.14
 - Does this behaviour occur with other modules disabled: N/A

**Additional context**
Line 36 of hideouslaughter.js:
`if (!("actorData.system.attributes.hp" in update) || !flag) return;`
never evaluates to true.

I modified it to:
`if (!("value" in update.system.attributes.hp) || !flag) return;`
and it works.  maybe there's a better way to use the in operator, not a JS expert.

**Comment by MrPrimate** [comment]
Thanks for the report, fixed in the next version, out some time this weekend

**Comment by MrPrimate** [comment]
Released
