### ISSUE TITLE
Pack Tactics incorect

### ISSUE THREAD

**Issue by StevenEvans1966** [MrPrimate/ddb-importer#312]
**Description
Pack Tactics is giving advantage when a Kobol is next to the attacking Kobol.  

**Expected behavior**
Advantage should be given if a Kobol is next to the target of an other Kobol.

_"The kobold has advantage on an attack roll against a creature if at least one of the kobold's allies is within 5 feet of the creature and the ally isn't incapacitated."_

**Comment by StevenEvans1966** [comment]
i think the Effect value should be
    **findNearby(-1, targetUuid, 5, 0).some(t=>t.actor.effects.some(t=>t.label==="Pack Tactics"))**

**Comment by StevenEvans1966** [comment]
opps need to filter out attacking token
**findNearby(-1, targetUuid, 5, 0)
  .filter(t=>t.actor.uuid !== tokenUuid)
  .some(t=>t.actor.effects.some(t=>t.label==="Pack Tactics"))**

**Comment by MrPrimate** [comment]
This does make the assumption that a kobolds only allies are other Kobolds with Pack Tactics.

**Comment by StevenEvans1966** [comment]
Yes, but the description of Pack Tactics is explicit to Kobols so not unreasonable

**Comment by MrPrimate** [comment]
I think `findNearby(-1, targetUuid, 5, 0).length > 1` will work

**Comment by MrPrimate** [comment]
Will be in v3.4.8
