### ISSUE TITLE
Swordburst Cantrip quick fix for Midi users

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#319]
For Midiqol users:

Change this:
![image](https://user-images.githubusercontent.com/116308065/233810525-a3a1d4d0-b93d-4617-9675-928d759b4165.png)

to this:
![image](https://user-images.githubusercontent.com/116308065/233810543-65e38aa9-d0b7-4489-9303-83b4a3952e56.png)

**Comment by MotoMoto1234** [comment]
If the midi user has the default settings for targetting on, then the spell will auto target all creatures within the range and the special causes midi to ignore the caster.  If they don't have the default targetting settings, thats ok the spell will basically behave just like the unedited version then.  No harm no foul.

**Comment by MrPrimate** [comment]
Fix in next release.
