### ISSUE TITLE
Thunderclap Cantrip for Midiqol

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#320]
Similar to my issue about Swordburst:
(Midiqol lets you target all creatures within 5ft automatically if the setting is set right, and if its not then no harm no foul the change will behave just like a simple attack or prompt late targetting)  Special is important to cause it to not target the caster.  

Change this:
![image](https://user-images.githubusercontent.com/116308065/233810720-74486877-2682-4a5e-a23f-f73ebfdab5db.png)

To this:
![image](https://user-images.githubusercontent.com/116308065/233810734-e53a68d4-1170-4128-988f-8ab4aa3a8ba4.png)

**Comment by MrPrimate** [comment]
Fix in next release
