### ISSUE TITLE
MidiQOL error in Witch Bolt macro

### ISSUE THREAD

**Issue by Krigsmaskine** [MrPrimate/ddb-importer#325]
I was trying out your Witch Bolt macro and it was erroring - I believe this line
https://github.com/MrPrimate/ddb-importer/blob/b451b4013d9ccc43a7a06922496c21ec808bbe7c/macros/spells/witchBolt.js#L35
should be
`
await MidiQOL.socket().executeAsGM("removeEffects", { actorUuid: caster.uuid, effects: [concentration.id] });
`
instead. Seemed to solve the issue for me and make it work as expected. Great macro otherwise. Thanks!

**Comment by MrPrimate** [comment]
Thanks!
