### ISSUE TITLE
DDB Cobalt Token Invalid error

### ISSUE THREAD

**Issue by Poonjam85** [MrPrimate/ddb-importer#327]
Every time I copy and paste my Cobalt cookie, i get the cookie is invalid.  I"ve followed the steps listed to get it to work and followed them but it don't seem to be working at all.  I have tried to copy the cookie from Chrome, Brave, and even... edge... not proud of that one.  Any help would be appreciated bc i'd love to be able to use my entire collection of ddb sources and materials, as well as my PCs

**Comment by MrPrimate** [comment]
1. Make sure you are logged into DDB
2. Go to https://www.dndbeyond.com/
3. In the browsers developer tools cookie/storage area, search for `CobaltSession` note there can be multiple cookies starting with `Cobalt` so make sure you copy the right one. You are probably copying one called `cobalt-token` which is incorrect.
