### ISSUE TITLE
Sacred Weapon for Midiqol is setup ina way that can result in problems

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#328]
**Describe the bug**
On the effect's first tab, the two boxes for apply to self should be unchecked, this item should be a standard effect transfer so no boxes should be checked.  However, once this is done, on the actual sacred weapon feature, in the details, you need to set range/target to self/self.  This makes it so the item never throws an error/fails when the user has nothing targetted.  The old setup only successfully works when the user has something targetted.  I will share the images below

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - Browser [e.g. chrome]
 - Foundry Version [e.g. 10.288]
 - 5e System Version [e.g 2.0.3]
 - Module Version [e.g 3.1.21]
 - Does this behaviour occur with other modules disabled: Yes/No (Find The Culprit module can help with this)

**Additional context**
![image](https://github.com/MrPrimate/ddb-importer/assets/116308065/0b90e14f-7905-4824-ae66-a0682d5c88d4)
![image](https://github.com/MrPrimate/ddb-importer/assets/116308065/072cfb3d-01e5-45cd-9d0f-be9c4e6c1054)

**Comment by MotoMoto1234** [comment]
I have additional changes you need to make for this premade to work properly in midi 42/dae 29:
![image](https://github.com/MrPrimate/ddb-importer/assets/116308065/ab97f778-8350-4927-8411-aa747dcc3e82)
![image](https://github.com/MrPrimate/ddb-importer/assets/116308065/a92e26a0-4579-4fff-b1a2-a04fba2a5697)
![image](https://github.com/MrPrimate/ddb-importer/assets/116308065/fa6640f8-6123-4e8d-93f0-81892cadb11d)

**Comment by MotoMoto1234** [comment]
The problem with the existing premade is that it lasts for 1 turn, I think because midi does not like the "10 turns" you have in the duration tab.  Though your guess is better than mine on why exactly the effect auto ends after the first turn.  What I changed, fixes things though.

**Comment by MrPrimate** [comment]
Fixed in v3.4.22
