### ISSUE TITLE
[BUG] Unable to parse option class info

### ISSUE THREAD

**Issue by cwramsey** [MrPrimate/ddb-importer#33]
Hey there!

So I've been moving to use this module instead of the original from VTTA to solve the following issue, but it still exists.

When importing[ this character](https://www.dndbeyond.com/profile/TheGreatJay/characters/40015014), I get the following stack trace in my console.

  | log | @ | logger.js:70
-- | -- | -- | --
  | error | @ | logger.js:94
  | parseMatch | @ | templateStrings.js:84
  | (anonymous) | @ | templateStrings.js:209
  | parseTemplateString | @ | templateStrings.js:205
  | getDescription | @ | actions.js:138
  | (anonymous) | @ | actions.js:393
  | getOtherActions | @ | actions.js:386
  | parseActions | @ | actions.js:414
  | parseJson | @ | character.js:22
  | (anonymous) | @ | import.js:156
  | Promise.then (async) |   |  
  | (anonymous) | @ | import.js:149
  | getCharacterData | @ | import.js:135
  | (anonymous) | @ | import.js:493
  | dispatch | @ | jquery.min.js:2
  | v.handle | @ | jquery.min.js:2

In this case, the import does eventually finish, and seems to have all the inventory, spells, etc, however this error still happens the same as in the old module. I have tried using both the URL linked to above, as well as the URL from the character-service and they both have the same error.

Again, it doesn't seem to actually affect anything, but I also haven't looked deep enough to truly figure that out yet.

Looking at the source of where the error happens, looks like it's related to not finding a class/subclass.

```js
 if (result.includes("classlevel")) {
    const cls = utils.findClassByFeatureId(ddb, feature.componentId);
    if (cls) {
      result = result.replace("classlevel", cls.level);
    } else {
      // still not found a cls? could be an option
      const classOption = [ddb.character.options.race, ddb.character.options.class, ddb.character.options.feat]
        .flat()
        .find((option) => option.definition.id === feature.componentId);
      if (!classOption) {
        logger.error("Unable to parse option class info, please log a bug report");
      } else {
        const optionCls = utils.findClassByFeatureId(ddb, classOption.componentId);
        if (optionCls) {
          result = result.replace("classlevel", optionCls.level);
        } else {
          logger.error("Unable to parse option class info, please log a bug report");
        }
      }
    }
  }
```

This character is using the 'new' subclass for Circle of the Spores from Tasha's, so perhaps it has something to do with that subclass not existing in the data I have in my system.

Again, things do seem to have been imported correctly eventually, but just wanted to bring this to your attention, as the log specifically tells me to file a bug report :)

**Comment by MrPrimate** [comment]
Ah yes, thanks, this is a known bug, they have only partially implemented some Tasha's features. It should start working once they roll out better support!

**Comment by MrPrimate** [comment]
Resolved now!
