### ISSUE TITLE
Silence spell breaks upon cast / import

### ISSUE THREAD

**Issue by RexxDM** [MrPrimate/ddb-importer#332]
**Describe the bug**
The Silence spell breaks when it is cast and the template hits the Source Actor + 2 More Actors. It does not happen if the Source actor is not within the template, nor if it hits only the source actor or the source actor+ 1 more actor. It's seemingly only when it hits Source Actor + 2 (or more)

**To Reproduce**
1. Bring out the Silence Spell from the DDB Spell list and add it to an Actor.
2. Click on the Silence Spell to cast it.
3. Ensure it hits Source Actor + 2 or more other Actors.
4: The deafened effect and concentration that should remain active is instantly removed.

**Expected behavior**
Expected behavior is for the spell to place a template which lasts while the source actor holds concentration. All actors within the template is expected to be deafened.

**Screenshots**
![image](https://github.com/MrPrimate/ddb-importer/assets/134309842/09c941fb-da5d-4178-9a9f-15a955a7db62)

**Environment:**
 - Foundry Client.
 - Foundry Version 10 - Build 291
 - 5e System Version 2.1.5
 - DDB Version 3.4.22
 - Sequencer Version 3.0.8
 - Does this behavior occur with other modules disabled: Having run FTC twice it once told me Template Macro was the issue - Which it was not as when back with modules on besides that one; the same error still occurred. Trying again it listed of that the issue likely lies with any of the modules that Midi works with.

**Additional context**
I already asked over in the Sequencer channel on the JB2A Discord (Seen as the error clearly points to Sequencer) but they told me that most likely the spell "breaks upon being imported"

Details of any errors in the browser console (press F12): Besides the screenshot already posted above, I can extend the error to show this. (The second screenshot carries on from where the first one ends)
![image](https://github.com/MrPrimate/ddb-importer/assets/134309842/6040174d-7db3-402d-ba19-41d08a54a832)
![image](https://github.com/MrPrimate/ddb-importer/assets/134309842/032bd4b1-377e-4c49-8ee5-57aed86a09ce)

**Comment by MrPrimate** [comment]
DDB Importer does not any sequencer or Animations to silence spell.

**Comment by MrPrimate** [comment]
I couldn't replicate this with the same, error, but did manage to get an error, which I think could be related when the spell was cast on a dozen or so (without Automated Animations enabled).

This is I believe a race condition between midi-qol and ActiveAuras. ActiveAuras v0.6.2 should fix this.

**Comment by RexxDM** [comment]
Going back and having tested just now: It does indeed seem to be fixed. Sorry for not being able to be "more specific" on the matter so it would have been easier to identify the issue.
