### ISSUE TITLE
Duergar Warlord Fixes

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#334]
Duergar Warlord Core Fixes:
1.  Psychic-Attuned Hammer is missing its additional damage formula of `1d10[psychic]`  Your call if you think psychic damage should benefit from enlarge.  RAW I think yes.  
2.  He's missing Plate Armor(maybe this is my bad import I dunno. ) 

Midi/Auto Effects:  
1. Same as Core
2. Same as Core

CPR can actually handle a few of the features on him but we'll have to wait for Chris to get to it as its just a matter of expanding his existing Duergar blueprint to the rest of them.

**Comment by MotoMoto1234** [comment]
I think we also discovered a parse fail as well.  On all of the Duergar.  The Invisibility feature is missing its 1/1 short rest.  I haven't tracked down all of them yet but I'm seeing it.  Its missing from the description of the invisibility item as well fwiw so that might be why theres a parse fail.

**Comment by MrPrimate** [comment]
Plate and extra damage fixed in next release. The invisibility recharge works/parses correctly for me....
