### ISSUE TITLE
War Priest Monster Fix

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#335]
Core fixes:
1. Add Icon image to Holy Fire: `icons/magic/light/beam-rays-red-large.webp` (or whatever you want)
2. Holy Fire's save is set to flat, when it should be derived from wisdom
3. Healing Light is missing an Action Type, once you assign Healing the item is already setup with the rest.  

Midi/Auto Effects:
1. Same as Core
2. Same as Core
3. Same as core
4.  Here is the link to the item Holy Fire with the description taken out:  (Tposney's discord link)
https://discord.com/channels/915186263609454632/1112123052545810563/1112123052545810563

**Comment by MrPrimate** [comment]
Healing light detection and new image added in next release, closing issue, flat dc will be addressed elsewhere.
