### ISSUE TITLE
Error when uploading a character with a buff that increase temporary Max hp

### ISSUE THREAD

**Issue by matthewbstroud** [MrPrimate/ddb-importer#336]
**Describe the bug**

**To Reproduce**

1. Add 5 to the temporary max hp of a character (either directly or via an effect)
2. Attempt to update DnDBeyond through the ddbi.
3. You will get an error.

It doesn't matter if you uncheck HP in the updates.  Still get the same error.

**Expected behavior**
DNDB also has a temp max.  Seems they are stored differently.

**Screenshots**
![Plus_five_to_max_hp](https://github.com/MrPrimate/ddb-importer/assets/17620888/a137ac1f-fe2d-40b2-a985-9047414fb929)
![error_message](https://github.com/MrPrimate/ddb-importer/assets/17620888/641fd497-4deb-4186-bd33-3027457a4ec7)

**Environment:**
 - Edge
 - Foundry Version 10.291
 - 5e System Version 2.1.5
 - Module Version 3.4.24
 - Does this behaviour occur with other modules disabled: Yes/No (Find The Culprit module can help with this) Yes

**Comment by MrPrimate** [comment]
Thanks for the report - I'm away for the week and don't have my full toolset with me so won't be able to take a look at this till next week.

**Comment by MrPrimate** [comment]
This is fixed in the next version, sorry it took a while to get to the bottom of!

**Comment by matthewbstroud** [comment]
Np, I have been out of town on vacation.
