### ISSUE TITLE
Fey-touched spells not prepared

### ISSUE THREAD

**Issue by elzibubble** [MrPrimate/ddb-importer#338]
**Describe the bug**
Spells learned with the Fey-touched feat may be cast once and then also cast with spell slots. This latter part is the problem, they don't show up in my Prepared filter. I always want this enabled as I have cleric levels.

**To Reproduce**
Import a character with the Fey-Touched feat, mine is Clr1/Wiz4.
Check the spellbook, the spells are listed as "At-will".

**Expected behavior**
I believe they should be "Always prepared" instead, retaining the free use.

**Additional context**
My character: https://www.dndbeyond.com/characters/96808788

**Comment by lxsli** [comment]
This will also affect Shadow-touched I imagine, though I haven't tested that.

**Comment by MrPrimate** [comment]
This is partially due to how they are coded in DDB - they are only after to the spell list as single use spells, not to the prepared list.

**Comment by MrPrimate** [comment]
Resolved in 3.4.58, out later today.
