### ISSUE TITLE
Auto Effects: Carrion Crawler

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#342]
I added the overtime effect of the Tentacles Attack and added paralyzed/poisoned to the effect.  I used the macro.CE keys for applying them so that this ability would synergize well with CPR.  You can grab it here(Tposney's discord): https://discord.com/channels/915186263609454632/1113734249867137086/1113734249867137086

**Comment by MrPrimate** [comment]
I have kinda done this - I've added an extra feature into the midi effect generator to detect save at start/end of turns to add an appropriate overtime effect. Tentacles also now will add a Paralyzed condition.
