### ISSUE TITLE
Auto Effects: Steady Aim Rogue feature

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#345]
Active Effect:
     Steady Aim:
          Details: 
               Effects do not stack by NAME
          Duration: 
               Do not fill in any duration(clear the 1 turn) let the dae transfer 1 turn in on its own from item details
     Steady Aim: Movement Restriction:
          Details:
               Effects do not stack by NAME
          Duration:
               Effect Duration(seconds): 12 seconds(this is just to prevent it wearing off too early)
               Effect Duration(turns): 2 rounds(this is just to prevent it wearing off too early)

**Comment by MrPrimate** [comment]
Thanks!
