### ISSUE TITLE
Monster: Dark Tide Knight - Uncanny Dodge Automation

### ISSUE THREAD

**Issue by TysonCodes** [MrPrimate/ddb-importer#349]
When munching https://www.dndbeyond.com/monsters/17446-dark-tide-knight the Uncanny Dodge reaction lacks automation effects that exist when munching a player character (rogue) with the same ability.

This is the munched monster version:
![image](https://github.com/MrPrimate/ddb-importer/assets/18636994/49e978b4-3b97-43c0-b811-15e3467699bc)

This is the munched character version:
![image](https://github.com/MrPrimate/ddb-importer/assets/18636994/f63bf65b-6f2e-416d-9e86-5653b21b8917)
![image](https://github.com/MrPrimate/ddb-importer/assets/18636994/313a6d4a-47f6-419a-a0ea-1a5a826d6d52)
![image](https://github.com/MrPrimate/ddb-importer/assets/18636994/27c11ed2-7a66-4625-8108-935634fd20a4)

If I drag the character version to the monster then Midi-QOL properly halves damage if I use the reaction when prompted for the monster.

**Comment by MrPrimate** [comment]
Thanks. In next release.
