### ISSUE TITLE
Rods import as the wrong type

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#350]
All the Rods are importing as trinkets.  Dnd5e has an item type for rods, its under Consumable for some reason.  Its actually better for Auto effects too if Rods are imported as Consumable\Rod.  This is sorta tied to that annoying Item sheet change in 2.2.1.  Tim's only adding the feet unit field to certain item sheet types and "Trinkets" are not getting that fix, but also trinkets don't get the midi flags at the bottom of the sheet either.  So you really should want to change rods to Consumable\Rod types.

**Comment by MrPrimate** [comment]
Fixed in next version.
