### ISSUE TITLE
Monster: Venom Troll

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#351]
Auto effects only changes:
I have created an auto effects version of the Venom Troll from Monsters of the Multiverse, you can find the 3 changed items on the actor in Tposney's discord here:  https://discord.com/channels/915186263609454632/1117295220212650104/1117295220212650104

Regeneration has an overtime effect and the roll is tweaked to whisper so it doesn't spoil
Venom Spray has had an overtime setup on it, and the actor damages itself when it uses it.
Poison Splash fires anytime the creature takes damage that is not psychic, it will target and damage anyone within 5ft ignoring self.

**Comment by MrPrimate** [comment]
Thanks, in next release
