### ISSUE TITLE
Glamour Bard: Mantle of Inspiration

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#353]
For both normal and auto effects, the damage type is not set for the temp hp formula.  Change `None` to temphp on the item details.  If you are interested in an on use macro that prevents targetting more than their proficiency bonus, I added an on use macro to my own version and shared it here:  https://discord.com/channels/915186263609454632/1118391633814233099/1118391633814233099  its not perfect though as Mantle of Inspiration is probably possibly better done by giving the targets a warpgate crosshair to move their tokens if they choose, but thats beyond me.

**Comment by MrPrimate** [comment]
I have added a slightly adjusted version of your macro!
