### ISSUE TITLE
Error whilst importing spells and creating active effects

### ISSUE THREAD

**Issue by berrfott** [MrPrimate/ddb-importer#356]
**Describe the bug**
Get error when trying to munch spells and creating active effects. "TypeError: Failed to fetch". Muncher stops.

**To Reproduce**
1. Open spell muncher
2. Click on Spells, and checkmark "Create active effects."
3. Click "Spell Munch"

**Expected behavior**
I expected the muncher to start and finish and finding the spells in the compendium. The muncher starts, but stops with an error in the console (DDB Importer | ERR > TypeError: Failed to fetch). No spells are created in the compendium-folder.

**Screenshots**
![screenshot_ddb_importer](https://github.com/MrPrimate/ddb-importer/assets/18735909/ec0e1bd8-efb8-4c6f-ad0a-68f5ab8fa09b)

**Environment:**
 - Browser Edge
 - Foundry Version 11.299
 - 5e System Version 2.2.1
 - Module Version 3.4.33

**Additional context**
In the end of the json-debug-file this line repeats multiple times (other spells only have one line): {"level":"DEBUG","data":["Getting macro for spell confusion.js"]},
The next spell on the list is: {"level":"DEBUG","data":["Adding effects to Summon Lesser Demons"]}, but it seems like the muncher stops before macro is made for this one.

**Error in F12 console**
logger.js:83  DDB Importer | ERR > TypeError: Failed to fetch
log @ logger.js:83
error @ logger.js:124
parseSpells @ DDBMuncher.js:274

logger.js:83  DDB Importer | ERR > TypeError: Failed to fetch
    at loadMacroFile (https://foundryv11.mydomain.com/modules/ddb-importer/dist/main.js:5683:28)
    at async fleshtoStoneEffect (https://foundryv11.mydomain.com/modules/ddb-importer/dist/main.js:9803:25)
    at async spellEffectAdjustment (https://foundryv11.mydomain.com/modules/ddb-importer/dist/main.js:11884:18)
    at async parseSpell (https://foundryv11.mydomain.com/modules/ddb-importer/dist/main.js:34550:5)
    at async Promise.all (index 2754)
    at async getSpells (https://foundryv11.mydomain.com/modules/ddb-importer/dist/main.js:23342:15)
    at async parseSpells (https://foundryv11.mydomain.com/modules/ddb-importer/dist/main.js:23497:21)
    at async DDBMuncher.parseSpells (https://foundryv11.mydomain.com/modules/ddb-importer/dist/main.js:2320:7)
log @ logger.js:83
error @ logger.js:124
parseSpells @ DDBMuncher.js:275

**Comment by MrPrimate** [comment]
Are you able to load the file https://foundryv11.mydomain.com/modules/ddb-importer/macros/spells/fleshtoStone.js

**Comment by berrfott** [comment]
> Are you able to load the file https://foundryv11.mydomain.com/modules/ddb-importer/macros/spells/fleshtoStone.js

Yes. Here is the content of that file.

```if (!game.modules.get("dfreds-convenient-effects")?.active) { ui.notifications.error("Please enable the CE module"); return; } const lastArg = args[args.length - 1]; const tokenOrActor = await fromUuid(lastArg.actorUuid); const targetActor = tokenOrActor.actor ? tokenOrActor.actor : tokenOrActor; const DAEItem = lastArg.efData.flags.dae.itemData; const saveData = DAEItem.system.save; function effectAppliedAndActive(conditionName) { return targetActor.effects.some( (activeEffect) => activeEffect?.flags?.isConvenient && (activeEffect?.name ?? activeEffect?.label) == conditionName && !activeEffect?.disabled ); } if (args[0] === "on") { await DAE.setFlag(targetActor, "fleshToStoneSpell", { successes: 0, failures: 1, rounds: 1, }); } async function checkPetrification(flag) { const flavor = `${CONFIG.DND5E.abilities[saveData.ability]} DC${saveData.dc} ${DAEItem?.name || ""}`; const saveRoll = await targetActor.rollAbilitySave(saveData.ability, { flavor, fastForward: true }); if (saveRoll.total < saveData.dc) { flag.failures += 1; await DAE.setFlag(targetActor, "fleshToStoneSpell", flag); if (flag.failures === 3) { ChatMessage.create({ content: `Flesh To Stone on ${targetActor.name} is complete` }); if (!effectAppliedAndActive("Petrified")) { await game.dfreds.effectInterface.addEffect({ effectName: "Petrified", uuid: targetActor.uuid }); } } else { console.log(`Flesh To Stone failures increments to ${flag.failures} and ${flag.successes}`); } } else if (saveRoll.total >= saveData.dc) { flag.successes += 1; await DAE.setFlag(targetActor, "fleshToStoneSpell", flag); if (flag.successes === 3) { ChatMessage.create({ content: `Flesh To Stone on ${targetActor.name} ends` }); await targetActor.deleteEmbeddedDocuments("ActiveEffect", [lastArg.effectId]); } else { console.log(`Flesh To Stone failures increments to ${flag.failures} and ${flag.successes}`); } } } if (args[0] === "each") { let flag = DAE.getFlag(targetActor, "fleshToStoneSpell"); flag.rounds += 1; if (flag.failures === 3) { await DAE.setFlag(targetActor, "fleshToStoneSpell", flag); } else { await checkPetrification(flag); } } if (args[0] === "off") { ChatMessage.create({ content: `Flesh to stone ends, if concentration was maintained for the entire duration, the creature (${targetActor.name}) is turned to stone until the effect is removed.`, }); const flag = await DAE.getFlag(targetActor, "fleshToStoneSpell"); if (flag && flag.rounds < 10) { if (effectAppliedAndActive("Petrified")) { game.dfreds.effectInterface.removeEffect({ effectName: "Petrified", uuid: targetActor.uuid }); } } await DAE.unsetFlag(targetActor, "fleshToStoneSpell"); }```

**Comment by berrfott** [comment]
Extra info: Foundry VTT is installed as a Docker container running behind Nginx, but no issue running sessions on LAN or WAN.

**Comment by MrPrimate** [comment]
Please update Foundry to v11.302 and DDB Importer to v3.4.34 and try again.

**Comment by berrfott** [comment]
Updating Foundry to v11.302 and DDB Importer to v3.4.34 worked like a charm. Sorry if I should have tried Foundry v11.301 before posting bug ;)
![screenshot_muncher](https://github.com/MrPrimate/ddb-importer/assets/18735909/1fae6d5c-0a9d-4733-acc9-3e3400afcff9)
