### ISSUE TITLE
Monster import: incorrect skill bonuses

### ISSUE THREAD

**Issue by ejrinkus** [MrPrimate/ddb-importer#357]
**Describe the bug**
Monsters don't get imported with skill expertise correctly.

D&D doesn't specify expertise explicitly in the monster stat blocks, but often times the explicit bonuses that monsters will have in their stat block is actually double-proficiency.  As an example, the Scout stat block has bonuses in Nature, Perception, Stealth, and Survival.  And these bonuses are equivalent to the monster having expertise in those skills.

However, when imported into Foundry from DDB, the monsters only have regular proficiency in these skills, resulting in a smaller bonus than they should have.

**To Reproduce**
1. Open an adventure in Foundry that has the DDB Importer module enabled.
2. Click on the Compendium tab.
3. Click on the DDB Muncher button.
4. Click on the Monsters tab in the popup that appears.
5. Leave all checkboxes at their default settings.
6. Click the Monster Munch button, and wait for the import to complete.
7. In the compendium, open the DDB Monsters folder and find a monster that has double-proficiency bonuses on its skills (e.g. the Scout).
8. Open the monster, and observe that they only have regular proficiency in those skills.

**Expected behavior**
Monsters should have the correct bonuses in their skills based on their stat blocks in D&D Beyond.

**Screenshots**
<img width="454" alt="image" src="https://github.com/MrPrimate/ddb-importer/assets/2413883/7fa45f3f-0ba9-4ac5-a835-f4d44dff5012">

Note that in the screenshot above, the icons next to the Nature, Perception, Stealth, and Survival skills are single-checkmarks, whereas they should be double-checkmarks to indicate expertise.  Additionally, the bonuses should be +4, +5, +6, +5 respectively.

**Environment:**
 - Browser: Chrome
 - Foundry Version: 10.291
 - 5e System Version: 2.2.1
 - Module Version: 3.4.33
 - Does this behaviour occur with other modules disabled: N/A, hard to do repeated testing against module combos given the nature of the bug appears to be an issue with how content is imported.

**Additional context**
Given I wasn't able to try and test this against different module combinations, here's a list of the modules I _do_ have activated (other than the importer) in case the list is helpful at all:

- Advanced Macros (1.19.6)
- Ambient Doors (2.3.3)
- Beyond20 Companion Module (1.5.2)
- Characters Action List dnd5e (6.0.4)
- Compact DnDBeyond 5e Character Sheet (0.21.1)
- Death House Map Pack (1.0.0)
- Dice So Nice! (4.6.8)
- Dice Tray (1.5.3)
- Entice with Dice So Nice (0.1.0)
- Forien's Quest Log (0.7.11)
- FXMaster (3.6.0)
- Game-icons.net (0.0.26)
- libWrapper (1.12.12.1)
- Lordu's Custom Dice for Dice So Nice (0.39)
- Monk's Active Tile Triggers (10.21)
- Monk's Token Bar (10.12)
- Multilevel Tokens (1.6.0)
- Nice more Dice (1.2.0)
- PopOut! (2.13)
- Simple Calendar (2.2.0)
- socketlib (1.0.13)
- Token Variant Art (4.41.2)
- Wall Height (4.9.6)

**Comment by MrPrimate** [comment]
These do import for me with the skill bonuses correct, and expertise applied. This is almost certainly a module conflict, which is why we ask to try without other modules enabled.

Please try deleting the monster in the compendium, and reporting it from scratch using the filter box to select "scout".

**Comment by MrPrimate** [comment]
Okay, I think there is an issue when monsters are imported by adventure muncher rather than using the monster muncher due to  slight formatting differences, I'll push an update later today with a fix

**Comment by MrPrimate** [comment]
Fixed in v3.4.36

**Comment by ejrinkus** [comment]
Thanks for the quick fix!  Apologies, I completely forgot that I had originally imported the monsters via the adventure muncher, glad you were able to find the issue.  I'll get my module updated.
