### ISSUE TITLE
Character input hangs, does not progress beyond "Getting Character data"

### ISSUE THREAD

**Issue by CKarper** [MrPrimate/ddb-importer#359]
**Describe the bug**
Unable to import characters from D&D Beyond.

**To Reproduce**
1. Double click token to open character sheet
2. Click on 'D&D Beyond` button to the left of the character name
3. Press the `Start Import` button in the DDB Importer dialog.
4. Press `Default` on the resource importer dialog, as needed.
4. See import status as "Getting Character data", and it never progresses

**Expected behavior**
I expected the character import to progress through all the stages and eventually close.

**Screenshots**
![image](https://github.com/MrPrimate/ddb-importer/assets/653156/ac16c287-2f72-46a3-8ad1-5437ac14e45e)
![image](https://github.com/MrPrimate/ddb-importer/assets/653156/951e5f61-4295-4ddd-8a8b-e4bac7b59133)

**Environment:**
 - __Browser:__ Chrome v114.0.5735.134 (Official Build) (64-bit)
 - __Foundry Version:__ 11 Stable, Build 299
 - __5e System Version:__ 2.2.1
 - __Module Version:__ 3.4.36
 - __Does this behaviour occur with other modules disabled:__ Yes. This is currently the only module enabled.
 - __Valid Cobalt Key:__ Yes, verified in console that it is valid.
 
**Additional context**
The `POST` call to `https://proxy.ddb.mrprimate.co.uk/proxy/v5/character` does complete with a 200 status, and contains reasonable values which I can't share since it contains my cobalt key, but it looks like that part is working.

 - A Character URL, if the problem is a character import.
 https://www.dndbeyond.com/characters/57413403
 
 - Details of any errors in the browser console (press F12).
No errors:
![image](https://github.com/MrPrimate/ddb-importer/assets/653156/590bf63d-0f9d-4c6e-88e5-b146fcfde95c)

**Comment by MrPrimate** [comment]
Please update to Foundry v11.302, earlier versions have too many compendium bugs which cause DDB Importer to fail in fun and interesting ways

**Comment by CKarper** [comment]
That was it.  Thought I was updated, but I had a docker caching issue.  Thanks so much!
