### ISSUE TITLE
Better error handling of unset data directory

### ISSUE THREAD

**Issue by MaxGabriel** [MrPrimate/ddb-importer#36]
Currently, if you do an import without setting the data directory in settings, you'll get this error in the UI:

![image](https://user-images.githubusercontent.com/1274145/101301415-c02bfe80-3806-11eb-8d51-e6ae1b8a22cc.png)

You'll also get a slightly better error saying a directory doesn't exist I believe, a temporary one at the top of the window.

This seems to cause people confusion; I answered someone's question about it here:

https://www.reddit.com/r/FoundryVTT/comments/k5f88f/dd_beyond_importer_error_type_error_cannot_read/geg5hdv/?context=3

You can also see in a recent YouTube video, the speaker calls this error out with the fix for it https://www.youtube.com/watch?v=9PjPkugkF1o

It would be nice if there was explicit error handling for it, with some clear error message.

**Comment by MrPrimate** [comment]
Thanks, I'll get something into the next release
