### ISSUE TITLE
Monster: Deathlock Mastermind(Auto Effects)

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#361]
If there is any confusion about the changes you can find the item import here:  
https://discord.com/channels/915186263609454632/1121737930206085142/1121737930206085142
```
Grave Bolt:
  Item Details Tab:
    Duration: 1 minute
  Effects Tab: Grave Bolt Effect
    Details Tab:
      Stackable: Effects do not stack by NAME
    Effects Tab:
      Attribute Key: flags.midi-qol.OverTime
        Change Mode: Override
          Effect Value: turn=end, saveAbility=str, saveDC=16, saveMagic=true, actionSave=true, label=Grave Bolt
      Attribute Key: macro.CE
        Change Mode: Custom
          Effect Value: Restrained
```

**Comment by MrPrimate** [comment]
`actionSave` must be new since I last looked, I have added a generic actionsave parser to try and detect if a monster action has an action save overtime effect.

**Comment by MotoMoto1234** [comment]
> `actionSave` must be new since I last looked, I have added a generic actionsave parser to try and detect if a monster action has an action save overtime effect.

I keep a cheat sheet to share to the other midi users over in Tposney's discord.  Theres a few new ones, most noteably rollMode.  Which is a great thing to add to regenerations.  

https://github.com/MotoMoto1234/Midi-Wiki/wiki/Overtime-Cheat-Sheet
