### ISSUE TITLE
Item: Ring of Protection(Auto Effects)

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#362]
This item has 2 active effects present on the item.  Both are set to....Stackable: Effects do not stack by origin.  This should be changed on both effects to "Effects do not stack by NAME".  Per the change to midi/dae checking this now, it checks that two effects have the same origin and kills them both.  This may affect DAE users who aren't auto effects users too so probably should check both versions of the item.

**Comment by MotoMoto1234** [comment]
Cloak of Protection also has this problem.

**Comment by MrPrimate** [comment]
This should be fixed in the last couple of versions of DDB Importer - all effects should be coming in as none name rather than none for their stacking option now

**Comment by MotoMoto1234** [comment]
This is what I get for volunteering to report the bug for someone else lol.
