### ISSUE TITLE
School of Enchantment: Hypnotic Gaze

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#363]
I have an automation for this but its using modules you don't include in your auto effects list.  You can look at it here if you wanna see it:  

https://discord.com/channels/915186263609454632/1123146003458035783/1123146003458035783

However, the reason for the issue report is that this item fools the parser:

```
Item:
  Hypnotic Gaze
    Item Details:
      Limited Uses: Blank of Blank per Blank(its parsed wrong by importer)
      Resource Consumption: Blank/Blank/Blank(It does not have a resource recovery, its fooling the parser with bad wording)
```

The item doesn't actually have a cooldown generally, it just can't be used on the target again till yada yada happens.  So its not really possible to show this in an items details.

**Comment by MrPrimate** [comment]
Fixed in next release.
