### ISSUE TITLE
Still issues with Temp HP

### ISSUE THREAD

**Issue by matthewbstroud** [MrPrimate/ddb-importer#364]
**Describe the bug**
Cast an effect that aids temp max hp, like Aid.  Try to update DnDBeyonds.

**To Reproduce**
1. Cast Aid on your player, or add to their temp _max_ hp.
2. Open DND Beyond importer and choose Update DND Beyond.
3. Click Update DNDB with changes.

**Expected behavior**
Update should work.

**Screenshots**
![image](https://github.com/MrPrimate/ddb-importer/assets/17620888/bb5a8d36-1b76-4ad9-928b-7fa2e3897cc4)

**Environment:**
 - Chrome
 - Foundry Version 10.291
 - 5e System Version 2.1.5
 - Module Version "3.4.42"

**Comment by MrPrimate** [comment]
I can't replicate this. Can you screen shot the hp section of a character sheet when you try to update?

**Comment by MrPrimate** [comment]
And I guess, is the Aid Spell one which generates active effects, etc?

**Comment by matthewbstroud** [comment]
Yes, I will give you both .

**Comment by matthewbstroud** [comment]
![image](https://github.com/MrPrimate/ddb-importer/assets/17620888/8e38e353-0e09-4b47-81a2-5dafd66f12a2)
[fvtt-Item-aid.zip](https://github.com/MrPrimate/ddb-importer/files/11931711/fvtt-Item-aid.zip)

**Comment by matthewbstroud** [comment]
i included the aid spell.
![image](https://github.com/MrPrimate/ddb-importer/assets/17620888/162de25e-3d1e-480b-aa16-1c0dc42316df)
![image](https://github.com/MrPrimate/ddb-importer/assets/17620888/dc1867cd-d70d-45b0-9863-2001aec8a3ff)

**Comment by matthewbstroud** [comment]
Yeah, my bad, it looks like his current was somehow higher than it should be.
