### ISSUE TITLE
Auto Effects: All Adamantine Armor

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#365]
I personally would include the generic form of the armor too for folks who may utilize it in a similar fashion.  

```
Effect Tab:
    Adamantine Effect:
        Details Tab:
            Transfer on equip: True
        Effects Tab:
            Attribute Key: flags.midi-qol.fail.critical.all
                Change Mode: Custom
                    Effect Value: 1
```
![image](https://github.com/MrPrimate/ddb-importer/assets/116308065/13c10b71-deb8-4c9b-af29-14a5ea4356b6)
![image](https://github.com/MrPrimate/ddb-importer/assets/116308065/7841b524-bcab-4411-903f-da87d6e4a098)

**Comment by MrPrimate** [comment]
Thanks, in the next version
