### ISSUE TITLE
Munched subclass features have the subclass listed as the class in the flags

### ISSUE THREAD

**Issue by kaelad02** [MrPrimate/ddb-importer#367]
**Describe the bug**
I'm writing a macro to organize the Class and Class Features munched into folders. For example, I'd like a folder named Rogue where all the class features go. Then each Rogue subclass would be a subfolder and those subclass features would go there. I noticed there's some data in the flags that make it easier to tell where a feature comes from, specifically `flags.ddbimporter.class` and `flags.ddbimporter.subClass`. On Rogue class features those are exactly what I expected, `Rogue` and `undefined` respectively. But subclass features, like the Thief's Fast Hands feature was `Thief` for both flags. I was hoping it would be `Rogue` then `Thief` so I could use that info to create the folder structure where I created a Rogue folder and then a Thief folder inside it.

Can you fix it so the `class` flag is set to the parent class on subclass features?

**Comment by kaelad02** [comment]
In case it helps, here are the versions:

Foundry v11.305
dnd5e v2.2.2
ddb-importer v3.4.49

**Comment by MrPrimate** [comment]
In v3.4.52
