### ISSUE TITLE
Images cannot be uploaded to server

### ISSUE THREAD

**Issue by Braste** [MrPrimate/ddb-importer#368]
**Describe the bug**
Whenever I try to import anything, the module cannot upload the images and i get an error in the console. I checked the configured directories and I am able to upload pictures manually. I even set wright premissions to everyone.
What I find suspicious is the link it tries to get the image from: https://images.ddb.mrprimate.co.uk/https://www.dndbeyond.com/avatars/35806/815/1581111423-104782081.jpeg?width=150&height=150&fit=crop&quality=95&auto=webp
This does not seem correct.

**To Reproduce**
1. Try to import a character from dndbeyond or use the muncher to import items, spells, etc.

**Expected behavior**
Images are uploaded correctly

**Screenshots**
![image](https://github.com/MrPrimate/ddb-importer/assets/494984/fde2d203-24e4-48e2-aa67-1429fa03ce31)
![image](https://github.com/MrPrimate/ddb-importer/assets/494984/8d4d45bc-6595-4ba6-9661-2217b3718b1c)

**Environment:**
 - Browser chrome
 - Foundry Version 11 Stable
 - 5e System Version 2.2.2
 - Module Version 3.4.52
 - Does this behaviour occur with other modules disabled: Yes
 - A Character URL, if the problem is a character import: https://www.dndbeyond.com/characters/44656683

**Comment by MrPrimate** [comment]
The image path is correct, the importer needs to download images via a CORS proxy due to various internet security things.

Can you open say the character image/token section and manually upload anything to the `[data] dndbeyond` path? It might be that the foundry application itself cannot write to that folder.

**Comment by Braste** [comment]
Already did this "I checked the configured directories and I am able to upload pictures manually." Sorry for the confusion.

**Comment by Braste** [comment]
It seems that since the last time I used foundry my chrome-profile got somehow corrupted. Just tried it with a new one and the upload works. Sorry for the inconvenience.

**Comment by Braste** [comment]
It seems that since the last time I used foundry my chrome-profile got somehow corrupted. Just tried it with a new one and the upload works. Sorry for the inconvenience.

**Comment by Braste** [comment]
It seems that since the last time I used foundry my chrome-profile got somehow corrupted. Just tried it with a new one and the upload works. Sorry for the inconvenience.
