### ISSUE TITLE
Fairy Race Character Import

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#370]
The parser is failing to understand Fairy Magic properly.  Faerie Fire AND Enlarge Reduce should be set as innates AND leveled spells available as always prepared.  Faerie Fire is missing from leveled spells.  

![image](https://github.com/MrPrimate/ddb-importer/assets/116308065/087e8cea-1426-4beb-8511-f86310bc155b)

**Comment by MrPrimate** [comment]
Same issue as #338 and partly due to the way these spells appear in DDB. Closing as tracking elsewhere
