### ISSUE TITLE
Monster: Quasit (auto effects submission)

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#371]
On the claws, I checked the midi flag for full dam save at bottom, then added an active effect for poisoned and an overtime to save it off.  The overtime is:  

```
turn=end,
saveAbility=con,
saveDC=@abilities.con.dc,
label=Poisoned Claws
```  

On scare, The only thing I tweaked from the original was I added magic effect to the flags at bottom and cleaned up the overtime just incase it was buggy, cause theres an errant page return in your version.  You may want to consider checking that on any monster overtimes on items with a "(something something)" in their names.  For some reason the spaces got turned into page returns/line breaks.  Its probably a non issue but I'm OCD and wanted a clean overtime appearance.  The overtime is:

```
turn=end,
label=Scare,
saveRemove=true,
saveDC=@abilities.con.dc,
saveAbility=wis
```

For invisibility, I added an action type of Other, so I could gain access to the bottom third of the item sheet, where I checked the box for "Don't apply CE" and then checked the midi box for "Concentration".  Then I added an active effect.  First tab(details) changes are check the box for always show effect icon.  Second Tab(Duration) set it up with no duration in seconds or turns, instead lean on Times Up here and add 3 special durations, 1 action, 1 spell, 1 attack.  Finally third tab(effects) add the key "macro.CE | Custom | Invisibility".  

If you need a visual guide to what to change I've submitted them in the showcase on posney's discord also, but they have no descriptions there.  

https://discord.com/channels/915186263609454632/1139995478549876737/1139995478549876737

**Comment by MrPrimate** [comment]
Have added claws and invis. I think RAW the Scare effect is not magical, so not going to add that as I think it's more a dm choice.

**Comment by MotoMoto1234** [comment]
The overtime in scare was really weird looking I think theres extra characters in what you put in it and it causes line breaks, not sure if that adversely affects it but I just cleaned up the spaces.  I think its caused by that setting that puts details in the title of an ability in the muncher.

**Comment by MrPrimate** [comment]
> The overtime in scare was really weird looking I think theres extra characters in what you put in it and it causes line breaks, not sure if that adversely affects it but I just cleaned up the spaces. I think its caused by that setting that puts details in the title of an ability in the muncher.

I don't see this

**Comment by MotoMoto1234** [comment]
Disregard, its user error, the dae UI confused me.
