### ISSUE TITLE
Fixes for Misty Step

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#372]
Misty Step needs to have its automated animations flags cleared so they go back to default.  Its munching/importing with a rogue aa flag on it that breaks it so that tokens arrive at their destinations as transparent tokens.  Visually in the UI of misty step you can fix tyis by toggling off your "customize" checkbox in the aa button of the item, and you will see that the misty steps customized to turn the token transparent.  Image Below.  You have a macro in the item but I think its old and you haven't been actually using it anymore right?  AA's teleport preset is pretty solid and you have it required for auto effects anyway.  I already alerted CPR to the issue since they used your item to build theirs off of.  

![image](https://github.com/MrPrimate/ddb-importer/assets/116308065/ed991a10-6742-4189-8010-755d4a56b755)

**Comment by MrPrimate** [comment]
I'm not sure this is my implementation. I do add a simple effect that allows you to teleport to a template position using a macro, but I don't add any AA flags to it. The improper may copy existing `autoanimations` flags on the item when it updates it.

**Comment by MrPrimate** [comment]
I can add a function to not apply this effect if AA is active though

**Comment by MrPrimate** [comment]
In next version.
