### ISSUE TITLE
Items created by Features are lacking Proficiency Bonus

### ISSUE THREAD

**Issue by tartarts** [MrPrimate/ddb-importer#373]
**Describe the bug**
_When using Booming Blade and/or Green Flame Blade Macros, the resulting dialogue fails to add the Proficiency modifier to the attack roll._

**Expected behavior**
_The Attack Roll adds the Proficiency modifier to the final amount._

**Screenshots**
![image](https://github.com/MrPrimate/ddb-importer/assets/114840468/88d555b4-6558-4adb-8ec5-be08e6aea86e)

**Environment:**
 - Opera 101.0.4843.43
 - Foundry Version [11.305]
 - 5e System Version [2.3.0]
 - Does this behaviour occur with other modules disabled: Yes

**Comment by MrPrimate** [comment]
Fixed in latest version
