### ISSUE TITLE
Leonin: Daunting Roar(AutoEffects submission)

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#374]
I took your current munched result and tweaked it to work with midi/dfreds ce/times up.  

**_Important note for non auto effects version:_**  The range is wrong on the item, its 10ft not 5ft.  I mean the original item needed to be fixed so this specific change is for both auto effects and regular item.  

This requires two settings to be right in midi/dfreds to work.  

In Dfreds CE:  Modify Status Effects set to REPLACE

In MidiQOL: Auto Target for ranged target spells/attacks set to anything other than NONE

As always, if you are confused about any of this, you can get a copy of this item without the description in Posney's discord here:  https://discord.com/channels/915186263609454632/1142592621928255540/1142592621928255540

```
Item Details:
    Activation Condition:  !target.effects.some(eff=>eff.label.toLowerCase().includes('deafened'))
    Target: 10 Feet Enemy
    Range: Special
    Duration: Special
    Activation condition true required for effect activation: TRUE
    
Effect:
    Daunting Roar
        Duration Tab:
            Effect duration(seconds): 12
            Effect Duration(Turns): 2 rounds
            Special Durations:
                Turn End: Expires at the end of the source actors next turn(in combat)
                End Combat
        Effects Tab:
            Attribute Key: macro.CE
                Change Mode: Custom
                    Effect Value: Frightened

**Comment by MrPrimate** [comment]
In next version, thanks.
