### ISSUE TITLE
Auto Effects: Spell Silence

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#376]
The spell Silence for auto effects still has the old active auras/advanced macros on use macro in it when it should be changed.  

I personally do this for active auras:

```js
if (args[0].macroPass === "preActiveEffects") {
	return await game.modules.get("ActiveAuras").api.AAHelpers.applyTemplate(args);
}
```
![image](https://github.com/MrPrimate/ddb-importer/assets/116308065/fbb414c1-1ca8-4109-88e4-df3562d48338)

Incase you want a download of the change its submitted to posney's discord as an item showcase here:  https://discord.com/channels/915186263609454632/1144307255911649361/1144307255911649361

**Comment by MotoMoto1234** [comment]
I've been told that the item we recieve for silence in the muncher has the old Item Macro flags and shouldn't.  Apparently they are a lil on the performance degredation side, so if you can remake the item or clear the flag it'd help.  The item I linked in posney's discord has the correct item macro flag in it as I based it off the SRD item instead.

**Comment by MrPrimate** [comment]
The AA and macro work just fine here. Also what do you mean old "item macro flags" ?

**Comment by MotoMoto1234** [comment]
I really need to check my pings here more often.  Elwin said that the flags on the item export of a ddbi item had the old v9 data scheme for item macro which apparently keeps things in memory or something and is inefficient compared to the modern scheme for flag data on the items for item macro.

**Comment by dineshm72** [comment]
I just tried using the DDBI version in v11 and none of the effects were created on anyone in the spell template.

I did remove Advanced Macros, in case that is something that is still required, it might explain why it's no longer working.

**Comment by dineshm72** [comment]
Nope, I am a dummy and just wasn't in combat so AA wasn't firing.
