### ISSUE TITLE
Temporal Awareness adding proficiency to initiative

### ISSUE THREAD

**Issue by ravingdragoon** [MrPrimate/ddb-importer#382]
**Describe the bug**
The Temporal Awareness effect is adding the intelligence modifier, which it should, and the proficiency bonus, which it should not, to the initiative when rolled.

**To Reproduce**
1. Import a level 2 or above Chronurgy Wizard with active effects turned on
2. Roll initiative for them
3. See that it is adding dex + int + proficiency

**Expected behavior**
The effect should only cause the initiative roll to add dex + int

**Screenshots**

**Environment:**
 - Chrome
 - Foundry Version 11.308
 - 5e System Version 2.3.1
 - Module Version 3.4.63
 - Does this behavior occur with other modules disabled: No as it is an issue with importing an active effect

**Additional context**

 - A Character URL, if the problem is a character import.   https://www.dndbeyond.com/characters/70291787

**Comment by MrPrimate** [comment]
Whoops! Thanks, fixed in the next version out later today, or maybe tomorrow.
