### ISSUE TITLE
Auto Effects: (Evard's) Black Tentacles(both of them)

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#383]
The normal version of evards/non evards black tentacles needs to stay as is, but the auto effects one should not be damaging anyone on cast, it does its thing when creatures enter its aoe and when people start their turn.  Thats a nuanced wording but when it is first cast, the victims haven't entered it technically.

**Comment by MrPrimate** [comment]
Thanks, fixed in next release.
