### ISSUE TITLE
Variant human created in DnDBeyond is imported to Foundry and adding Mark of Passage when it shouldn't

### ISSUE THREAD

**Issue by leonfeder** [MrPrimate/ddb-importer#386]
**Describe the bug**
My player create a Forgotten Realms character on DnDBeyond and even though I made sure that "Eberron Content" is not selected there, when I import the PC into Foundary, it adds the Mark of Passage to the character in Foundry (Forge).  This is a Forgotten Realms campaign and that's not allowable. Additionally, I disallowed "Favorite Foe" but the importer set it even though it's not on the DnDBeyond character sheet. The DnDBeyond sheed has "Favorite Enemy" as it should.

**To Reproduce**
1. Create a brand new actor in Foundry.
2. Click on the DnDBeyond button on the actor.
3. Import the following PC: https://www.dndbeyond.com/characters/76571906
4. Start the import (I'll attach configuration screens)
5. 

**Expected behavior**
The Mark of Passage traits should not be added.

**Screenshots**
The process I step through:
![image](https://github.com/MrPrimate/ddb-importer/assets/39753469/8ca3e43c-fc5b-47a9-955f-4f88341bc057)

The configuration:
![image](https://github.com/MrPrimate/ddb-importer/assets/39753469/6f1456b6-8305-41f2-87b2-62820fc9933f)

The result:
![image](https://github.com/MrPrimate/ddb-importer/assets/39753469/5b3c2860-b0c3-452d-ab0c-487d8389aafd)

**Environment:**
 - Version 116.0.5845.187 (Official Build) (64-bit)
 - Foundry Version [10.303]
 - 5e System Version [e.g 2.3.1]
 - Module Version [e.g 3.4.66]
 - Does this behaviour occur with other modules disabled: Yes/No (Really not sure. I started pretty vanilla and slowly added modules but this HAS been a problem)

**Additional context**
None

**Comment by MrPrimate** [comment]
It's adding these because these are custom actions that have been added to the character on DDB, if you don't want them imported, don't add them to the character on DDB.

**Comment by MrPrimate** [comment]
![Screenshot from 2023-09-13 22-30-47](https://github.com/MrPrimate/ddb-importer/assets/3985378/b9c251d4-b5d0-4b9c-bc80-ff0178855354)

**Comment by leonfeder** [comment]
Thanks. The player must've added them. I've removed them.
