### ISSUE TITLE
AutoEffects: All Frightful Presences on Dragons.  

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#387]
On the item details tab:

Target: 120 feet Enemy(Was blank)
Range: self(was something else)
Duration: 1 Minute(Was Instantaneous)

I like to flag these as magical effects cause some magic resistance features say "spells and other magical effects" and I think this is one of those but your call.  

On the active effect:
Make sure its 60 Seconds/10 rounds for the two duration spots

**Comment by MrPrimate** [comment]
In next release, thanks.

**Comment by MotoMoto1234** [comment]
It appears that the target settings for frightful presence never made it into this feature request.  

Frightful Presence on Adult Red Dragon has a target of `120 feet sphere` when in midiqol environments `120 blank enemy` is best for self aoe's since templates don't accoutn for the tokens size.
