### ISSUE TITLE
Way of the Kensei fixes and Auto Effects

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#389]
Magical Kensei Weapons:  I chose `icons/weapons/thrown/daggers-kunai-purple.webp`

Deft Strike:  I chose `icons/skills/melee/strike-spear-red.webp`

Deft Strike should be a unique Optional.name setup, add a transfer on equip active effect to it with the following keys:

`flags.midi-qol.optional.deftStrike.damage.all` OVERRIDE `@scale.monk.martial-arts`
`flags.midi-qol.optional.deftStrike.label` OVERRIDE `Deft Strike`
`flags.midi-qol.optional.deftStrike.count` OVERRIDE `turn`
`flags.midi-qol.optional.deftStrike.countAlt` OVERRIDE `@resources.primary.value`
`flags.midi-qol.optional.deftStrike.criticalDamage` CUSTOM `1`

The last key relies upon Ki being the primary resource which imo is always the case on a monk.  

Here is the shared Deft Strike in Posney's discord:  https://discord.com/channels/915186263609454632/1113409378230489088/1151927289760714842

**Comment by MotoMoto1234** [comment]
I forgot a key for the optional.name

`flags.midi-qol.optional.deftStrike.criticalDamage` CUSTOM `1`

I'll edit it into the OP incase you haven't read this yet.

**Comment by MrPrimate** [comment]
Thanks, this will link to the Ki Pool feature/uses, I'd recommend Link Item and Resource DnD5e to link stuff
