### ISSUE TITLE
Folder Creation

### ISSUE THREAD

**Issue by HippyCraig** [MrPrimate/ddb-importer#39]
On your configuration, where you set the path for images, I used the button to create a new folder.  It looks like it doesn't set the right permissions on the hosting machine local folder when using that.   I went to import a character and got write error messages for adding icons when importing.

I went to my hosting machine, deleted the directory created and recreated it while logged into the machine, and restarted Foundry.  After that I did another import and this time it succeeded.

**Comment by MrPrimate** [comment]
Hey, thanks for the report, I'll look into it!

**Comment by MrPrimate** [comment]
@HippyCraig I assume you are running as a limited user i.e. not root, and not using docker/similar?

**Comment by HippyCraig** [comment]
So Foundry is running in a VM in Azure, full version of windows 10.   I am accessing the site on my local laptop logged in as Game Master when doing the above.  Hope that helps.

**Comment by MrPrimate** [comment]
Ah, okay, this might be more of a foundry problem, as it just uses the foundry system to create folders etc.

I personally run linux on the desktop and on my servers so won't be able to replicate this.

**Comment by HippyCraig** [comment]
Should I move this over to discord for Foundry?  Is there a better place to post this

**Comment by MrPrimate** [comment]
Yeah, Discord Foundry might be a better place to ask
