### ISSUE TITLE
Race: Hadozee size does not import

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#392]
When making a hadozee player race character, the choice of small or medium always imports as medium.

**Comment by MotoMoto1234** [comment]
I also created the "Hadozee Dodge" item in posney's discord if you want to add it to the Auto Effects for this race.  

For the "Hadozee Glide" item, change its reaction type to reaction manual for auto effects.  

https://discord.com/channels/915186263609454632/1153793407899152516/1153793407899152516

**Comment by MrPrimate** [comment]
Size fix in next version

**Comment by MrPrimate** [comment]
Dodge and Glide also added.,Thanks!
