### ISSUE TITLE
Auto Effects: Myconid Adult(and probably sovereign)

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#394]
The ability Pacifying Spores has its item details set to instantaneous when it should be 1 minute.  And to be extra meticulous, in the active effect tab, I'd recommend adding the duration of 10 rounds to the active effect too, it already has the 60 seconds but theres nuanced times where if its not filled out then it doesn't expire right inside of combat that lasts more than 10 rounds.

**Comment by MrPrimate** [comment]
Thanks. I've made some changes that will impact all effects that are similar, so hopefully it will catch others that are like this.
