### ISSUE TITLE
Monster Munch: Wind Javelin icon path different from expected

### ISSUE THREAD

**Issue by T-Whiz** [MrPrimate/ddb-importer#397]
For the Munched monster Storm Giant Quintessent, the "Wind Javelin" action shows a broken link for the icon. It looks like it should be icons/weapons/ammunition/arrowhead-glowing-blue.webp instead of icons/weapons/guns/arrowhead-glowing-blue.webp.

**To Reproduce**
1. Select the DDB Muncher button from the Compendium Sidebar.
2. Go to the Monster Munch tab and either munch the above monster either individually or as part of a larger munch.
 
**Expected behavior**
Icon path of icons/weapons/ammunition/arrowhead-glowing-blue.webp
 
**Screenshots**
Attached screen shots of the item and muncher settings.
[Wind Javelin screen shots.pdf](https://github.com/MrPrimate/ddb-importer/files/12818987/Wind.Javelin.screen.shots.pdf)

**Environment:**
Browser: Edge, Foundry v11.308, dnd5e v2.3.1, DDBI v3.4.74, Hosting: The Forge

 - Details of any errors in the browser console (press F12).
No errors in console.

**Comment by MrPrimate** [comment]
Thankyou, fixed in next release
