### ISSUE TITLE
Monster munch: Monster items contain unexpected uses and recharge details in name

### ISSUE THREAD

**Issue by T-Whiz** [MrPrimate/ddb-importer#398]
**Describe the bug**
After munching with the 'Strip uses and recharge information from action names' selected, some monsters show features/item names containing recharge or uses information instead of being stripped out. Attached the list of those I could identify based on my DDB content, so there could be others.

**To Reproduce**
1. Select the DDB Muncher button from the Compendium Sidebar.
2. Go to the Monster Munch tab and either munch the above monsters either individually or as part of a larger munch.
 
**Expected behavior**
Monster features appear with the corresponding name from DDB, without any recharge or uses details.
 
**Screenshots**
Attached list of the monster features/items and applicable monsters, and screen shots of muncher settings.
[Monster.items.with.unexpected.details.in.name-revised.csv](https://github.com/MrPrimate/ddb-importer/files/12824263/Monster.items.with.unexpected.details.in.name-revised.csv)
[monster munch settings.pdf](https://github.com/MrPrimate/ddb-importer/files/12819360/monster.munch.settings.pdf)

**Environment:**
Browser: Edge, Foundry v11.308, dnd5e v2.3.1, DDBI v3.4.74, Hosting: The Forge

 - Details of any errors in the browser console (press F12).
No errors in console.

**Comment by MrPrimate** [comment]
I have done a handful of these but have admittedly not checked all (it would be super useful to have what the uses/recharge info is in the spreadsheet).

There are a few in the list which don't really make sense to strip out, as the system doesn't do a good job of tracking (such as Spys' 1/turn (there is no native 1/turn).

Please let me know if any remain after your next munch with v3.4.75 release

**Comment by T-Whiz** [comment]
Thanks for taking a look. I agree about the 1/Turn types of items. I updated my attachment with the extra info in the item names. I remunched them all with v3.4.75 and they look as expected except for the following 6 creatures. The Ray of Sickness maybe doesn't need to be changed, but I listed it just in case.
Benign Transportation (Recharges after Jim Casts a Conjuration Spell of 1st Level or Higher), Jim Darkmagic
Fey Step (Recharge 4 – 6), Spring Eladrin, Autumn Eladrin
Poison Prick (Cost 2 Actions), Lichen Lich
Summon Devil (Recharges after 9 Days), Victoro Cassalanter
Ray of Sickness (1st-Level Spell; Requires a Spell Slot), Skull Lasher of Myrkul

**Comment by MrPrimate** [comment]
OKay, Fey Step and Posion Prick have slightly different wording to the standard, so that's an easy fix.

I think I will leave the following three as they are non-standard/nt obvious otherwise.
Benign Transportation (Recharges after Jim Casts a Conjuration Spell of 1st Level or Higher), Jim Darkmagic
Summon Devil (Recharges after 9 Days), Victoro Cassalanter
Ray of Sickness (1st-Level Spell; Requires a Spell Slot), Skull Lasher of Myrkul
