### ISSUE TITLE
Cannot import character sheet | "Cannot set properties of undefined (setting 'type')"

### ISSUE THREAD

**Issue by RealDealDanger** [MrPrimate/ddb-importer#401]
**Describe the bug**
I'm currently trying to import a character into Foundry. This character has been imported before, but once I updated to 3.4.75 I've encountered an error stating that it "Cannot set properties of undefined (setting 'type'). I've turned off all modules and it still shows up. Other characters can be imported just fine and when I try to make a new actor for this sheet, I get the same error. 

I assume this an error with the character sheet itself or data in the world, but any help could be appreciated.

**To Reproduce**
1. Go to the character sheet on DDB and obtain the URL
2. Return to Foundry and go through the process of importing a character with a new actor on
3. Set the settings to the preferred method and click 'Start Import'
4. The Resource Selection will appear, any button click will show the error
5. See the error

**Expected behavior**
As I've stated this character sheet never used to give me issues and I haven't added anything to it since I first imported it into Foundry. I expected the import to go smoothly, but everything I try doesn't help.

**Screenshots**
![DDB Importer Image](https://github.com/MrPrimate/ddb-importer/assets/147213677/fcf2203f-c8fc-447d-b35e-a0ce0cb04763)
![DDB Impoter Image 2](https://github.com/MrPrimate/ddb-importer/assets/147213677/aa9018d2-f464-418b-a571-97afde5f1776)

**Environment:**
 - Chrome
 - Foundry Version 11.311
 - 5e System Version 2.3.1
 - Module Version 3.4.75
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**

 - Here's a link the character sheet:
 https://www.dndbeyond.com/characters/91519651

**Comment by MrPrimate** [comment]
THis is due to the renaming of Waterskin to Waterbottle, and there are some special rules applied to the parsing of Waterskins. A fix is in the next release out this weekend.
