### ISSUE TITLE
Icon-related info

### ISSUE THREAD

**Issue by T-Whiz** [MrPrimate/ddb-importer#405]
I identified some places across monsters, items, and spells where the default mystery man appears as the icon. Hopefully this is useful info. I've added everything in the attached list, along with some potential core icons that could be used.

**Additional context**
[DDBI missing icons.csv](https://github.com/MrPrimate/ddb-importer/files/12839424/DDBI.missing.icons.csv)

**Comment by MrPrimate** [comment]
Thank you for these, this is an incredible amount of work!

**Comment by T-Whiz** [comment]
It looks like a couple are still missing:
Fraz-Urb'luu: Fraz-Urb'luu's Lair - icons/environment/settlement/wizard-castle.webp
Graz'zt: Graz'zt's Lair - icons/environment/settlement/palast.webp
Also I had the wrong one for Ender Pearl, it was supposed to be: icons/commodities/gems/pearl-purple-dark.webp
