### ISSUE TITLE
Monster Parse Fail: Druid(And Fala Lefaliir among others based on druid)

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#407]
The staff on the actors is setup with normal damage, then a second formula for versatile, and then the actual versatile field is already populated.  In Auto effects this would be bad, pretty sure it also would be bad in normal dnd5e.  

![image](https://github.com/MrPrimate/ddb-importer/assets/116308065/e611d3ba-8937-4d5b-8c4b-65ebdda8c0c9)

**Comment by MrPrimate** [comment]
Oh druids use a slightly different set of language for their dual handed stuff, fix in next release/
