### ISSUE TITLE
Some monster ability names different from expected

### ISSUE THREAD

**Issue by T-Whiz** [MrPrimate/ddb-importer#409]
**Describe the bug**
In DDBI 3.4.77 there are still a few monsters with some abilities that aren't parsing out as expected. Below are the ones I could identify. Attached screen shots of examples and also verified with all other modules disabled.

- Eldritch Lich: Spellcasting
- Faerie Dragon (Younger): Euphoria Breath
- Otto: Euphoria Breath
- Fractine: Imprison
- Mythic Actions on applicable creatures, including: Ancient Dragon Turtle, Aspect of Bahamut, Aspect of Tiamat, Black Greatwyrm, Blue Greatwyrm, Brass Greatwyrm, Bronze Greatwyrm, Copper Greatwyrm, Gold Greatwyrm, Green Greatwyrm, Red Greatwyrm, Silver Greatwyrm, White Greatwyrm

**To Reproduce**
Use the Monster Munch with the above monsters, either updating existing or deleting and re-munching the monster.

**Screenshots**
[monster-munch-abilities.pdf](https://github.com/MrPrimate/ddb-importer/files/12862030/monster-munch-abilities.pdf)

**Environment:**
 - Browser [e.g. chrome]: Edge
 - Foundry Version [e.g. 10.288]: 11.313
 - 5e System Version [e.g 2.0.3]: dnd5e 2.1.3
 - Module Version [e.g 3.1.21]: 3.4.77
 - Does this behaviour occur with other modules disabled: Yes

 - Details of any errors in the browser console (press F12).
No errors in console.

**Comment by MrPrimate** [comment]
I have fixed most of these for the next version, but the Faerie Dragon are impossible to parse out correctly
