### ISSUE TITLE
Auto Effects:  Kalashtar Race

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#411]
The feature Mind Link, could honestly be a blank active effect duration 1 hour and be considered automated if you felt like doing a simple one.  Also maybe add Telepathy as a custom language.  Because its range scales I would either just not put a range in the item, I doubt the range field takes scale values.  Make sure you set the item details duration and also set 3600 seconds in the duration tab of the active effect.

**Comment by MrPrimate** [comment]
Thanks, and in new release.
