### ISSUE TITLE
Fighting style: Dueling mistake

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#412]
There is an additional attribute key that doesn't belong on this fighting style feature item.  It should only affect melee weapons yet it has a ranged weapon key in it added in.  

![image](https://github.com/MrPrimate/ddb-importer/assets/116308065/9db33674-586a-426f-ba00-9e405f2d90e8)

**Comment by MrPrimate** [comment]
It looks like the modifier definition used by DDb changed at some point, it will require a bit of rejigged to get this fixed. Might be a few days

**Comment by MrPrimate** [comment]
Fixed in 3.5.4
