### ISSUE TITLE
Race: Kobold(non legacy)

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#415]
**Is your feature request related to a problem? Please describe.**
Just an icon submission to help with CPR integration

**Describe the solution you'd like**
The Kobold non Legacy Race feature Draconic Cry has no icon designated for it, CPR has gone ahead and automated this and its chosen an icon and it'd probably be smart to use their icon so the ae and the item match:  `icons/creatures/magical/spirit-fire-yellow.webp`

**Describe alternatives you've considered**

**Additional context**
If you don't use the suggested icon then CPR users will have an item with mismatched icon with its active effect.  Currently its a bag icon item with the suggested icon for its effect.  Its too bad you can't override and utilize the icons of CPR when applying CPR automations honestly.

**Comment by MrPrimate** [comment]
Fixed.
