### ISSUE TITLE
Race: Kobold(Non Legacy)

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#416]
**Describe the bug**
The feature Kobold Legacy: Defiance parses poorly and labels itself weirdly, you should trim the name properly

**To Reproduce**
1. Import a non legacy Kobold race character and choose Defiance for the Kobold Legacy Feature

**Expected behavior**
I think the bad name is self explanatory when you see the screenshot

**Screenshots**
![image](https://github.com/MrPrimate/ddb-importer/assets/116308065/794734b9-01ed-4858-8cc6-c9a15b207a70)

**Environment:**
Pretty sure this stuff is N/A

**Additional context**
Found while updating the midi wiki

**Comment by MrPrimate** [comment]
Thanks, this is a rare case where the choice already has the feature name in it, I shall adjust the logic.
