### ISSUE TITLE
Character Importer: Song of Rest

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#417]
**Describe the bug**
Song of Rest, with auto effects enabled, needs an `activation cost` set in the item details, and then also an `action type`.  **Additionally, in auto effects, its damage flavor should be "No Damage" as its currently set to "None" which in midi means pure damage**.  I wouldn't worry about applying a healing flavor to this, its more of a theater of the mind heal and can't really be automated efficiently, it just needs the above 3 fixes.  

**To Reproduce**
1. Import a level 2+ bard into a game with all the auto effect modules/settings enabled.  Then edit song of rest and it should present itself.  

**Expected behavior**
When activation cost and action type are not populated the item sheet hides stuff, and when you deal None damage its pure damage in midi.  No Damage is the proper choice.  I changed a few other things but they are cosmetic or for modules you don't require so no need to adjust.  

**Screenshots**
![image](https://github.com/MrPrimate/ddb-importer/assets/116308065/542a19df-532c-46b0-aef8-472d06a4babb)

**Environment:**
Probably n/a

**Additional context**
probably n/a

**Comment by MrPrimate** [comment]
Thanks
