### ISSUE TITLE
Loxodon: Trunk change

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#419]
**Is your feature request related to a problem? Please describe.**
I think it'd be a really funny and cool thing to make the feature for Trunk on the Loxodon just be a reskinned additional Unarmed Strike using its icon image.  Cause in the features description it says you can use it to make an unarmed strike.  Right now its just a basic passive feature with a description.  

**Describe the solution you'd like**
Just Clone your typical character imported Unarmed Strike and slap the passive feature's description onto it.  

**Describe alternatives you've considered**
N/a

**Additional context**
https://www.dndbeyond.com/races/67607-loxodon#LoxodonTraits

**Comment by MrPrimate** [comment]
Nice!
