### ISSUE TITLE
Race: Plasmoid(Auto Effects)

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#420]
The "Hold Breath" racial feature could be a really really simple basic active effect self transfer.  No boxes checked in first tab of ae, and have the item have target/range of self/self and a duration of 1 hour.

**Comment by MrPrimate** [comment]
THanks

**Comment by MotoMoto1234** [comment]
> THanks

OH, I missed a step, check the box at the bottom of the item details for "Toggle Effect" for them to easily turn on and off hold breath by rolling the item.
