### ISSUE TITLE
"Sleep" targets actors invulnerable to its effect

### ISSUE THREAD

**Issue by joshuanestler** [MrPrimate/ddb-importer#423]
**Describe the bug**
Sleep spell does target actors immune to its effects.
In our case our Elf (who has the "Fey Ancestry" race feature and hereby cannot be targeted by sleeping spells) was put to sleep by the automation of the "Sleep" spell (https://github.com/MrPrimate/ddb-importer/blob/3.5.6/macros/spells/sleep.js).

It would be nice if the spell would check for "Fey Ancestry" as race features or anything that encases that and anything that is not already checked. (I've seen that the macro checks for "construct" and "undead" race, and have hacked around for it to include "elf", but as we are beginners to DnD, I am not certain if that mitigates all problems causing this)

**To Reproduce**
1. Cast the spell with an elf (with the "Fey Ancestry" feature) with sufficient low HP in the radius.

**Expected behavior**
Any actor with the "Fey Ancestry" or similar perks should be unable to be affected by this spell.

**Environment:**
 - Firefox 119.0 / Chromium 114.0.5735.289, Electron 25.9.1 (https://github.com/theripper93/fvtt-player-client/releases/tag/1.4.3)
 - Foundry Version 11.314
 - 5e System Version 2.3.1
 - Module Version 3.5.6

**Comment by MrPrimate** [comment]
Some improvements in the next version, will check for elf and half-elf and also character import will add `Sleep` as an immunity to those characters with fey ancestry which the Macro already checks for.
