### ISSUE TITLE
Monster: Rahadin(Auto Effects submission)

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#424]
I've automated his Mask of the Wild with a very simple midi on use macro.  Here is the tposney discord link to it.  Don't confuse it with the second ability I automated in the post, that one needs to be done by CPR not you.  You should only yoink the Mask of the Wild from the post:

https://discord.com/channels/915186263609454632/1171668792187826216/1171668792187826216

Its just a simple midi on use macro of 

```
actor.rollSkill(`ste`);
```

This is a really cheesy simple automation if you wanted to add it.

**Comment by MrPrimate** [comment]
Thanks, I think I can actually do the other effect in DDB without CPR tbh

**Comment by MotoMoto1234** [comment]
Yeah I leveraged cpr cause his helpers were easier for me to grasp.
