### ISSUE TITLE
Monster: Strahd Zombie(Auto Effects)

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#425]
Bugbear made a Loathsome Limbs automation for us.  Its not 100% rules as written as it doesn't break up into multiple monsters, instead I keep it as one.  It also technically imposes a disadvantage on the bite under certain circumstances when it shouldn't but I really didn't see much of a big deal with it so left that scenario in.  If a user really wants to automate multiple tokens they could link their strahd zombie and then duplicate its token and change its image as body parts fall off.  

https://discord.com/channels/915186263609454632/1171800881235234816/1171800881235234816

Just requires midiqol.

**Comment by MrPrimate** [comment]
Thanks, tweaked slightly and added.
