### ISSUE TITLE
Race: Shifter(Multiverse)(Auto Effects)

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#426]
**Describe the bug**
If you made a Shifter in the Multiverse one, and the last racial feature is set to Shifting: Wildhunt:

The Changemode on the effect that "Shift" has on it is set to ADD when it needs to be CUSTOM(its a midi key that is typically undefined so ADD can't work on it)

**To Reproduce**
1. Import a Shifter from multiverse that has the final racial setting set to Wildhunt
2. Edit the Shift feature and look at the key/changemode/value on the ae

**Expected behavior**
Midi keys typically can't be ADD cause their values are usually undefined on actors, CUSTOM or OVERRRIDE are usually recommended, CUSTOM for this specific one.  

**Screenshots**
![image](https://github.com/MrPrimate/ddb-importer/assets/116308065/fc396fa3-56db-4e44-873a-cb8358f5c604)

**Environment:**
 - Browser [e.g. chrome] Newest Chrome
 - Foundry Version [e.g. 10.288] 11.313
 - 5e System Version [e.g 2.0.3] 2.3.1
 - Module Version [e.g 3.1.21] 3.5.8
 - N/A

**Additional context**
Found while working on the midi wiki

Be sure not to check CPR's setting cause he has his own version of this specific feature

**Comment by MrPrimate** [comment]
Ta
