### ISSUE TITLE
More Hold Breath automations

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#427]
1. The Tortle's hold breath imports without an activation cost so it shows passive instead of activateable.  It does have the ae like I had suggested though, just needs an activation.  I'd suggest 1 Special

2. The Vedalken's feature that is like Hold Breath is "Partially Amphibious"

It should be 1 Special and do hold breath for 1 hour.  However it should have 1/1 uses that refreshes on a long rest.

**Comment by MrPrimate** [comment]
Thanks
