### ISSUE TITLE
Planar warrior not adding the extra 1d8 scale damage

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#429]
On line 69 of the macro on this item it should be:

```js
        value: DDBImporter.lib.DDBMacros.generateItemMacroValue({ macroType: "feat", macroName: "planarWarrior.js", document: { name: `${macroData.item.name}` }}),
```

If you try to use it you will identify why by the error in the console.  Its setting an `ItemMacro.ItemMacro.Planar Warrior` effect value and that is wrong.  Trim that initial `ItemMacro.`

I've confirmed this as the fix/solution myself.

**Comment by MrPrimate** [comment]
Whoops, thank you
