### ISSUE TITLE
Expertise doesn't import properly for tool proficiencies

### ISSUE THREAD

**Issue by willhaning** [MrPrimate/ddb-importer#435]
**Describe the bug**
Thieves have the ability to select "Thieves' Tools" for their expertise feature.  However, this isn't reflected on an imported character in Foundry.  Moreover, it gets incorrectly overwritten on subsequent imports if the change is made in the Foundry character sheet after import.
**To Reproduce**
1. Create Rogue in DDB and select Thieves' Tools for the expertise feature.
2. Import the character into Foundry using the importer.
3. Open the Foundry character sheet and check the Tool proficiencies at the bottom of the attributes tab to see just a single checkmark next to Thieves' Tools.
4. Click on the gear icon next to Thieves' Tools and select "Expertise" in the proficiency field and click submit.  Verify that it has changed to the double checkmark indicating that expertise is applied.
5. Re-import the character using the wizard, and find that the change to Thieves' Tools has been reverted to just "Proficient"

**Expected behavior**
Expertise in a tool proficiency should be imported into the Foundry character sheet.

**Environment:**
 - Chrome
 - Foundry Version - 11.315
 - 5e System Version - 2.4.0
 - Module Version - 3.6.0

**Additional context**

-  I did try to add Thieves' Tools as a custom skill in DDB but this Custom Skill wasn't refelected in Foundry at all.
- I brought up a clean Foundry instance in The Forge with only the DDB importer enabled, and the behavior persisted as described above.

**Comment by MrPrimate** [comment]
This is actually already fixed for the next release, due out in the next week or so.

**Comment by willhaning** [comment]
Amazing.  Thanks!
