### ISSUE TITLE
Artificer: Tool Expertise

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#436]
This feature makes it so they roll expertise for any tool they are proficient in.  However if you import an artificer with various tool proficiencies, they show as just proficient.  

The image below has the alchemist supplies set to expertise manually so you can see the difference between expertise and proficient:
![image](https://github.com/MrPrimate/ddb-importer/assets/116308065/85bd1947-570d-4eb2-8335-11ca0ff7ffe8)

**Comment by MotoMoto1234** [comment]
When I tested this, I imported a basic level 20 artificer with no subclass set(working on the midi wiki).  There is a chance an incremental import might yield a different result.

**Comment by MrPrimate** [comment]
As per https://github.com/MrPrimate/ddb-importer/issues/435 this is fixed in the next release already. Thank you for the issue.
