### ISSUE TITLE
Class Feature: Intimidating Presence(Path of the Berserker)

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#443]
For both auto effects and regular version:

Target should be `1 Creature`  
Range should be `30 feet`  
Duration should be `2 turns`(Not for auto effects though see my item below for auto effects duration)  

Additionally I have automated this via auto effects and submitted a descriptionless version to Posney's discord here:  

https://discord.com/channels/915186263609454632/1192106701839671337/1192106701839671337

**Comment by MrPrimate** [comment]
Thanks, in next release
