### ISSUE TITLE
Cannot open core setup

### ISSUE THREAD

**Issue by thaeama** [MrPrimate/ddb-importer#444]
**Describe the bug**
I can open every other options menu besides core setup. It still shows the colored outline to show it has been hovered over/clicked, but does not open any sort of menu. Every other menu has been working fine. I have tried: re-installing foundry and the module;  and, disabling every other module (which was only two dice modules). This issue started when I updated from a previous version (not sure exactly which version i had prior, in the range of 3.5.7-3.6). I also just recently updated from 2.4 of the 5e system. Reverting back both to 5e 2.4 and DDB importer 3.5.7 did seem to solve the issue.

**Environment:**
 - Foundry Version 11.315
 - 5e System Version 2.4.1
 - Module Version 3.7.4

**Screenshots**
![Screenshot 2024-01-03 090029](https://github.com/MrPrimate/ddb-importer/assets/155552419/300d6f71-873c-42a9-99cc-1f749cecdcf8)
![Screenshot 2024-01-03 090005](https://github.com/MrPrimate/ddb-importer/assets/155552419/20016ff4-1eb2-4791-af36-c3b4c7908280)

**Comment by MrPrimate** [comment]
See the "cannot open core setup" in the FAQ
