### ISSUE TITLE
Path of the Storm Herald(Desert)

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#445]
Most of this is basically auto effects submissions but the actual raw subclass really could benefit from most of this too.  The set fire feature in the submissions is not for you, its for the posney guys to use.  You already had it.  

This subclass needs to be divided basically into 3 seperate subclasses as the main choice of the subclass affects all the subclass features.  I have made the Desert version, I included a blank Subclass item with the scale values for all 3 versions of this subclass, they are missing from your version that munches/imports fyi.  The link below is basically everything for just the Desert version.  I left out a few passive things that your importer brings in, so don't delete all your entries, some need to stay.  Everything is directly built off your imported stuff so you should be able to line everything right up.  I will do Tundra and Sea at some point tonight also and submit them.  

https://discord.com/channels/915186263609454632/1192222829375143966/1192222829375143966

**Comment by MotoMoto1234** [comment]
Here is the link to the Path of the Storm Herald(Sea) variant.  Its a reply in the same thread for desert so don't mix up the two posts hehe.  

Most of this is probably auto effects but I know for a fact on all three the Storm Aura's target and range is wrong for the non auto effects versions.  

Also the bonus action storm aura items for all three probably could have damage formulas in non auto effects.

(For auto effects don't touch the range/target of them as I set mine up for midi as self aoes)

https://discord.com/channels/915186263609454632/1192222829375143966/1192511871635431518

**Comment by MotoMoto1234** [comment]
Here is the Tundra version of this subclass:


https://discord.com/channels/915186263609454632/1192222829375143966/1192572854710063195

**Comment by MrPrimate** [comment]
In next release
