### ISSUE TITLE
Character class advancement missing features

### ISSUE THREAD

**Issue by puradox** [MrPrimate/ddb-importer#446]
**Describe the bug**
Imported characters' classes don't include features in their advancement. This prevents leveling up characters solely in Foundry. If a player attempts this, they will find 

**To Reproduce**
1. Import a character
2. View their class
3. View the "Advancement" tab
4. Compare to equivalent class from the SRD

**Expected behavior**
The DDB version of character classes' advancement to include character feats.

**Screenshots**
Two version of the Cleric class: **left** SRD, **right** DDB. Notice "Divine Domain", "Channel Divinity", and "Turn Undead" character feats missing.

![image](https://github.com/MrPrimate/ddb-importer/assets/941763/1a275a13-692c-4fb8-9d40-6436a0daa2dd)

**Environment:**
 - Browser: Chrome Version 120.0.6099.131 (Official Build) (64-bit)
 - Foundry Version: 11 Stable Build 315
 - 5e System Version: v2.4.1
 - Module Version: v3.7.6
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**
 - Example character URL: https://www.dndbeyond.com/characters/109960799
 - No errors in the browser console

**Comment by MrPrimate** [comment]
In order to link features like this they need to exist in the Compendium, you will need to run the Class and Feature munch feature first in the the DDB Muncher

**Comment by puradox** [comment]
After running the Class and Feature munch, there are still features missing. For example, `Channel Divinity: Turn Undead` is missing.

![image](https://github.com/MrPrimate/ddb-importer/assets/941763/bd7069e0-19d1-4c69-b9d7-9825270fe56e)

Additionally, `Channel Divinity` is listed as passive instead of an action.

![image](https://github.com/MrPrimate/ddb-importer/assets/941763/1e00c6ba-672c-4ce3-b5c4-0fd67e216028)
