### ISSUE TITLE
Consider changing the wording on the character importer

### ISSUE THREAD

**Issue by krbz999** [MrPrimate/ddb-importer#447]
In the import tool, several modules are named as "strongly recommended for best results", especially under the 'Active Effect Options' header. This often confuses new users of the dnd5e system, as they (1) don't know what Active Effects actually are (often confusing them with animations), and they (2) are not made aware that this is for 'best results' only if one is seeking high automation; they then install most, if not all, of these modules believing them to be required for best results of using the import tool, rather than for the added benefit that they may not be at all interested in.

Please consider changing the wording to make it more explicit that none of these modules are in fact required, needed, or provide any benefit, unless one actively wants to delve into the same _high_ automation that the relevant modules provide.

**Comment by krbz999** [comment]
Admittedly a bit surprised that this hasn't even gotten a sideways glance in 3 weeks for what should be a 2-minute change. The request is simply to inform users about what they are being encouraged to install, and why.

**Comment by MrPrimate** [comment]
I did tweak the wording @krbz999 , but forgot to link back to this request. https://github.com/MrPrimate/ddb-importer/commit/f81f7e73337ecc1b00195e04b157a82894b728e8

If you wish to change it further for your own understanding of the issue, then please submit a PR. I know you know how.

**Comment by krbz999** [comment]
Done.
