### ISSUE TITLE
Sentinel Shield doesn't give the +5 passive perception bonus

### ISSUE THREAD

**Issue by ravingdragoon** [MrPrimate/ddb-importer#448]
**Describe the bug**
Sentinel Shield doesn't give the +5 passive perception bonus that it should grant due to it granting advantage on perception checks.

PHB Chapter 7: Using Ability Scores:
Ability Checks:
Passive Checks:

"Here’s how to determine a character’s total for a passive check:

10 + all modifiers that normally apply to the check

If the character has advantage on the check, add 5. For disadvantage, subtract 5. "

**To Reproduce**
1. Equip and attune the imported Sentinel Shield on any PC.
2. Look at the PC's passive perception.
3. See that it did not increase by 5 as it should have

**Expected behavior**
Anything that gives advantage on perception checks should increase passive perception by 5.

**Comment by MrPrimate** [comment]
This works for me, at least using the default sheet. You will also need midi-qol active for the effect to apply. It will add the effect as `flags.midi-qol.advantage.skill.prc` which midi-qol will add the appropriate flat bonus to passive.

**Comment by ravingdragoon** [comment]
> This works for me, at least using the default sheet. You will also need midi-qol active for the effect to apply. It will add the effect as `flags.midi-qol.advantage.skill.prc` which midi-qol will add the appropriate flat bonus to passive.

That flag is giving me advantage on the perception checks, but I have to manually add the "system.skills.prc.bonuses.passive - add - 5" effect to my shield to get the bonus 5 to show up in the passive perception score.

**Comment by ravingdragoon** [comment]
Ugh, sorry. I forgot they had exhaustion which was cancelling out the advantage.
