### ISSUE TITLE
feature: Tidy 5e Sheets Rewrite Compatibility

### ISSUE THREAD

**Issue by kgar** [MrPrimate/ddb-importer#449]
Hello 👋
I am requesting to work with you on a way to establish compatibility between the Tidy 5e Sheet rewrite and DDB-Importer.
As far as I know, the only piece that is missing is the DDB import image button on the character/NPC sheets.

For this, I have created an "Inject Anywhere" API to assist with providing compatible reactivity to traditional form applications while operating within Tidy's svelte runtime environment. For adding content to the player character sheet, there is [registerCharacterContent](<https://kgar.github.io/foundry-vtt-tidy-5e-sheets/classes/Tidy5eSheetsApi.html#registerCharacterContent>). Like for NPCs, there is [registerNpcContent](<https://kgar.github.io/foundry-vtt-tidy-5e-sheets/classes/Tidy5eSheetsApi.html#registerNpcContent>).

I have not captured all of the implementation details of DDB-I, but the API usage would generally look like this with the current offering:
```js
// example of adding the button next to character name
Hooks.once("tidy5e-sheet.ready", (api) => {
  api.registerCharacterContent(
    new api.models.HtmlContent({
      html: `<div class="ddbCharacterName"></div>`,
      injectParams: {
        selector: `[data-tidy-sheet-part="name-header-row"]`,
        position: "afterbegin",
      },
      enabled: () => !game.settings.get("ddb-importer", "character-link-title"),
      onRender: (params) => {
        const $ddbCharacterName = $(params.element).find(".ddbCharacterName");

        const button = $(
          '<button type="button" id="ddbImporterButton" class="inactive"><i class="fab fa-d-and-d-beyond"></button>'
        );

        if (app.document.flags.ddbimporter?.dndbeyond?.url)
          button.removeClass("inactive");

        // todo: wire button click

        $ddbCharacterName.append(button);
      },
    })
  );
});
// the same can be done with NPC sheets via `registerNpcContent`
```

This results in the ddbi button appearing when configured:
![image](https://github.com/MrPrimate/ddb-importer/assets/4632129/bbe0d3e0-31d9-407e-a3b9-93a451021cfa)

As of now, the `html` prop only takes a string, but I am working on updating it to take a callback function also, which could eliminate the one extra layer of indirection of relying on `onRender`. If you're interested in having it all in the `html` prop as a callback function, I can prioritize this for DDBI integration.

Thanks for reading. I hope to hear your thoughts on this.

**Comment by MrPrimate** [comment]
Thankyou, first pass support in 3.7.14, out shortly

**Comment by kgar** [comment]
I should be thanking you!
Thank you very much for working with me on this.

**Comment by MrPrimate** [comment]
Okay, it's out in the wild, I'm away for a few days, but will try to get the tokenizer changes done before the weekend. Thanks for your great work on the new sheet!
