### ISSUE TITLE
Rune Knight: Giant's Might feature and Auto Effects

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#450]
**Describe the bug**
There is a data entry error in this feature.  If you view the active effect, it appears that one of the intended key/mode/values has been accidentally squeezed into another.  Looks really obvious in the image below.  I don't think you need to even include the borked system.trait.size key honestly.  Also the optional.name.count key is wrong, it only happens on their turn so it should be `turn` not `each-turn`.  

![image](https://github.com/MrPrimate/ddb-importer/assets/116308065/bdce4518-0ac3-4d59-97d1-2166eb42e24d)

**Comment by MrPrimate** [comment]
Fixed in next release.
