### ISSUE TITLE
Sharpshooter Feat(Auto Effects)

### ISSUE THREAD

**Issue by MotoMoto1234** [MrPrimate/ddb-importer#455]
I tweaked your sharpshooter feat, I think I changed it to self/self for range/target and then I checked the box in the Midi tab for "toggle Effect".  This lets a midi user toggle the effect whenever they roll it.  I also moved the CE to the item so that this will work even if a user doesn't have DFreds, though I think you have a hard requirement of Dfreds CE in auto effects so probably a non issue for your users.  

Heres my descriptionless submission to posney's discord:

https://discord.com/channels/915186263609454632/1201306206929702982/1201306206929702982

**Comment by MrPrimate** [comment]
I actually tweaked this myself this morning!
