### ISSUE TITLE
Does not work on D&D 5e v3.0.0

### ISSUE THREAD

**Issue by HitManTWO** [MrPrimate/ddb-importer#457]
My player's Blood Hunter Character sheet won't even open after the new D&D update. When I try to import a new character it doesn't import a class or any features.

**Comment by MrPrimate** [comment]
D&D System 3.0.0 contains many breaking changes, there will be a compatibility release soon. Until then, if you wish to use DDB Importer, you need to roll back to v2.4.* of the Foundry system.

**Comment by johnweland** [comment]
I am not sure if it's related. 5e v3.0.1 with DDB Importer 4.0.0, but all settings pages open and can be configured EXCEPT the core settings, so there is no way to setup the Cobalt Cookie.

**Comment by MrPrimate** [comment]
> I am not sure if it's related. 5e v3.0.1 with DDB Importer 4.0.0, but all settings pages open and can be configured EXCEPT the core settings, so there is no way to setup the Cobalt Cookie.

This is probably unrelated see https://github.com/MrPrimate/ddb-importer/blob/main/FAQ.md#my-core-settings-screen-wont-open

**Comment by johnweland** [comment]
absolutely right, in my case it had to do with using a self hosted proxy which I then had a typo in (soon as I fixed that, then the core would open)
