### ISSUE TITLE
Error when importing character from DnD Beyond: Error processing Character: Error: This is not a registered Game Settings

### ISSUE THREAD

**Issue by franckflo** [MrPrimate/ddb-importer#458]
**Describe the bug**
I am currently unable to import a character from DnD Beyond to my campaign hosted on the Forge. It has worked fairly well in the past and no configuration was changed. The Upload of the same character worked a week ago, and I am trying to download it back after its player leveled up in DnD Beyond.

**_This seems to be a conflict with the latest version of the Item Macro module: 1.11.1_**

**To Reproduce**
1. Go to Character character sheet in Foundry
2. Click on DnD Beyond icon
3. click on Import character
4. Only the following are selected: Name, HP; Hit Die; Spell Slots; Classes, Features, Spells
5. Error shows up

I tried on multiple character tokens from the same token and got same result

**Expected behavior**
The character's Name, HP; Hit Die; Spell Slots; Classes, Features, Spells are updated

**Environment:**
 - Browser: Tried with Chrome, Vivaldi and FLC
 - Foundry Version 11.315
 - 5e System Version 2.4.1
 - Module Version 3.717
 **_- Find the Culprit: It seems there is a conflict with Item Macro 1.11.1 but not previous version: 1.10.5_**

**Additional context**
- I am a long-date Patron supporter of your Patreon page
- I checked that Patreon Key and Cobalt Cookie key are correct
 - Character URL (he is public): https://www.dndbeyond.com/profile/Indytims/characters/43699078
 - Details of any errors in the browser console (press F12).

**This is the changelog for Item Macro since 1.10.5**

> v1.11.1
> Fixed Macro lacking context (and in turn having mismatched arguments)
> v1.11.0
> General
> Changed item.executeMacro() method to be async
> Updated how Item Macro is built and called to allow retrieving its value
> DnD5e
> Switched DnD 5e's support to dnd5e.preUseItem Hook
> Because of that, there no longer is distinction between using item from sheet, macro or any other way
> Because of that, using plain item.use() in Item Macro is now disabled as it can lead to uncontrolled infinite loops
> Since good practice dictates that all 3rd party modules, including custom sheets, should make use of item.use(), this means that all of them should now be supported by default
> Character Sheet Hook and Right Click Override settings for dnd5e are now removed in favor of single Override default macro execution
> Item Macros that you wish to still execute "standard" item.use() must now do it in one of two ways:
> Return true from macro, or
> Call item.use({}, {skipItemMacro: true}) instead (passing skipItemMacro = true in options argument)

**Comment by MrPrimate** [comment]
I believe the version of Itemacro installed won't work with the D&D installed.

In addition, this will only occur if you're using DAE, and Item Macros functionality has been absorbed by DAE. Is suggest disabling Item macro until you can update to the v3.0.0 of the D&D system.

**Comment by franckflo** [comment]
Got it, thanks !
