### ISSUE TITLE
Improved Autognome Armored Casing AC calculation

### ISSUE THREAD

**Issue by benedfit** [MrPrimate/ddb-importer#462]
**Is your feature request related to a problem? Please describe.**
Each time I run the importer on my Autognome character I find that my AC always returns to my "natural" unarmored state of `13 + dex` despite also having armor equipped. I am currently solving this by changing `system.attributes.ac.formula` from `10 + 3 + @abilities.dex.mod` to `max(10 + 3, @attributes.ac.armor) + @abilities.dex.mod`, but each time I run the import it is overridden

**Describe the solution you'd like**
I'd like the importer to take into account whether my Autognome is wearing armour, and use the higher of the two values to calculate the AC

**Describe alternatives you've considered**
If there is a way to prevent this being overridden when importing by unchecking some of the boxes, please let me know

**Additional context**
<img width="593" alt="Screenshot 2024-02-23 at 00 10 45" src="https://github.com/MrPrimate/ddb-importer/assets/580859/a0d6b0a9-e84d-434a-92e0-067be320335c">

**Comment by MrPrimate** [comment]
Thanks, this fix will be in the next release.
