### ISSUE TITLE
Unarmored Defense uses wrong formula

### ISSUE THREAD

**Issue by Blazewardog** [MrPrimate/ddb-importer#465]
**Describe the bug**

The Barbarian Unarmored Defense effect uses the wrong formula. It generates an effect with the formula of
`max(10 + @abilities.con.mod + @abilities.dex.mod, @attributes.ac.armor)`
Which does the max of unarmored defense or the base armor **ignoring any dex bonus**
The real formula that should be used is
`max(10 + @abilities.con.mod + @abilities.dex.mod, @attributes.ac.armor + @attributes.ac.dex)`

**To Reproduce**
1 Create a barbarian with unarmored defense and at least a +2 to dex and +2  to con
2 Equip Half Plate
3 Import via DDB Importer
4 See a AC of 15 instead of the 17 that should be calculated. The 15 is wrong for both unarmored defense (14) and the armor's AC (15+2dex), it is just the base armor AC without dex.

**Expected behavior**
It should calculate to the armor + appliable dex modifier if that is greater than the AC of unarmored defense.

**Screenshots**

**Environment:**
 - Browser [e.g. chrome]
 - Foundry Version 11.315
 - 5e System Version 3.0.3
 - Module Version 4.0.13
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**
Might be broken for Monk also, but I haven't checked. 

Additionally, since you are always setting a custom formula the AC calculation when you hover over AC looks weird, even after fixing the effect. Could it maybe just set the correct AC formula vs always setting it to custom?

 - A Character URL, if the problem is a character import.
 - Details of any errors in the browser console (press F12).

**Comment by MrPrimate** [comment]
Thank you, improvements in the next release.

**Comment by Blazewardog** [comment]
I took the update and re-imported the affected Barbarian.

The AC calculation now looks correct, but it still by default enables Unarmored Defense. I can disable the effect manually and it now then properly falls back to Armor calculation, but I still need to manually disable the effect each import. Less annoying than the previous fix, but still not really fixed.

Summary:
The completely wrong AC 15 is gone, but AC 14 (unarmored defense) is still preferred over AC 17 (Half Plate + Dex).

**Comment by MrPrimate** [comment]
It should be disabling the effect if it's not the highest. Please can you at least provide a character url of your affected character so i can replicate

**Comment by Blazewardog** [comment]
Character is here: https://www.dndbeyond.com/characters/110163947

I don't have time to check right now, but I remember that there is that setting to try and preserve active effects. I can't remember if I have that turned on or not. I'll try and remember to update this comment when I get a chance.

**Comment by MrPrimate** [comment]
Sorry, this was a stupid error on my part, I corrected it, then made a change which would invalidate the correction. Fixed in v4.0.15,  out now

**Comment by Blazewardog** [comment]
Confirmed that it is fixed. Thanks for the fancier fix than I originally asked for.
