### ISSUE TITLE
Portable Hole not being imported with "Weightless Contents" checked

### ISSUE THREAD

**Issue by ravingdragoon** [MrPrimate/ddb-importer#467]
**Describe the bug**
Portable Hole not being imported with "Weightless Contents" checked, causing players to incorrectly be marked as over-encumbered.

**To Reproduce**
1. Import a character with a portable hole filled with stuff
2. See that they are over-encumbered and that in the Details page of the Portable Hole the check box for Weightless Contents is unchecked.

**Expected behavior**
The Portable Hole should import with the Weightless Contents checkbox checked and should not impact the carry weight of the character who has it.

**Screenshots**
![image](https://github.com/MrPrimate/ddb-importer/assets/72875320/304416d6-00aa-41e9-812e-0f144316ca6e)

![image](https://github.com/MrPrimate/ddb-importer/assets/72875320/d62c855f-9fff-44e0-b91f-998bef00981b)

**Environment:**
 - Browser Chrome
 - Foundry Version 11.315
 - 5e System Version 3.0.4
 - Module Version 4.0.16
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**

 - A Character URL: https://www.dndbeyond.com/characters/70101654

**Comment by MrPrimate** [comment]
Thanks, this will be fixed in the next release.
