### ISSUE TITLE
Avatar for homebrew spell not synced

### ISSUE THREAD

**Issue by tymonite** [MrPrimate/ddb-importer#470]
Avatars for my homebrew spells are missing. Just getting the spell icon school replacement.
It's working for other homebrew entities like monsters and items. But not for spells...

I'm using up-to-date versions for all systems and modules, including version 5.0.0 of DDB-Importer.

**Comment by MrPrimate** [comment]
The JSON that is fetched for spells does not include the images, so the importer is unable to add them.

**Comment by tymonite** [comment]
I see. :( 
DDB itself must have a link anywhere to show the image in the browser. I'm curious how the fetch mechanism work. There must be a reference anywhere to that "https://www.dndbeyond.com/avatars/thumbnails/..." image.

**Comment by MrPrimate** [comment]
> I see. :( 
> DDB itself must have a link anywhere to show the image in the browser. I'm curious how the fetch mechanism work. There must be a reference anywhere to that "https://www.dndbeyond.com/avatars/thumbnails/..." image path.

It's not the spell page that the data is fetched from, but the JSON data that is provided to characters when you select the spell, which is a slightly different subset of information.
