### ISSUE TITLE
Compendium packs aren't created in the D&D Beyond folder

### ISSUE THREAD

**Issue by kaelad02** [MrPrimate/ddb-importer#472]
**Describe the bug**
When this module auto-creates a bunch of compendium packs to munch data into, they're not in the D&D Beyond folder.

**To Reproduce**
1. Create a new world
2. Enable the DDB Importer module
3. Go to the Compendium Packs sidebar tab

**Expected behavior**
All of those packs should be inside that "D&D Beyond" folder, but they're not.

On the main Foundry Discord server, someone else was having the same problem. They were trying to programmatically create a pack inside a folder and it wasn't working. It reminded me of this longstanding problem the importer has had. Someone suggested a workaround that worked for them: update the pack after creating to put it into the folder. Turns out that's exactly what the core Foundry code does if you look into `CompendiumDirectory#_onCreateEntry`:

```js
// FYI: metadata doesn't have a folder property in it
const pack = await CompendiumCollection.createCompendium(metadata);
if ( targetFolderId ) await pack.setFolder(targetFolderId);
```

For the importer, you should be able to fix it in the `CompendiumHelper#createIfNotExists` function.

**Comment by kaelad02** [comment]
I haven't filed a PR in a while and this is simple enough. I'll just do that

**Comment by kaelad02** [comment]
okay, PR #473 is ready

**Comment by MrPrimate** [comment]
Fantastic!!!
