### ISSUE TITLE
PC Features failing to import properly

### ISSUE THREAD

**Issue by ravingdragoon** [MrPrimate/ddb-importer#478]
**Describe the bug**
The following features are not importing properly for my PCs:
_Wizard_
Chronal Shift: Not importing with the activation cost (Preventing the resource from displaying/consuming properly)
Arcane Abeyance: Not importing with the activation cost (Preventing the resource from displaying/consuming properly)
Temporal Awareness: Not adding the intelligence score to the initiative bonus again (You had fixed this previously)
_Paladin_
Channel Divinity: Not importing with the activation cost (Preventing the resource from displaying/consuming properly and the Channel Divinity Abilities from using the resource)
_Druid_
Cosmic Omen: Not importing with the activation cost (Preventing the resource from displaying/consuming properly)
Star Map: Not importing with the activation cost (Preventing the resource from displaying/consuming properly) (This one may be more complex and a separate issue due to it's link with casting Guiding Bolt)

**To Reproduce**
1. Go to 'Import these characters'
2. Click on 'Open character sheets'
3. Scroll down to 'Resources'

**Expected behavior**
Activation cost to be imported properly, allowing these features to function properly after import.

**Screenshots**

**Environment:**
 - Browser [chrome]
 - Foundry Version [11.315]
 - 5e System Version [3.1.2]
 - Module Version [5.1.19]
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**
Given the nature of these errors, I would hazard a guess that there are many features that are not importing properly due to a missing activation cost.

**Character links**
 - https://www.dndbeyond.com/characters/70291787
 - https://www.dndbeyond.com/characters/70295399
 - https://www.dndbeyond.com/characters/70289177

**Comment by MrPrimate** [comment]
All of these are importing with activation costs here, and the int is added to initiative as an effect. Did you try with other modules disabled, and you're not using things like override compendiums? Does it work in a completely new world?

**Comment by ravingdragoon** [comment]
I did try with all modules off except ddb-importer, CPR, and Gambit premades (plus all of their prerequisite modules) but I have not tried on a fresh world. I do have some stuff in the override compendium but no class features. I will close this for now and reopen it if/when I have time to test more.
