### ISSUE TITLE
Artificer Infusion Import error

### ISSUE THREAD

**Issue by Blazewardog** [MrPrimate/ddb-importer#479]
**Describe the bug**
Upon importing one of my player's characters (an Artificer), I get an import error of TypeError: Cannot read properties of undefined (reading 'value').

This is caused by this line of code in infusions.js:

https://github.com/MrPrimate/ddb-importer/blob/232d93d04f2f3a099d9a9257ad7e4edb941adfc8/src/parser/item/infusions.js#L178

mockAbility is set to "" which doesn't exist in the array. This is because in the line above where this is supposed to be handled:

https://github.com/MrPrimate/ddb-importer/blob/232d93d04f2f3a099d9a9257ad7e4edb941adfc8/src/parser/item/infusions.js#L175

The item's system.ability is set to "" rather than null.

The item is a Crossbow, heavy with a Repeating Shot infusion on it.

**To Reproduce**
1. Go to import a character with the specified item/infusion such as https://www.dndbeyond.com/characters/112215903
2. Get the error

**Expected behavior**
The character to import

**Screenshots**
My import configuration looks like this:
![image](https://github.com/MrPrimate/ddb-importer/assets/682867/67c81d50-3f51-4c29-bc30-eda6f0797671)

**Environment:**
 - Browser Chrome/Firefox
 - Foundry Version 11.315
 - 5e System Version 3.1.2
 - Module Version 5.1.21
 - Does this behaviour occur with other modules disabled: Yes

Have Midi/DAE/Chris's Premades enabled, 

**Additional context**
The affected character is this:
https://www.dndbeyond.com/characters/112215903
I tested just setting mockAbility to "dex" and it works as expected then.

**Comment by MrPrimate** [comment]
Thanks for the report and detailed info, fixed in the next release, out in about 24 hours.
