### ISSUE TITLE
trouble munching newly bought content

### ISSUE THREAD

**Issue by jkuball** [MrPrimate/ddb-importer#481]
**Describe the bug**

Hey! Thanks for the tool :)

I bought the player's handbook on the 29.04.2024, which I could import into my foundry instance (with patreon I also could import all races & classes, etc.).
In session 0 today a player wanted to play a race available in _mordenkainen presents monsters of the multiverse_ -- so we bought it instead of building it by ourselves.

While buying I found that D&D Beyond looked different, but I just bought it and tried to munch races -- nothing new was created.
I tried multiple times and different settings, but I just didn't get it to work.

It seems like D&D beyond changed something in their payment process / order history after april '24, could it be that they changed their API too?

I checked multiple times that I really own the content on D&D Beyond, and I do.

**EDIT:** I have just learned that I also can't select those races inside D&D Beyond Character Creation itself, maybe they have borked something and it is not a problem on the ddb-importer. Still, I can't use the bought content, I can just read the digital book.

**To Reproduce**
1. Buy something new that contains races -- like mordenkainen presents monsters of the multiverse
2. Do a race munch

**Expected behavior**
After a race munch I'd like to see the races I own in D&D Beyond. (And other munches too, I didn't get any content of the freshly bought things to work).

**Environment:**
 - Browser: Firefox 123.0.1
 - Foundry Version: 11.315
 - 5e System Version 3.1.2
 - Module Version: 5.1.22
 - Does this behaviour occur with other modules disabled: Not tested yet

Hopefully something else has this problem too, or it just works magically tomorrow.

**Comment by MrPrimate** [comment]
If you can't select the races in the character creator the Importer won't be able to see them. You likely need to "sync your entitlements" in DND beyond.

https://dndbeyond-support.wizards.com/hc/en-us/articles/7747224765588-Sync-Entitlements#:~:text=If%20they're%20out%20of,Entitlements%20are%20back%20in%20sync.

I'm going to close this as it's not a DDB Importer issue, as it's working correctly, able to see the content you have access to on DDB.

**Comment by jkuball** [comment]
Hi! Thanks for the link and the fast response!

After going to bed it just worked now -- probably, because ddb syncs regularly (?).
I was a little perplexed because I am pretty sure the last time I bought something it was available instantly, but that might just be bad timing.

Have a nice day :)
