### ISSUE TITLE
Shared Compendium

### ISSUE THREAD

**Issue by MaineKnight** [MrPrimate/ddb-importer#482]
I have been looking online and countless sources say you simply go to settings and select the shared compendium you wish to import say "Items" into so that when you much "Items" it will update the shared compendium verses a world specific one. So far this has not worked and not sure if it is a bug, a change, or a procedural problem on my side. 

When I go into the settings all optioned only show the world specific "[World] ddb [Compendium Name]", Tables and Journals are the only ones that give other options. 

What I am attempting to do:
1) Create a shareable module which would have tables referencing the imported from DDB Items compendium
2) This would allow me to access/update info from DDB in all worlds.

If this is not a feature yet, adding the option to allow munched compendiums created during import to be shareable verses world specific by default

**Comment by MrPrimate** [comment]
It is an option, make sure you have created compendiums of the right type, and that they are unlocked.
