### ISSUE TITLE
Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by EtienneDroletBegin** [MrPrimate/ddb-importer#483]
after Updating my FoundryVTT to the latest version (11) as well as the DnD system (3.1.2), i have been unable to import characters, it simply gives me the error "Cannot read properties of undefined (reading '0')"

i tried resetting the cobalt key and reinstalling the module but nothing worked

**Comment by MrPrimate** [comment]
Duplicate of https://github.com/MrPrimate/ddb-importer/issues/406 see original issue for cause and resolution.
