### ISSUE TITLE
Import all characters - script doesn't do anything for me

### ISSUE THREAD

**Issue by RandomLegend** [MrPrimate/ddb-importer#484]
**Describe the bug**
I read through the FAQ and found this script:

```
const actors = game.actors;
for (let [key, value] of actors.entries()) {
  const ddbImported = 'ddbimporter' in value.flags;
  if (ddbImported && value.type === "character") {
    console.log('Importing: ' + value.name);
    await game.modules.get("ddb-importer").api.importCharacter(value);
  }
}
```

I've saved it as a script macro and executed it, but it doesn't do anything. Nothing in the logs and / or console

**Environment:**
 - Browser [Thorium]
 - Foundry Version [e.g. 11.315]
 - 5e System Version [e.g 3.1.2]
 - Module Version [e.g 5.1.24]
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**
Manually importing single characters work fine.

**Comment by MrPrimate** [comment]
This script will just update existing characters in the world

**Comment by RandomLegend** [comment]
Yeah i realized that aswell.

Sorry and thanks^^
