### ISSUE TITLE
DDB Importer 5.1.28 is not showing up in configure settings

### ISSUE THREAD

**Issue by aulyre77** [MrPrimate/ddb-importer#486]
**Describe the bug**
I have DDB-Importer 5.1.28 installed on Foundry v11.315 and DnD 5e system 3.2.0. The DDB Importer module shows up in manage modules as installed, but it does not show up in configure settings and does not show as a button on the player character sheet when in edit mode. 

**To Reproduce**
1. See above

**Expected behavior**
DDB Importer should show up in configure settings and should be a button in the player character sheer when in edit mode.

**Screenshots**
![Screenshot 2024-05-30 Foundry Player Character Sheet](https://github.com/MrPrimate/ddb-importer/assets/171306153/e075099e-9fa2-46e9-9610-3cb90294004b)
![Screenshot 2024-05-30 Foundry Configure Settings](https://github.com/MrPrimate/ddb-importer/assets/171306153/2fdc84fb-d8b2-4942-9e3d-6ba9d5872d34)
![Screenshot 2024-05-30 Foundry Modules](https://github.com/MrPrimate/ddb-importer/assets/171306153/cf361d9a-3737-402c-a10c-4c9fc80b706c)

**Environment:**
 - Browser: Chrome
 - Foundry Version v11.315
 - 5e System Version 3.2.0
 - Module Version 5.1.28
 - Does this behaviour occur with other modules disabled: Yes - I disabled all modules except DDB Importer and it still does not show in Configure Settings

**Additional context**

 - A Character URL, if the problem is a character import.
 - Details of any errors in the browser console (press F12).

**Comment by JamesAlday** [comment]
Just noticed this issue myself.  I updated earlier and had a game tonight. My characters leveled up, but then noticed that the button was no longer on their character sheets.  After seeing this bug, I checked and see that it shows up in Module Management but not Game Settings.

**Comment by MrPrimate** [comment]
Are you both using the Forge? Other users have reported this issue, if so you need to contact Forge support as they have a special way of installing modules, and it's broken for some users with DDBI and other modules.

**Comment by jalday-wu** [comment]
I am using forge. Haven't tested it against a local install.

**Comment by redheaddude62** [comment]
I am using foundry and am running into the same issues. I upgraded to current foundry v12.x, and the DDB Importer module shows up in manage modules as installed, but it does not show up in configure settings and does not show as a button on the player character sheet when in edit mode.

also I only downloaded DDB importer after upgrading to foundry version 12 but I assume it worked on v11

**Comment by MrPrimate** [comment]
> I am using foundry and am running into the same issues. I upgraded to current foundry v12.x, and the DDB Importer module shows up in manage modules as installed, but it does not show up in configure settings and does not show as a button on the player character sheet when in edit mode.
> 
> also I only downloaded DDB importer after upgrading to foundry version 12 but I assume it worked on v11

Are you also using the forge? If so, talk to forge support as something is still not right for your account. If not, then disable all other modules, as likely one of them is interfering because it's not compatible with v12.

**Comment by JamesAlday** [comment]
Looks like there was some "asset issue" that was cleared up.  Can confirm that it's loading for me now in Forge using Foundry 11.

**Comment by aulyre77** [comment]
It was resolved for me as well yesterday.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
