### ISSUE TITLE
Missing Backgrounds from PHB

### ISSUE THREAD

**Issue by atomdmac** [MrPrimate/ddb-importer#487]
**Describe the bug**
After importing the Players Handbook, I'm able to see Journal Entries (indicating that the import was successful) but no Backgrounds appear under the DDB Backgrounds compendium.  May be related to: https://github.com/MrPrimate/ddb-importer/issues/147

**To Reproduce**
1. Pull down the PHB adventure using the DDB Adventure Muncher
2. Import the PHB file into Foundry using `Import Generated Adventure`
3. Use the `Import Adventure to Adventure Compendium` option
4. Notice that the DDB Adventure compendium _does_ show the PHB entry
5. Import the PHB adventure into the World
6. Notice that no Backgrounds appear in the `DDB Backgrounds` compendium or in the `Items` tab

**Expected behavior**
All backgrounds from the Players Handbook should be available under the `Items` tab.

**Screenshots**
N/A

**Environment:**
 - Browser: Firefox 126.0
 - Foundry Version: 12 Stable, Build 325
 - 5e System Version: 3.2.0
 - Module Version: 5.2.0
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**
N/A

**Comment by MrPrimate** [comment]
Backgrounds are imported using the Backgrounds tool on the Characters tab of the DDB Muncher. The Adventure Muncher is intended for importing scenes and journal content, it does not parse things like backgrounds or classes.

**Comment by atomdmac** [comment]
Got it - thank you for clarifying!
