### ISSUE TITLE
Already exists within parent collection error when importing one PC

### ISSUE THREAD

**Issue by Yamiash102** [MrPrimate/ddb-importer#491]
**Error**
When importing [one character in particular](https://www.dndbeyond.com/characters/73129966), I'm encountering the following error:
> Error: The_id [ddbSendSeStSenSt] already exists within the parent collection: Actor [BkzkRmxebMMaFEqs] items
![image](https://github.com/MrPrimate/ddb-importer/assets/63170090/697d8267-0a3c-4a43-84f4-1583d3283e60)
![image](https://github.com/MrPrimate/ddb-importer/assets/63170090/62b1fdd5-b06f-4961-88e1-f8f9da1ddfc0)

The error persists even with all update boxes unchecked in "Update selection", and when importing to a new, empty actor sheet.

Cobalt Cookie has been updated. The error persisted with all modules disabled except for some libraries via Find the Culprit:
![image](https://github.com/MrPrimate/ddb-importer/assets/63170090/5313b9ce-dad3-439d-8d9f-681fd735f874)

I've looked through [other](https://github.com/MrPrimate/ddb-importer/issues/305) similar issues—the Druidcraft cantrip was on the character due to a homebrew item, but the error continued to exist after deleting the cantrip from the spells list on the character sheet in Foundry. Not sure if I should delete it elsewhere.

The compendiums appear to be set correctly, and I munched my spells as well
![image](https://github.com/MrPrimate/ddb-importer/assets/63170090/1cd7e26f-8fdc-4bf1-914a-30714a113112)

**To Reproduce**
1. Attempt to import above character into actor as usual
2. Import fails; above error messages shown

**Expected behavior**
Full import, as with the other 4 character sheets I've imported today

**Environment:**
 - Browser: Chrome
 - Foundry Version: Release 11.315
 - 5e System Version: 3.2.0
 - Module Version: 5.2.6
 - Does this behaviour occur with other modules disabled: Yes; only some library modules that remained enabled as shown above
 
 Log info from instructions in FAQ:
[ddbimporter-log-data.json](https://github.com/user-attachments/files/15748066/ddbimporter-log-data.json)

**Comment by MrPrimate** [comment]
Thanks for the report, fixed in v5.2.7, out soon.
