### ISSUE TITLE
Error when trying to change the location settings

### ISSUE THREAD

**Issue by kaelad02** [MrPrimate/ddb-importer#492]
**Describe the bug**
This was reported by a user on the main Foundry Discord server. Since I dug into the code to find the bug, figured I'd file one for them. Anyways...

> odd error recently when trying to change the DDB Importer Location Settings. when attempting to change then click select directory, nothing happens in foundry and i receive the screenshotted console error. this happens whether i select a new directory or leave it alone.

Here is the error they saw in the console:

![image](https://github.com/MrPrimate/ddb-importer/assets/19502084/3ad7ed8f-91cf-47e8-8684-8baf79bbe663)

**Environment:**
 - Browser: unknown
 - Foundry Version: 11.315
 - 5e System Version: 3.2.0
 - Module Version: 5.2.8
 - Does this behaviour occur with other modules disabled: Yes, they ran FTC and it still happened
 
**Additional context**
Since the error message had the word "bucket" in it, I suspected it had something to do with the recent Foundry v12 S3 fix in version 5.2.8. I took a peek in the code and it looks like it's assuming that S3 is configured here:

https://github.com/MrPrimate/ddb-importer/blob/c69eb2b14e739d52954fe58d632aa416d9e3de46/src/lib/DirectoryPicker.js#L17

This part, specifically: `this.sources.s3.bucket`

**Comment by kajishun** [comment]
i also noticed this issue on my dev-dnd5e world. same problem there so it is not world-related.

**Comment by kajishun** [comment]
i also see the same problem in my forge vtt instances. downgrading to 5.2.7 for now to avoid issue.

**Comment by MrPrimate** [comment]
Fixed in v5.2.10

**Comment by kajishun** [comment]
sweet, thanks!
