### ISSUE TITLE
Spells fail to import

### ISSUE THREAD

**Issue by MrSSvard** [MrPrimate/ddb-importer#494]
**Describe the bug**
I'm trying to import spells but it throws an error in the browser (screenshot) and stops. 
Importing monsters and items work.

**To Reproduce**
- Create new world
- Enable DDB-Importer (reproducible with or without other modules)
- Configure token and ddb-proxy
- Open "Spells" tab
- Click "Spell Munch"

**Expected behavior**
Spells should import

**Screenshots**
![screenshot blurred](https://github.com/MrPrimate/ddb-importer/assets/15969894/fca29574-d001-42ad-a447-3c80da48419a)

![Screenshot from 2024-06-16 20-38-05](https://github.com/MrPrimate/ddb-importer/assets/15969894/ed2ba729-8124-4e45-94ad-11d6f5e563ba)

**Environment:**
 - Browser: Brave Browser version 1.67.116 (Running on Linux)
 - Foundry Version: 12.327 ([Feldy's docker image, latest Release tag](https://registry.hub.docker.com/r/felddy/foundryvtt))
 - 5e System Version: 3.2.1
 - Module Version: 5.2.15
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**
Node version in container is 18.
The screenshots are from creating a new world and only activating DDB-Importer.
Thanks for creating this awesome module! You're the best!

**Comment by MrSSvard** [comment]
I added a screenshot of the container logs with debug info on. It seems to stumble on the summons

**Comment by MrPrimate** [comment]
Are you definitely using 5.2.15? I thought I had fixed this there - a work around is to use my proxy or disable summon spells processing

**Comment by MrPrimate** [comment]
Are you using your own proxy? (This shouldn't be a problem, just trying to narrow down causes)

**Comment by MrSSvard** [comment]
Hi, thanks for the reply. Yes I updated both container, DnD system and the module as well as the proxy (also self hosted). I got around the issue now by importing spells without the proxy and then with the proxy again but I'll double check tomorrow that the issue is present with a new world.

**Comment by MrPrimate** [comment]
I have just pushed 5.2.16, which will hopefully fix this for you

**Comment by MrSSvard** [comment]
Yes, that did it!
That's awesome, thanks. I'll subscribe for a couple of months as thanks
