### ISSUE TITLE
3 Monsters from Quest of the Infinite Staircase not importing

### ISSUE THREAD

**Issue by WisdomOfWombats** [MrPrimate/ddb-importer#497]
**Describe the bug**
The Monster import from Quests from the Infinite Staircase hangs up at "Warrior of Madarua". That monster, and the following: Worker Robot and Wolf-in-Sheep's-Clothing, and maybe others are not importing after that.

**To Reproduce**
1. Set up Monster Munching to munch the Quest from the Infinite Staircase.
2. Run
3. Always stops at Warrior-of-Madarua

**Expected behavior**
All monsters from the Quest from the Infinite Staircase are munched

**Screenshots**
![image](https://github.com/user-attachments/assets/d3417a10-336e-4d27-8418-7297bcbfb42d)

**Environment:**
 - Browser: Chrome 126.0.6478.185
 - Foundry Version 12.330
 - 5e System Version 3.3.1
 - Module Version 5.2.26

**Additional context**

 - A Character URL, if the problem is a character import.
 - Details of any errors in the browser console (press F12): See screenshot

**Comment by MrPrimate** [comment]
These are working here. Please try:

- disabling all other modules 
- disabling the webp conversation in your file location settings for DDB importer

**Comment by WisdomOfWombats** [comment]
Disabling the webp conversion did the trick.
