### ISSUE TITLE
Doesn't apply magical sleep resistance when importing race shadar-kai

### ISSUE THREAD

**Issue by dafzor** [MrPrimate/ddb-importer#498]
**Describe the bug**

When importing a character of the  shadar-kai race it doesn't import it's magical sleep resistance.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a DnD Beyond character that's a shandar-kai
2. Import to Foundry
3. Notice lack of resistance in VTT vs DnD Beyond

**Expected behaviour**

Magical sleep resistance to be added to resistances same as DND Beyond Character sheep

**Environment:**
 - Browser Any
 - Foundry Version 11.315
 - 5e System Version 3.2.1
 - Module Version [e.g 3.1.21]
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**

The race description lacks the explicit mention of magical sleep resistance, which is why i assume it doesn't get added.

 - https://www.dndbeyond.com/characters/126889707
 - Details of any errors in the browser console (press F12). N/A

**Comment by MrPrimate** [comment]
I have a fix for this but it won't be out for a little while as its part of a broader refactor for some features.

**Comment by MrPrimate** [comment]
Resolved in 6.0.0
