### ISSUE TITLE
Character Import: Wrong effects from feats

### ISSUE THREAD

**Issue by weberal** [MrPrimate/ddb-importer#499]
**Describe the bug**
I have a character that has the feat "Squat Nimbleness" (XGE) it grants a speed bonus of 5 ft. as well as an increase on STR or DEX and a proficiency on Acrobatics or Athletics.
So after the import there is one effect for "Squat Nimbleness: Dexterity Score" and one for "Squat Nimbleness: Acrobatics" and both grant a speed bonus of 5 ft.

It seems like the effects are taken from data.choices.feat instead of data.modifiers.feat. I think that would make more sense and reduce errors.

**To Reproduce**
1. Create any character with the feat "Squat Nimbleness".
2. Import to Foundry
3. Compare the walking speed between D&D Beyond and Foundry.

**Expected behavior**
I would expect that every single bonus of a feat is listed separately in Effects.

**Environment:**
 - Browser any
 - Foundry Version 12.330
 - 5e System Version 3.3.1
 - Module Version 5.2.27
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**
- https://www.dndbeyond.com/characters/129802512

**Comment by MrPrimate** [comment]
This is already fixed, but likely won't be released until D&D system version 4.0.x is out, similar to https://github.com/MrPrimate/ddb-importer/issues/498.

I might release a branch to support earlier versions before that, but sufers from some breaking changes.

**Comment by MrPrimate** [comment]
Resolved in 6.0.0
