### ISSUE TITLE
Goggles of night (and possibly other vision-affecting items) apply twice

### ISSUE THREAD

**Issue by bhill298** [MrPrimate/ddb-importer#500]
**Describe the bug**
A character imported from a character sheet with goggles of night equipped gets 120 feet of darkvision instead of 60. This is because it imports the "additional sense" of 60 feet that the character gets in their dndbeyond character sheet, which stacks on top of the 60 feet darkvision from the goggles of night passive effect.
Currently, as a workaround, you can import a character with the goggles in their inventory but unequipped, then manually equip them in foundry. This will correctly apply the effect once.

**To Reproduce**
Import a character with goggles of night equipped (in my case, this was a character who did not already have innate darkvision). See that their darkvision range is 120 feet instead of 60. You can unequip the goggles of night and see that the character's innate darkvision range is 60.

**Expected behavior**
Darkvision is increased by 60 feet and not 120 feet.

**Environment:**
 - Chrome
 - Foundry 11.315
 - 5e System Version 3.3.1
 - Module Version 5.2.30

**Comment by MrPrimate** [comment]
Thanks, fixed in the next release
