### ISSUE TITLE
Unable to activate module

### ISSUE THREAD

**Issue by dpmcalister** [MrPrimate/ddb-importer#504]
**Describe the bug**
Trying to activate the module in FoundryVTT but it is greyed out and when you hover over it you get the following message: This module requires a maximum system version of 3.9.0 but your version is 4.0.0.

**To Reproduce**
1. Go to "two cogs in upper right"
2. Click on "Manage Modules"
3. Try to click on "DDB-Importer: A D&D Beyond Integrator"

**Expected behavior**
Being able to activate the module.

**Screenshots**
<img width="684" alt="Screenshot 2024-09-15 at 13 41 59" src="https://github.com/user-attachments/assets/a6efac0b-9096-4f94-9763-20d468a89b8b">

**Environment:**
 - Foundry Version 12.331
 - 5e System Version 4.0.0
 - Module Version 5.2.36
 - Does this behaviour occur with other modules disabled: Yes

**Comment by MrPrimate** [comment]
As per announcements on Patron and Discord, this module does not yet support v4.x of the D&D system due to the massive changes for Activities. A limited functionality version will be available this week.

**Comment by MrPrimate** [comment]
Resolved.
