### ISSUE TITLE
Character Import: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by wolffstarr** [MrPrimate/ddb-importer#507]
Created a Level 7 Cleric (this is a from-scratch recreation of a 2014 campaign character; the 2014 version has a different name and is not imported.) Character is https://www.dndbeyond.com/characters/132156394 

Upon attempting to import, I get "Getting Character data" for a few seconds, then get the following screen.

![image](https://github.com/user-attachments/assets/250a52b2-10fe-4e32-8bc7-37c3c0805030)

**To Reproduce**
1. Click on DDB logo on character sheet
2. Input character URL
3. Click "Start Import"

**Environment:**
 - Browser: Chrome
 - Foundry Version: 12.331
 - 5e System Version: 4.0.2
 - Module Version: 6.0.2
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**
This is a bare test system, with only two other actors created and this is the first import attempt I've made. I've attached the last two entries in the Console error log section. At first glance they look identical but I'm definitely not a coder, so I included both.

Let me know if I can provide any additional information.

[test-1726888082474.log](https://github.com/user-attachments/files/17082597/test-1726888082474.log)
[test-1726888059908.log](https://github.com/user-attachments/files/17082598/test-1726888059908.log)

**Comment by MrPrimate** [comment]
Fixed in 6.0.3
