### ISSUE TITLE
dice string error

### ISSUE THREAD

**Issue by ErdanThren** [MrPrimate/ddb-importer#510]
**Describe the bug**
When trying to import a character getting a "Error processing Character: TypeError: Cannot read properties of null (reading 'diceString')

**Environment:**
 - Browser Chrome
 - Foundry Version 12.331
 - 5e System Version 3.2.1
 - Module Version 5.2.30

**Additional context**

 - https://www.dndbeyond.com/characters/130483397
 
 - Details of any errors in the browser console (press F12).
[foundry.dukisnet.homelinuxserver.org-1727477694813.log](https://github.com/user-attachments/files/17171178/foundry.dukisnet.homelinuxserver.org-1727477694813.log)

**Comment by MrPrimate** [comment]
You are trying to import a 2024 character into a version of the module that does not support it. Please update to 6.x.x and &D 4.x.

This error is also fixed in v5.2.34 but that does not support your D&D version.

See also https://github.com/MrPrimate/ddb-importer/blob/main/FAQ-2024-DND.md
