### ISSUE TITLE
wealthDice being null causes fatal error

### ISSUE THREAD

**Issue by natedogg484** [MrPrimate/ddb-importer#511]
at line 367 in shared.js and line 1095 in DDBClass.js the checks are not catching for the value of this.ddbClassDefinition.wealthDice being null. This is allowing the next parts of the code being called where since the diceString and diceMultiplier are not set a type error is thrown. Adding a small check for the value of wealthDice being/not being null would resolve this.

 I tried to create and push a branch with a fix to make a pull request for but I do not have permission to do so. My bad.

DDBClass.js:

  _generateWealth() {
    if (!this.ddbClassDefinition.wealthDice && this.ddbClassDefinition.wealthDice != null) return;
    const diceString = this.ddbClassDefinition.wealthDice.diceString;
    const diceMultiplier = this.ddbClassDefinition.wealthDice.diceMultiplier;
    this.data.system.wealth = diceMultiplier && diceString
      ? `${diceString}*${diceMultiplier}`
      : "";
  }

shared.js:

if (klass.wealthDice && klass.wealthDice != null) {
    const diceString = klass.wealthDice.diceString;
    const diceMultiplier = klass.wealthDice.diceMultiplier;
    result.system.wealth = diceMultiplier && diceString
      ? `${diceString}*${diceMultiplier}`
      : "";
  }

Edit: did some more checking and it is specifically failing when calling _generateWealth

**Comment by MrPrimate** [comment]
Please provide a character url and an version for DDB importer this is happening in, as I believe it is fixed, and is caused normally by trying to import a 2024 character using a version of DDB Importer that does not support it.

**Comment by natedogg484** [comment]
That was it! Thanks

**Comment by natedogg484** [comment]
Sorry, closing.
