### ISSUE TITLE
Cannot import items

### ISSUE THREAD

**Issue by Somel1978** [MrPrimate/ddb-importer#514]
**Describe the bug**
Cannot munch items

**To Reproduce**

**Expected behavior**
items in compendium

**Screenshots**
![image](https://github.com/user-attachments/assets/8c5f2948-50de-47c9-a3d6-cd5a3fb716fb)
![image](https://github.com/user-attachments/assets/4cd773c0-5d3a-48a7-a04c-87c8a378737d)
![image](https://github.com/user-attachments/assets/f7d4cde5-b5c1-49ba-8f8b-be7929e3f351)

**Environment:**
 - Browser [e.g. chrome]
 - Foundry Version [e.g. 12.331]
 - 5e System Version [e.g 4.0.4]
 - Module Version [e.g 6.0.2]

**Additional context**

 - A Character URL, if the problem is a character import.
 - Details of any errors in the browser console (press F12).

**Comment by MrPrimate** [comment]
Looks like a problem with a module.

Please disable all other modules and try again
 You can use the Culprit module to disable other modules

**Comment by MrPrimate** [comment]
Fixed in 6.0.27.
