### ISSUE TITLE
Exception importing character with automations enabled

### ISSUE THREAD

**Issue by jmroot** [MrPrimate/ddb-importer#517]
**Describe the bug**
Importing a particular character (Level 11 Fighter/Eldritch Knight) fails with an exception when the recommended automation modules are enabled.

**To Reproduce**
1. Enable DAE, Midi-QOL, Times Up modules
2. Go to character sheet
3. Click on D&D Beyond import button
4. Click Start Import
5. Click Auto when the resource selection window pops up
6. See error

**Expected behavior**
Character is imported without error.

**Screenshots**
![Screenshot 2024-11-02 at 15 55 26](https://github.com/user-attachments/assets/eeb03d5c-fa5c-4976-ba56-fb9a8a9b70c1)

**Environment:**
 - Browser: Firefox 132.0
 - Foundry Version: 12.331
 - 5e System Version: 4.0.4
 - Module Version: 6.0.26
 - Does this behaviour occur with other modules disabled: No (But it does occur with only the required automation modules: DAE, Midi-QOL, Times Up)

**Additional context**
https://www.dndbeyond.com/characters/2139080

The other characters in the campaign import OK.

Looks like the exception might be getting thrown somewhere around here: https://github.com/MrPrimate/ddb-importer/blob/main/src/parser/features/CharacterFeatureFactory.js#L272
Console output: 
[console-export-2024-11-2_16-2-25.txt](https://github.com/user-attachments/files/17605657/console-export-2024-11-2_16-2-25.txt)

**Comment by MrPrimate** [comment]
I do not believe there are versions of DAE and Midi which support D&D4 yet. Which version of these modules are you using?

**Comment by jmroot** [comment]
DAE 12.0.1, Midi QOL 12.4.6

**Comment by MrPrimate** [comment]
Please can you also make your character publically accessible.

**Comment by MrPrimate** [comment]
This _might_ be fixed in 6.0.27, but unable to check without a public URL.

**Comment by jmroot** [comment]
> Please can you also make your character publically accessible.

Ah sorry, I didn't notice it's not public. It's not actually my character, so here's another one with the same build that also exhibits the problem: https://www.dndbeyond.com/characters/135701363

**Comment by jmroot** [comment]
> This _might_ be fixed in 6.0.27, but unable to check without a public URL.

Confirming that the character can now be imported with the new version. Thank you!
