### ISSUE TITLE
Spell Muncher hangs on "Generating Spell List Journals"

### ISSUE THREAD

**Issue by wolffstarr** [MrPrimate/ddb-importer#522]
**Describe the bug**
Spells Import appears to hang on "Generating Spell List Journals". Under DDB Journals compendium, there is a Spell Lists folder with one entry in it of Basic Rules (2014) but that Journal is blank. I've left it to sit for quite some time (at least 10-15 minutes) with no progress, and the system it's running on does not show a noticeable increase in resource usage.

**To Reproduce**
1. Settings Tab: Only "Use icons from inbuilt dictionary" and "Exclude legacy things from import" options are checked.
2. Spells Tab: Only "If no other icon, use D&DBeyond spell school icon" option is checked.
3. Click on "Spell Munch"
4. Muncher proceeds through "Downloading data", creates and processes all the spells (confirmed the spells imported correctly), and then shows "Generating Spell List Journals" indefinitely.

**Expected behavior**
Spell List Generation completes.

**Screenshots**

**
![image](https://github.com/user-attachments/assets/c8827d91-d358-4d41-937a-a226370e43e4)
**

**Environment:**
 - Browser: Chrome
 - Foundry Version: 12.331
 - 5e System Version: 4.1.1
 - Module Version: 6.0.40
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**

 - A Character URL, if the problem is a character import.
 - Details of any errors in the browser console (press F12).

![image](https://github.com/user-attachments/assets/60fbe984-b664-4434-9ced-57bb71e892c1)

**Comment by MrPrimate** [comment]
Resolved in 6.0.41
