### ISSUE TITLE
Adventure import and spell importer fails

### ISSUE THREAD

**Issue by TheGrim159** [MrPrimate/ddb-importer#523]
**Describe the bug**
When I press spell munch or when I click import generated adventure it fails. The spell importer gets stuck on green-flame blade and when I import an adventure it fails when it gets to green flame blade as well.

**To Reproduce**
1. Go to DDB muncher and then press spells or adventures
2. Click on spell munch or import generated adventure
3. See error

**Expected behavior**
It to complete the importing of spells and adventures

**Screenshots**
![Foundry_Virtual_Tabletop_vJPKFZXHms](https://github.com/user-attachments/assets/a5e6219f-0ba9-4a8d-bd33-79c49432b4b1)
![Foundry_Virtual_Tabletop_CDOAYC360q](https://github.com/user-attachments/assets/d50cf648-b62c-438b-b3d1-f124c4b9c14e)
![cTJjc1Wk4q](https://github.com/user-attachments/assets/18b4477d-75cb-4400-a8e4-ef95299c621e)
![Foundry_Virtual_Tabletop_kuRkAn0VlY](https://github.com/user-attachments/assets/339f0756-8753-42ff-8bd5-591618952891)
![Foundry_Virtual_Tabletop_mtQxBmxAQb](https://github.com/user-attachments/assets/4d249f84-a022-4c91-a3fb-20eb70542e32)

**Environment:**
 - Browser Foundry
 - Foundry Version 12 Build 331
 - 5e System Version 4.1.1
 - Module Version 6.0.48
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**

 - Cannot read properties of null

**Comment by MrPrimate** [comment]
This was fixed in 6.0.49, released a few hours before this bug report.
