### ISSUE TITLE
Resilient feat doesn't apply ability point bonus

### ISSUE THREAD

**Issue by dafzor** [MrPrimate/ddb-importer#524]
**Describe the bug**
When picking the [Resilient](https://www.dndbeyond.com/sources/dnd/phb-2024/feats#Resilient) feat the imported feat does not apply the extra abilitity point bonus.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a character with the resilient feat
2. import into foundry
3. Notice the ability score difference from dnd beyond and foundry

**Expected behavior**
Feat passive effect should include the ability score increase

**Environment:**
 - Browser: Firefox 132.0.2
 - Foundry Version: 12 Build 331
 - 5e System Version: 3.3.1 and 4.1.1
 - Module Version:  5..2.37 and 6.0.49
 - Does this behaviour occur with other modules disabled: Yes

 - https://www.dndbeyond.com/characters/116828685

**Comment by MrPrimate** [comment]
Thank you for this report. The 2024 version of this adds a new restriction to the ability score increase which was not present in the previous rules "That you do not have Saving Throw Proficiency in.". This is fixed in the 6.0.50 release of the module, in the next 24 hours or so.
