### ISSUE TITLE
Companion Import creates empty folder

### ISSUE THREAD

**Issue by Kriosplayz** [MrPrimate/ddb-importer#525]
On every Charakter i tried to import, the companion import didn't work. It just created an empty Folder "[Extras] <name>" but not the contents of implemented extras.

I'm working with:
Foundry: 12.331
DnD5e: 4.1.1
Module Version: 6.0.51

**Comment by MrPrimate** [comment]
Thankyou for the report. Sorry for the delay on this, you did not report all the information requested in the bug template:

- Does this behaviour occur with other modules disabled: Yes/No (Find The Culprit module can help with this)
- Details of any errors in the browser console (press F12).

I will issue a fix in the next couple of days.

**Comment by Kriosplayz** [comment]
I had no other modules activated.

Logger.mjs:89 DDB Importer | ERR > Failure parsing extra TypeError: Cannot read properties of undefined (reading 'name')
    at new DDBCompanionFactory (DDBCompanionFactory.mjs:286:127)
    at generateCharacterExtras (DDBExtras.js:551:33)
    at async HTMLButtonElement.<anonymous> (DDBCharacterManager.js:592:20)
log @ Logger.mjs:89
error @ Logger.mjs:132
generateCharacterExtras @ DDBExtras.js:556
await in generateCharacterExtras (async)
(anonymous) @ DDBCharacterManager.js:586
Logger.mjs:91 DDB Importer | ERR > TypeError: Cannot read properties of undefined (reading 'name')
    at new DDBCompanionFactory (http://localhost:30000/modules/ddb-importer/dist/main.mjs:2:841874)
    at generateCharacterExtras (http://localhost:30000/modules/ddb-importer/dist/main.mjs:2:349111)
    at async HTMLButtonElement.<anonymous> (http://localhost:30000/modules/ddb-importer/dist/main.mjs:2:1447880)
log @ Logger.mjs:91
error @ Logger.mjs:132
generateCharacterExtras @ DDBExtras.js:557
await in generateCharacterExtras (async)
(anonymous) @ DDBCharacterManager.js:586
chrome-extension://gnblbpbepfbfmoobegdogkglpbhcjofh/images/icons/badges/custom20.png:1 
        
These are the errors in the console.
