### ISSUE TITLE
Sourcerous burst import does not work as it should

### ISSUE THREAD

**Issue by Popchip9** [MrPrimate/ddb-importer#526]
**Describe the bug**
Sourcerous burst is intended to be a attack that does 1d8 + level scaling and gets extra damage roles if you roll an 8, the extra roles part works correctly but by default it doesnt let you choose damage before rolling and instead rolls damage for all available damage types for the spell causing massively inflated spell damage compared to expected

**To Reproduce**
1. Make sorcerer on dndbeyond with sorcerous burst
2. import character to foundry
3. check the spells

**Expected behavior**
It should only roll for the damage type you want instead of all of them at once

**Screenshots**

**Environment:**
 - Browser Edge
 - Foundry Version 12.331
 - 5e System Version 4.1.1
 - Module Version 6.0.50
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**

 - A Character URL, if the problem is a character import.
 - Details of any errors in the browser console (press F12).

**Comment by MrPrimate** [comment]
Thank you, I had to change how some damage hints worked and this got missed in the processes. Fixed in 6.0.52
