### ISSUE TITLE
No Proficiency for subsequently added tools.

### ISSUE THREAD

**Issue by vaka42** [MrPrimate/ddb-importer#529]
**Describe the bug**
For player characters: 
Tool proficiencies that are subsequently added to the character sheet are not imported with proficiency. They remain marked as not proficient in the character sheet in FoundryVTT. 

**How To Reproduce**
1. Add a proficiencies for a Tool in the D&D Beyond Sheet
![grafik](https://github.com/user-attachments/assets/03e68c5f-1220-4222-ad23-233cf18ad066)
2. Import the character as usual.
3. See error
![grafik](https://github.com/user-attachments/assets/be48c14b-833b-4c4d-8b87-2dd38d53324d)

**Expected behavior**
The proficiency should be adopted as normal. If the tool is proficient in the D&Dbeyond sheet, this should also be adopted in the FoundryVTT sheet.

**Screenshots**
see above

**Environment:**
 - Browser: Firefox [133.0.3 (64-Bit)]
 - Foundry Version [12.331]
 - 5e System Version [4.1.2]
 - Module Version [6.0.54]

Best regards
Vaka!

**Comment by MrPrimate** [comment]
What module version are you using, because that version isn't supported for that version of D&D system?

**Comment by vaka42** [comment]
ahh my mistake! i looked at the latest version on github! i had version 6.0.54 installed. I'll correct that in my first post.

**Comment by MrPrimate** [comment]
Thanks. I can replicate it here. The fix will be in the next update, probably sometime within the next week. Hopefully, you can live with this minor annoyance until then!
