### ISSUE TITLE
Error parsing Character: TypeError: Cannot read property 'concat' of undefined

### ISSUE THREAD

**Issue by Harshmage** [MrPrimate/ddb-importer#54]
FoundryVTT 0.7.9
DDB-Importer 0.2.1
DDB-Importer-Chrome 0.0.2 (cookie configured)

https://character-service.dndbeyond.com/character/v4/character/21972349

Three other characters imported successfully, but this one just will not come over.  I can't find anything in specific to where the issue is on the character sheet, and I've tried turning on Debug logging to provide something more, but there is no output in the console, or in any log file I can find for DDB Importer.

**Comment by MrPrimate** [comment]
Thanks for your report, this should be fixed in 0.2.3 - I think it was some bad handling of customised spells/attacks/items in the code.
