### ISSUE TITLE
Shield Spell incorrectly imported

### ISSUE THREAD

**Issue by Brimcon** [MrPrimate/ddb-importer#55]
When importing a character with a shield in their equipment and using the DAE Import option, the Shield Spell gets imported rather than the shield Item

**Comment by MrPrimate** [comment]
Hi @Brimcon this calls the function provided by the DAE module to add/swap items/features/spells, so the problem is upstream I'm afraid.

**Comment by MrPrimate** [comment]
Resolved in local implementation of DAE compendium match function
