### ISSUE TITLE
[Bug] Class Feature Expertise/Proficiencies ALL checked after import or re-import

### ISSUE THREAD

**Issue by damccull** [MrPrimate/ddb-importer#57]
After importing a character, clicking the Features tab, then the edit button on the class name, then the details tab, there is a button to choose class proficiencies that has EVERY proficiency checked. It should either check the ones the player has selected in dndbeyond or else leave them all empty.

![image](https://user-images.githubusercontent.com/401104/102835158-f602e280-43c3-11eb-9323-b4d2ac413095.png)

**Comment by MrPrimate** [comment]
Resolved in v0.2.10
