### ISSUE TITLE
Magic items imported from the DAE-SRD are unequipped during import

### ISSUE THREAD

**Issue by jegasus** [MrPrimate/ddb-importer#61]
When importing a character from DDB, if you have the "Use Dynamic Active Effects Compendium for matching items (requires DAE and SRD modules" option checked, some magic ttems are automatically unequipped, even though they might be set as "equipped" in DDB. 

I believe this is happening because of the data inside the DAE-SRD module. Several items have the `data.equipped` set to `false`. I'm guessing this overrides what is seen in DDB. 

Is there any way for the override to be the other way around? Whatever is written in DDB should override the default data inside DAR-SRD.

Thanks!!!

**Comment by jegasus** [comment]
I believe the same thing is happening with Attunement: items that are marked as "attuned" in DDB get un-attuned when imported using the DAE-SRD matching. I suspect that this is also because the items in the DAE-SRD have the `data.attuned` set to `false` by  default.

**Comment by MrPrimate** [comment]
Currently the DAE items/spells are equipped by calling a function provided by DAE to do the search and replace. https://gitlab.com/tposney/dae so DAE needs to be responsible for updating the equipped status.

**Comment by MrPrimate** [comment]
Resolved in local implementation of DAE compendium match function
