### ISSUE TITLE
Ac calculation on active effects with items doesnt work as intended.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [MrPrimate/ddb-importer#68]
everytime i import the ac calculation isnt correct. and even donnoning or doffing a shield doesnt add or subtract the ac bonus. the same thing happens with armor ac. taking them off doesnt change anything. if this could be fixed id really appreciate it.

**Comment by MrPrimate** [comment]
You will need to play with the Active effect settings around auto calculating AC - DDB importer works out your AC from DDB and puts it in the AC field - if your using auto calculating ac you may need to make some changes.
