### ISSUE TITLE
Divine Soul Sorcerer Feature Divine Magic not importet

### ISSUE THREAD

**Issue by ReneSHTW** [MrPrimate/ddb-importer#69]
After importing my Divine Soul Sorcerer I've noticed my "Bane" - Spell is missing. This is a Spell granted by the Divine Magic Feature and depending on the alignment of the character. 
It's a small issue though.

**Comment by MrPrimate** [comment]
This is working on my test character - can you provide a link to your character? (DM me on Discord if you want to keep this private).

**Comment by ReneSHTW** [comment]
Okay, sorry! I've tested it again in two different worlds and it works fine. My Bad! Sorry for wasting your time. 

/closed
