### ISSUE TITLE
Error when importing character: undefined

### ISSUE THREAD

**Issue by odcinek** [MrPrimate/ddb-importer#7]
Getting an error on character import, it only says "undefined", no other error messages (nothing in the console too).

Character link https://character-service.dndbeyond.com/character/v4/character/36221975

![image](https://user-images.githubusercontent.com/217108/98589605-6295a800-2282-11eb-9f83-d43b492ed272.png)

**Comment by MrPrimate** [comment]
Thanks for the report, I'll dig into it

**Comment by odcinek** [comment]
This is not happening anymore, and import happens as expected, closing

**Comment by MrPrimate** [comment]
I think this is related to the work on custom attack modifiers/names, there are some bugs there to iron out still.
