### ISSUE TITLE
 Magic items imported from the DAE-SRD are un-attuned during import

### ISSUE THREAD

**Issue by jegasus** [MrPrimate/ddb-importer#70]
When importing a character from DDB, if you have the "Replace DDB item with Dynamic Active Effects Compendiums for matching items/features (requires DAE and SRD module)" option checked, some magic items are automatically un-attuned, even though they might be set as "attuned" in DDB. 

I believe this is happening because of the data inside the DAE-SRD module. Several items have the `data.attuned` set to `false`. I'm guessing this overrides what is seen in DDB. 

Is there any way for the override to be the other way around? Whatever is written in DDB should override the default data inside DAR-SRD.

Here is a sample character with whom this is happening: https://www.dndbeyond.com/profile/phildias/characters/42424951

Thanks!!!

PS: Sorry for this report being very similar to my old one. It's just that it's a very similar, but not identical. problem. Thanks again!

**Comment by MrPrimate** [comment]
Ah, this should be working, I think this is because the attunement rules improved in the D&D5e system recently, and I'm not copying across the new flag on match. This is fixed in version 0.2.21 and above. (released later today).
