### ISSUE TITLE
Cannot read property 'type' of null when trying to import weapons

### ISSUE THREAD

**Issue by Jumbolaya** [MrPrimate/ddb-importer#71]
Hello!

It appears that I'm no longer able to import weapons without it throwing an error

![image](https://user-images.githubusercontent.com/65468850/104043085-eb589380-51a0-11eb-8c99-a8823775bda2.png)

Here is what I see in the console:

![image](https://user-images.githubusercontent.com/65468850/104043116-f4e1fb80-51a0-11eb-93c1-7fe7d1d39a41.png)

I did this with all modules disabled except ddb-import, iconizer, tokenizer, DAE, DAE-SRD.

This happens on existing characters (that I had imported before) as well as newly created. Tried to re-install ddb-importer (removing module and re-installing) to no avail. 

As a troubleshooting step, I decided to delete the import, create a fresh character, and start importing each item below one by one:

![image](https://user-images.githubusercontent.com/65468850/104043611-aaad4a00-51a1-11eb-8955-50a087894f9b.png)

What I found was the error only happens when "Weapons" is checked.

I think this issue started either when I updated ddb-importer (now at version 0.2.20) OR when I updated the DnD5e - Fifth Edition System to 1.2.1 (from 1.2.0). Running Foundry 0.7.9.

Let me know if there is any other info that could help.

**Comment by mbrauch24** [comment]
As a workaround for existing characters, one can go into their character sheet and delete the "unarmed strike" item, then import things (still with "Weapons" _unchecked_). This at least allows you to import everything else.

**Comment by Jumbolaya** [comment]
I actually think this is a bug with the DnD5e System.

https://gitlab.com/foundrynet/dnd5e/-/issues/924

I can confirm after an update that it is no longer an issue. Sorry for confusion.
