### ISSUE TITLE
Feature Request: Provide API to perform scripted setup and import of characters.

### ISSUE THREAD

**Issue by thomasmckay** [MrPrimate/ddb-importer#73]
To facilitate the periodic automatic update of fvtt, I'd like to be able to:
1) set dndb url (resulting in calls go `getCharacterId(URL)`, `getCharacterAPIEndpoint(characterId)`, and `actor.update()`
2) trigger `await` on character update

I could likely script this myself but the class and methods seem to be tied to the html and not a set of global methods. (Correct me if I'm wrong?)

**Comment by MrPrimate** [comment]
They currently are. This will be split out in a later update as I have a feature planned that requires it, but can't give you a timeframe right now.

**Comment by MrPrimate** [comment]
This feature now exists, to loop through all player characters in your world and update run the following:

```javascript
const actors = game.actors;
for (let [key, actor] of actors.entries()) {
  if ('ddbimporter' in actor.data.flags && actor.type === "character") {
    console.log('Importing: ' + actor.data.name);
    await DDBImporter.importCharacter(actor);
  }
}
```
