### ISSUE TITLE
Silvered Weapons

### ISSUE THREAD

**Issue by HippyCraig** [MrPrimate/ddb-importer#74]
Weapons marked as silvered are not imported.  The item is but the check box to mark them silvered is not coming over.

**Comment by MrPrimate** [comment]
This is actually fixed in the next version, the silvered and adamantine flags were only added in the most recent version of the D&D 5E system.

**Comment by HippyCraig** [comment]
cool thanks, this was just more of a suggestion to post, but I didn't know any other way but to post it under issues.  Great Job!!!
