### ISSUE TITLE
Attuned items dont stay attuned or have attuned attribute turned on

### ISSUE THREAD

**Issue by Mushie1** [MrPrimate/ddb-importer#75]
Items that require attunement or are currently attuned dont keep that attribute when imported

**Comment by MrPrimate** [comment]
Please can you provide a character link, and the options you have selected when importing. (screenshot works best for this)

**Comment by Mushie1** [comment]
Thanks for the quick reply. Let me know if you need more info. (its happened on 3 characters)
In this character you can see Shatterspike and Ring of spell storing require attunement (the ring is a homebrew if that makes any difference but shatterspike is from sunless citadel - purchased)
I am also using The Forge if that also makes any difference?
As for the options i selected, I am not sure - I have updated that character a couple of times.  I will start a new character in another world and let you know how it goes.

https://www.dndbeyond.com/profile/Mushie101/characters/31459823


































    On Monday, 11 January 2021, 11:23:05 pm AEDT, Jack Holloway <notifications@github.com> wrote:  
 
 


Please can you provide a character link, and the options you have selected when importing. (screenshot works best for this)

**Comment by MrPrimate** [comment]
The character imports for me with correct attunement options. Please can you confirm the version of ddb-importer you're using, and a screen shot of the options you use when importing. Thanks.

**Comment by Mushie1** [comment]
I just tried it on another character and it was all good, so I am not sure what happened to the other 2 characters. Thanks for checking, sorry to any hassle.  Do you want me to delete the comment in github?

Marcel.


    On Tuesday, 12 January 2021, 4:26:29 am AEDT, Jack Holloway <notifications@github.com> wrote:  
 
 


The character imports for me with correct attunement options. Please can you confirm the version of ddb-importer you're using, and a screen shot of the options you use when importing. Thanks.

**Comment by MrPrimate** [comment]
Please let me know if it re-occurs.
