### ISSUE TITLE
Importing Artificer Artillerist subclass fails

### ISSUE THREAD

**Issue by soulcat1** [MrPrimate/ddb-importer#76]
When I import an Artillerist the parser fails...I tests with a couple characters, and as soon at the lvl 3 of artificer and artillerist is hit the character will no longer import:
main.js:6258 DDB Importer | ERR > TypeError: Cannot read property 'value' of undefined
log @ main.js:6258
error @ main.js:6278
parseJson @ main.js:16578
(anonymous) @ main.js:18105
Promise.then (async)
(anonymous) @ main.js:18100
getCharacterData @ main.js:18070
(anonymous) @ main.js:18510
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
main.js:6256 DDB Importer | ERR > Error during parse: Cannot read property 'value' of undefined
log @ main.js:6256
error @ main.js:6278
parseJson @ main.js:16579
(anonymous) @ main.js:18105
Promise.then (async)
(anonymous) @ main.js:18100
getCharacterData @ main.js:18070
(anonymous) @ main.js:18510
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
main.js:6258 DDB Importer | ERR > JSON Fetch and Parse Error
log @ main.js:6258
error @ main.js:6278
(anonymous) @ main.js:18118
Promise.catch (async)
(anonymous) @ main.js:18117
getCharacterData @ main.js:18070
(anonymous) @ main.js:18510
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
main.js:6258 DDB Importer | ERR > TypeError: Cannot read property 'value' of undefined
log @ main.js:6258
error @ main.js:6278
(anonymous) @ main.js:18119
Promise.catch (async)
(anonymous) @ main.js:18117
getCharacterData @ main.js:18070
(anonymous) @ main.js:18510
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
main.js:6258 DDB Importer | ERR > TypeError: Cannot read property 'value' of undefined
    at calculateRange (http://10.0.0.107:30000/modules/ddb-importer/dist/main.js:11772:124)
    at http://10.0.0.107:30000/modules/ddb-importer/dist/main.js:12006:14
    at Array.map (<anonymous>)
    at getOtherActions (http://10.0.0.107:30000/modules/ddb-importer/dist/main.js:11990:6)
    at parseActions (http://10.0.0.107:30000/modules/ddb-importer/dist/main.js:12026:8)
    at parseJson (http://10.0.0.107:30000/modules/ddb-importer/dist/main.js:16557:19)
    at http://10.0.0.107:30000/modules/ddb-importer/dist/main.js:18105:29
log @ main.js:6258
error @ main.js:6278
(anonymous) @ main.js:18120
Promise.catch (async)
(anonymous) @ main.js:18117
getCharacterData @ main.js:18070
(anonymous) @ main.js:18510
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
main.js:6258 DDB Importer | ERR > TypeError: Cannot read property 'value' of undefined
log @ main.js:6258
error @ main.js:6278
(anonymous) @ main.js:18531
async function (async)
(anonymous) @ main.js:18510
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
main.js:6258 DDB Importer | ERR > TypeError: Cannot read property 'value' of undefined
    at calculateRange (http://10.0.0.107:30000/modules/ddb-importer/dist/main.js:11772:124)
    at http://10.0.0.107:30000/modules/ddb-importer/dist/main.js:12006:14
    at Array.map (<anonymous>)
    at getOtherActions (http://10.0.0.107:30000/modules/ddb-importer/dist/main.js:11990:6)
    at parseActions (http://10.0.0.107:30000/modules/ddb-importer/dist/main.js:12026:8)
    at parseJson (http://10.0.0.107:30000/modules/ddb-importer/dist/main.js:16557:19)
    at http://10.0.0.107:30000/modules/ddb-importer/dist/main.js:18105:29

**Comment by MrPrimate** [comment]
Can you make sure that you have all your options selected for the character once you've levelled - if that's not a problem can you either post a character link here or DM me on discord. Thanks.

**Comment by soulcat1** [comment]
All the options were selected.
I tried with 3 characters...
This character first where he was imported fresh
https://www.dndbeyond.com/profile/Soulcat/characters/40439906
This character I tried second Second where I advance him each level and
imported with each advancement (ending with artillerist)
https://www.dndbeyond.com/profile/Soulcat/characters/42666116
Finally this character I tried last who was a pure artificer Artillerist
https://www.dndbeyond.com/profile/Soulcat/characters/17101334

**Comment by MrPrimate** [comment]
What version of ddb-importer are you using?

**Comment by soulcat1** [comment]
I am using importer 0.2.24
foundry 0.7.9
dnd 1.2.2

**Comment by MrPrimate** [comment]
This is fixed in v0.2.25!
