### ISSUE TITLE
Error parsing Character: TypeError: Cannot read property 'label' of undefined

### ISSUE THREAD

**Issue by ehallick** [MrPrimate/ddb-importer#78]
I'm getting this error when trying to import a character.

Here is the link to the ddb character: https://www.dndbeyond.com/profile/MastonHammerfell/characters/42930604

I've successfully imported several other characters (including this one previously). I also verified I can still import other characters, so it seems to be something to do with this particular one.

All modules, systems up to date. DDB Importer version: 0.2.31

Attaching a screenshot of the error.

Any suggestions?

![image](https://user-images.githubusercontent.com/36142572/104930347-a8e64200-596a-11eb-8632-47a0c7541389.png)

**Comment by MrPrimate** [comment]
You haven't finished selecting your proficiencies and the character importer is crashing out. I will try and improve the error handling around this.

**Comment by ehallick** [comment]
Hi MrPrimate. Just a note to let you know that selecting the proficiencies fixed the problem and to say thank you for the quick reply.
