### ISSUE TITLE
CobaltKey is a Security Issue

### ISSUE THREAD

**Issue by rebeccaskinner** [MrPrimate/ddb-importer#79]
The application currently requires that you paste an authentication token into the module to configure it. This key is used to authenticate requests to D&D Beyond, so that data can be imported, however requests are proxied through mrprimate.co.uk, which will have complete access to authenticate as any user using the plugin.

This opens up a number of obvious privacy and security holes, as the remote server has credentials allowing it to take any arbitrary action on behalf of the user, including viewing billing details and other information.  There is no way to know what the remote server is doing with these credentials, how long they are stored for, or what security measures are in place to prevent them from being leaked.

If this proxy is indeed a hard requirement for the functionality of the plugin, then it is important that:

1. Users be better informed of the risk of sharing credentials, including documented mitigations (how to invalidate the token)
2. Requirements for the remote server should be documented so that users who are interested in doing so may self-host, rather than relying on a third party to proxy the requests

**Comment by Parasrah** [comment]
Point 2 could be pretty easily achieved by open sourcing the server and making `ddb-importer.api-endpoint` configurable. While open sourcing the server still doesn't give people any guarantees that that's what's running on the instance you provide, it does at least enable us to host code we can review ourselves. Also if it's not already open source, that already comes off somewhat suspicious imo

**Comment by MrPrimate** [comment]
I won't be open sourcing the backend at this time - I will improve the documentation about invalidating the credentials - for those looking for this information you just need to log out of D&D Beyond.

**Comment by IamWarHead** [comment]
You should encode the cobalt with rsa private/public key pair storing public key on the client and private on the backend. You will have to send the hash with the pubkey to your api before connecting ddb to resolve the hash with the key pair and you can use cobalt until reload.

Or you can store cobalts on backend associated with a uuid hashed with rsa or similar and the client just sends the uuid and the pub key to the backend. The Client does not need the cobalt at all, its needed for the backend (if im right) so after the user entered it once with that method you can eliminate it from foundry settings. 

Sorry my english is not my main, but i hope you can get what i wanna say.

**Comment by Parasrah** [comment]
For those interested, I have forked this module [here](https://github.com/Parasrah/ddb-importer) and have started work on my own proxy [here](https://github.com/Parasrah/ddb-proxy). I currently have character imports more or less working, will continue working on the other features as I have time. I will not be providing a public server, but for those interested in hosting it themselves I have removed all of the patreon/beta key functionality from the module, so as the other features are completed you will be able to use them without paying me (or anybody else). The proxy still needs a little more work before it can be easily hosted.

And for what it's worth @MrPrimate, I would have happily continued supporting you on Patreon and using your module had you just open sourced the proxy. I find it highly dubious that you chose not to, considering the security/privacy implications of what you're doing. If at any point you'd be willing to change your mind I'd be happy to help.

**Comment by MrPrimate** [comment]
@Parasrah there are changes coming, so please keep subscribed to this thread.

**Comment by MrPrimate** [comment]
Resolved, see https://github.com/MrPrimate/ddb-proxy

**Comment by Parasrah** [comment]
@MrPrimate it seems your claim that you're not storing cobalt sessions on your server isn't entirely true, as you are using a hash of the cobalt token as an identifier in the hash. For the same reason it's not safe to use `sha256` for a password hash, it's probably not safe to be using that for a proxy server open to the public with a bunch of people using it. Don't get me wrong, I did the same thing in my version of the proxy, but it's intended for only a couple people to be using it, and I was already thinking of switching over to something more appropriate like `bcrypt` or `Argon2`. At least it might be good to update your documentation to explain this.

Regardless I do appreciate you releasing the proxy, I imagine more people will feel comfortable self-hosting the official proxy rather than mine.
