### ISSUE TITLE
Unescaped character error when attempting to import character with curly apostrophe

### ISSUE THREAD

**Issue by MaxGabriel** [MrPrimate/ddb-importer#83]
I was attempting to import `Grum’shar`, from Chapter 1 of Waterdeep: Dragon Heist and got this error:

![image](https://user-images.githubusercontent.com/1274145/105656787-03166400-5e91-11eb-9e1e-c32857beec62.png)

Related, I'm not sure what search term to use when trying to import this character, given this issue.

**Comment by MrPrimate** [comment]
Enter Grum in the field and untick "Exact name match" - it will import a couple of monsters but will also grab the one you want. I'll get a real fix in ASAP.

**Comment by MrPrimate** [comment]
This will be fixed in the 0.3.3 release

**Comment by MaxGabriel** [comment]
Ok, just upgraded to 0.3.4. It looks like you no longer get the API error, but you also don't get any matches for `Grum’shar`, `Grum'shar`, or `Grumshar`

**Comment by MrPrimate** [comment]
This was a problem with the backend API and a clash with the "exact match" functionality - this should all work now.
