### ISSUE TITLE
Rename iconizer to tokenizer?

### ISSUE THREAD

**Issue by MaxGabriel** [MrPrimate/ddb-importer#86]
Currently the code and UI refers to an "iconizer". I'm guessing this is an outdated reference to the Tokenizer module. I think https://github.com/MrPrimate/ddb-importer/blob/9fc50ff598aab9273e19b11002ac2120fea88803/src/muncher/ddb.js#L371 should probably be replaced with "Tokenizer", but I'm not sure about the rest of the code.

**Comment by MaxGabriel** [comment]
Ok, I think this might be an issue in the code as well. If I dump `game.modules` I get (see the last entry)

![image](https://user-images.githubusercontent.com/1274145/106082422-ab723580-60e8-11eb-8cf0-c551a3e73312.png)

and if I do:

![image](https://user-images.githubusercontent.com/1274145/106082562-e6746900-60e8-11eb-9d90-b843fc8299e1.png)

So, this implies to me that the code should be changed as well, it's not just a display thing. This also matches up with what I'm experiencing in the UI, which is that "Use iconizer (if installed)." is grayed out as an option

**Comment by MrPrimate** [comment]
Hi Max, this is a module, but it was removed from Foundry when the authors hosting went down, he no longer maintains it however, you can find it here https://vtta.io/assets/vtta-iconizer or a fork here https://github.com/MrPrimate/vtta-iconizer - the module trys to provide matching icons from the WoW icon set. We are working to replace this functionality with the native Icons in Foundry.
