### ISSUE TITLE
D&D Beyond Importer slight incompatibility with Combat Utility Belt

### ISSUE THREAD

**Issue by JustinKovacich** [MrPrimate/ddb-importer#88]
![image](https://user-images.githubusercontent.com/32140377/106363508-f6fa2e80-62f6-11eb-8bde-effc308e1da7.png)

With CUB and D&D Beyond Importer active at the same time, the hide actors mask icon from CUB obscures the base sheet's race for some reason.  I did not have the Hide Actors option enabled, so this appeared all on its own.

**Comment by MrPrimate** [comment]
Hi @JustinKovacich  I've been fighting this CSS issue for a while with limited success, it appears hit or miss as to if it affects a system .There is a workaround that allows the import button to be placed into the title bar, from the image it looks like your version probably doesn't support this, but if you upgrade you should see it in the module settings.
