### ISSUE TITLE
Potent Spellcasting - import leads to incorrect formula

### ISSUE THREAD

**Issue by liz-is** [MrPrimate/ddb-importer#89]
Used the importer (v0.3.6) to import the sheet for a level 8 Light domain Cleric with Potent Spellcasting (adds wisdom mod to cantrip damage). This gives `1d8 + @mod` as the damage formula for Sacred Flame, but when actually rolling damage, the formula shown is `1d8 + @mod + 1d8 + 5 + @bonus`, leading to the wisdom modifier being added twice. I was able to fix this by specifying `1d8` as the scaling for Level Scaling = Cantrip, but it would be nice if this was done automatically. 

Let me know if something isn't clear or you need more information!

**Comment by MrPrimate** [comment]
This will be fixed in the next version, 0.3.7. Not sure if it has always been the case or if the cantrip scaling has recently changed to use the entire damage field rather than just the dice string. Thanks for the report!
