### ISSUE TITLE
D&D Beyond Importer not importing added weapon proficiencies

### ISSUE THREAD

**Issue by ChosenOne912** [MrPrimate/ddb-importer#90]
I have a character in D&D Beyond that is not naturally proficient with a warhammer, however they have been given proficiency in using a warhammer. Because of this, D&D Beyond shows the character as proficient with a warhammer and rolls within D&D Beyond include the proficiency bonus. Here's what shows up on D&D Beyond:

![D D_Beyond_Proficiency](https://user-images.githubusercontent.com/10257549/106394960-32632e80-63c5-11eb-9235-e3670547b623.PNG)
![D D_Beyond_Config](https://user-images.githubusercontent.com/10257549/106394961-342cf200-63c5-11eb-9973-d232910bf0bd.PNG)

When I import the character into Foundry using the module, the warhammer proficiency shows up under the characters weapon proficiencies, however when looking at the weapon in the characters inventory it is listed as not proficient. When rolling in Foundry, it does not include the proficiency bonus. This is what it looks like in the character sheet:

![Foundry_Proficiency](https://user-images.githubusercontent.com/10257549/106395062-c634fa80-63c5-11eb-83fa-1972df37fc55.PNG)
![Foundry_Config](https://user-images.githubusercontent.com/10257549/106395064-c7662780-63c5-11eb-9ff5-d654748c8902.PNG)

I have another character with the same issue except it is with a pistol, but it shows up in exactly the same way.

I am currently running and seeing this issue with
Foundry version 0.7.9
Module version 0.3.6

**Comment by MrPrimate** [comment]
Thanks for this report, this will be fixed in 0.3.7 which should be out in the next couple of hours.
