### ISSUE TITLE
Can no longer import characters

### ISSUE THREAD

**Issue by Rawrly85** [MrPrimate/ddb-importer#91]
Foundry 0.7.9
ddb-import 0.3.9

I can no longer import characters. I tried a fresh install, updating the cookie, character URL but all result in this same page without the ability to import a character. 

![image](https://user-images.githubusercontent.com/53245027/106697012-c46c6200-6592-11eb-96ed-0f9f5754ec65.png)

**Comment by MrPrimate** [comment]
Hi,

This looks like the module has been set to restrict Imports to Trusted User, but allow character sync (i.e. back to DDB) and the user is set to Player type permissions.

Can you post a screenshot of your settings?

**Comment by Rawrly85** [comment]
Either of those settings is currently enabled as I don't have a patron subscription to allow the sync back and my players aren't set to trusted (though if I'm logged in as a GM account, I don't think this should matter?)

Interestingly, when I logged on to a different device, the problem disappeared, the only difference being the OS (Windows had the problem, my mac doesn't).

**Comment by MrPrimate** [comment]
If you can reach out to me on Discord I'd love to log into your world and have a look.

**Comment by Rawrly85** [comment]
I no longer see the issues now. Next time it appears, I'll post on discord and see if you are around to check. I wonder if it was some sort of cache/cookie issue.
