### ISSUE TITLE
Error when importing characters 'filter undefined'

### ISSUE THREAD

**Issue by bakkerj05** [MrPrimate/ddb-importer#95]
I updated module today and whenever I try to import characters I get the following errors on all 6 of my player's actors. I was able to use it yesterday 2/12 when I installed module to replace vtta.

`Foundry VTT | Rendering CharacterImport
main.js:5784 DDB Importer | ERR > TypeError: Cannot read property 'filter' of undefined
log @ main.js:5784
main.js:5782 DDB Importer | ERR > Error during parse: Cannot read property 'filter' of undefined
log @ main.js:5782
main.js:5784 DDB Importer | ERR > JSON Fetch and Parse Error
log @ main.js:5784
main.js:5784 DDB Importer | ERR > TypeError: Cannot read property 'filter' of undefined
log @ main.js:5784
main.js:5784 DDB Importer | ERR > TypeError: Cannot read property 'filter' of undefined
    at parseFeatures (http://192.168.1.100:30000/modules/ddb-importer/dist/main.js:16662:6)
    at parseJson (http://192.168.1.100:30000/modules/ddb-importer/dist/main.js:21047:20)
    at http://192.168.1.100:30000/modules/ddb-importer/dist/main.js:21767:29
log @ main.js:5784
main.js:5784 DDB Importer | ERR > TypeError: Cannot read property 'filter' of undefined
log @ main.js:5784
main.js:5784 DDB Importer | ERR > TypeError: Cannot read property 'filter' of undefined
    at parseFeatures (http://192.168.1.100:30000/modules/ddb-importer/dist/main.js:16662:6)
    at parseJson (http://192.168.1.100:30000/modules/ddb-importer/dist/main.js:21047:20)
    at http://192.168.1.100:30000/modules/ddb-importer/dist/main.js:21767:29`

**Comment by MrPrimate** [comment]
Please can you provide a character URL

**Comment by kavukavu** [comment]
Hey I've had the same issue pop up MrPrimate, here is a character URL where this error occurred:

https://www.dndbeyond.com/profile/kavukavu/characters/33688903

**Comment by MrPrimate** [comment]
Hi @kavukavu I'm struggling to reproduce this, someone else reported something similar on Discord, and their cobalt token had expired, or rather was unable to access some content, so first thing to try is to grab a new one of those.

Next would be to let me know what version of Foundry, the D&D5e system, and the ddb-importer module you are using.

**Comment by jsmith2500** [comment]
Hello. I am getting this also. I have deleted and recreated the characters on D&D Beyond. For that last one I just kept it at level 1 and kept basic equipment and still get the error. I am a player, not the DM if that makes a difference.

**Comment by jsmith2500** [comment]
DM is running version  0.4.10

**Comment by MrPrimate** [comment]
A few other folks have reported this, and it may be that I'm not correctly catching situations where the cobalt cookie has expired - please can you try grabbing a new one.

**Comment by jsmith2500** [comment]
Hmmm... as a player I am not able to access the cobalt settings on this specific DM's foundry server.  I have my own foundry server that I tested this on and was able to import everything just fine when I was logged in as a DM. Are there some permissions settings that I need to tell my DM about to allow player access to the cobalt cookie entry?

**Comment by MrPrimate** [comment]
I have a fix for this in 0.4.12
