### ISSUE TITLE
DAE and User active effects get overwritten every update.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [MrPrimate/ddb-importer#96]
hi i have an issue thats bugging my players is that they are scared to update because they self program the active effects for their class abilities and items on their effects tab but when they level up or use dnd beyond importer it resets all of those and deletes them and redownloads only the armor based dae effects. could we have it so that we can have a tick box to retain any active effects upon update? it would really benefit my players and they wont be so scared or annoyed to use the update feature. loosing programing for stuff like great weapon master or sharpshooter and having to do it all over again is an annoyance for my players. 

thanks very much in advance!

**Comment by MrPrimate** [comment]
![retain_effect](https://user-images.githubusercontent.com/3985378/108108173-2d220700-7088-11eb-81fa-b440f4887153.png)
Ensuring that the following two options are ticked should do that.
