### ISSUE TITLE
Error parsing Character

### ISSUE THREAD

**Issue by kavukavu** [MrPrimate/ddb-importer#97]
This is an odd one for me. Tried updating characters today, literally all of the characters update fine, except for one that comes up with a "Error parsing Character: Please Update your D&D 5e System to a newer version"

My D&D system is currently the latest version, and no other characters in the same campaign encounter this issue at all.

https://www.dndbeyond.com/profile/Velates/characters/33684514 <- This is the character in question

`main.js:5856 DDB Importer | ERR > Error: Please update your D&D 5e system to a newer version
    at getToken (http://localhost:30000/modules/ddb-importer/dist/main.js:15520:11)
    at getCharacter (http://localhost:30000/modules/ddb-importer/dist/main.js:15724:12)
    at parseJson (http://localhost:30000/modules/ddb-importer/dist/main.js:21150:21)
    at http://localhost:30000/modules/ddb-importer/dist/main.js:21872:29`

**Comment by MrPrimate** [comment]
Fixed in 0.4.13, sorry!
